### ISSUE TITLE
Suggestion: Rewrite text for the option to include or not subdomains when creating new containers.

### ISSUE THREAD

**Issue by rgamici** [stoically/temporary-containers#102]
On Isolation tab, and mouse clicks tabs, we have:

**When navigating in Tabs should open new Temporary Containers:**
- If the navigation target doesn't match the current Tabs Website Domain
- If the navigation target doesn't match the current Tabs Website Domain (includes Subdomains)

I found the current text a little confusing.
Just reading them I have no idea if "includes Subdomains" refer to matching also the subdomains (current functionality) or refers to navigation target, and the subdomains would open in a different container (my first guess).

I suggest rewriting them as:
If the navigation target doesn't match the current Tabs Domain (Different Subdomains will be isolated)
If the navigation target doesn't match the current Tabs Domain (Different Subdomains won't be isolated).

Also:
The options for Mouse click > Middle click have a slightly different text.

And finally:
I did not know it was just an html file, and submitted a pull request with this suggestion.

**Comment by stoically** [comment]
Hey, thanks for the suggestion. I guess you're right that the option texts regarding subdomains could be a bit more explicit. After the refactoring in #91 it won't be called "Isolation" anymore, but instead just "Navigating should open new Temporary Containers"

So, how about:

**Navigating should open new Temporary Containers**
* If the Navigation Target Domain does not exactly match the current Tabs Domain - Subdomains are affected
* If the Navigation Target Domain does not match the current Tabs Domain - Subdomains are not affected

**Mouse Clicks on Links should open new Temporary Containers**
* If the clicked Links Domain does not exactly match the current Tabs Domain - Subdomains are affected
* If the clicked Links Domain does not match the current Tabs Domain - Subdomains are not affected

Also, if you have an opinion on the preferences "per website" refactoring here https://github.com/stoically/temporary-containers/issues/91#issuecomment-375048222 I'd be interested to hear it too.

**Comment by rgamici** [comment]
I liked yours text more, but I still think they are too similar to each other.

I suggest to make them a single option ("If the clicked Links Domain does not match the current Tabs Domain"), and then show a checkbox to select how to control the subdomains.
However, I do not remember if this can be done easily without breaking other stuff.

I have not separated some websites using the custom rules.
I will try it, and give you a feedback later.

**Comment by stoically** [comment]
> and then show a checkbox to select how to control the subdomains.

While this is a good idea, the checkbox would need some text to explain what it does too. And if that text explains the behavior well, then it could also just be included in the dropdown instead. :D

Maybe:

**Navigating should open new Temporary Containers**

* If the Navigation Target Domain does not exactly match the current Tabs Domain (Subdomains of the current Tabs Domain are not matched)
* If the Navigation Target Domain does not match the current Tabs Domain (Subdomains of the current Tabs Domain are matched)

**Mouse Clicks on Links should open new Temporary Containers**

* If the clicked Links Domain does not exactly match the current Tabs Domain (Subdomains of the current Tabs Domain are not matched)
* If the clicked Links Domain does not match the current Tabs Domain (Subdomains of the current Tabs Domain are matched)

Also, at some point it might be a good idea to add some documentation and link it in the options, that way a more thorough explanation could be included.

**Comment by stoically** [comment]
> I have not separated some websites using the custom rules.
> I will try it, and give you a feedback later.

It also merges the Global Preferences for Isolation and MouseClicks. Thanks in advance!

**Comment by stoically** [comment]
Since I decided to keep it "Isolation" as title for the merged tabs I took your suggestion and came up with

**Navigating**
* If the Navigation Target Domain does not exactly match the current Tabs Domain (Subdomains also get isolated)
* If the Navigation Target Domain does not match the current Tabs Domain (Subdomains get not isolated)

**Mouse Clicks**
* If the clicked Link Domain does not exactly match the current Tabs Domain (Subdomains also get isolated)
* If the clicked Link Domain does not match the current Tabs Domain (Subdomains get not isolated)

This will be published with the next version. If you have further suggestions feel free to let me know.

**Comment by stoically** [comment]
Just published version 0.80 with the changes. Hope you like it.
