### ISSUE TITLE
Isolation based on path

### ISSUE THREAD

**Issue by stoically** [stoically/temporary-containers#116]
Would be nice to have an additional option for Isolation that enables to specify paths. E.g. I'd like to stay in the same tmp as long as I'm navigating github.com/example/example and deeper paths, but as soon as I "leave" that path Isolation should take place. Not exactly sure how to implement that yet tho

- Same tmp as long as path `/([^/]+/[^/]+)(\/.+)?` is matched
- *But* new tmp if $1 changes

**Comment by eberhardweber** [comment]
This is a feature that I have been looking for in container add-ons as well. I believe there are lots of Reddit users who would want to possibly sandbox certain /r/subfolders on the domain while browsing the rest normally!

**Comment by stoically** [comment]
I guess having the RegExp is enough for now, maybe I'll come back to this at some point.
