### ISSUE TITLE
Question: Multiple bookmarks same domain

### ISSUE THREAD

**Issue by Decopi** [stoically/temporary-containers#119]
Hi @stoically ,

I have a question about opening multiple bookmarks in same domain. Please, answer me only if you want/can, and feel free to close my issue:

For example at Facebook, I successfully managed to set your add-on, in a way that Facebook always opens in container tab, and everything I click inside this tab opens in a new separate container tab, and I don't need to login again.

However in this example, even if I keep opened my original Facebook container tab, if I open a new separate container tab... I am forced to login again into Facebook. In brief:
- Clicking links inside logged container tab => it opens separate container tab, but there is no need to login again.
- Opening a new container tab with same domain already logged-in in other opened container tab => It asks for login again.

I failed to set Facebook in a way that once logged-in, it always keep me logged-in (until closing last Facebook container tab, or closing Firefox). I know is my fault, I read the wiki, I played around with different settings, and I can't make it works.

It is worst when I try to use bookmarks.
For example, I open Facebook in new container tab, I login, then I go to bookmarks => my folder "Facebook" with 20 links of different Facebook pages => "open all"... and each Facebook bookmark link opens in new separate tab container... but I need to login each container tab.

I would appreciate your help.
Thank you very much

**Comment by stoically** [comment]
If you're looking for a way to stay loggedin in a container, then you'd have to use permanent containers instead - since that's out-of-scope for Temporary Containers (though, it's possible with the Advanced > Set Cookies feature, but that should only be used if you know what you're doing). I'd encourage you to use the Multi-Account Containers Add-on for that purpose - a quick guide how to achieve your desired behavior is to be found [on AMO under "How to stay logged in"](https://addons.mozilla.org/firefox/addon/temporary-containers/). Hope that helps.

**Comment by Decopi** [comment]
OK! Understood.
Shame on me: The day I installed the add-on, I read the AMO, and forgot this guide.

A suggestion for a future option: Make the FF' context menu to work with TC, allowing the user to open a bookmark link in a new tab, but using an existing container number. My hope is that in the future, this option also will work with already logged-in container tabs.

**Comment by stoically** [comment]
Support for the [bookmark context menu](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/ContextType) [landed in Firefox 59](https://bugzilla.mozilla.org/show_bug.cgi?id=1370499#c34). That's something I can look into implementing.

To support Permanent Containers there as well you might want to vote over at MAC: https://github.com/mozilla/multi-account-containers/issues/323

**Comment by stoically** [comment]
Sorry for the open/reopen spam - opened #121 for the suggested bookmark context menu feature.
