### ISSUE TITLE
Disbled Isolation of Permanent containers is not honoured

### ISSUE THREAD

**Issue by physkets** [stoically/temporary-containers#122]
- Temporary Containers Version: **0.85**
- Firefox Version: **59.0.2**
- Operating System + Version: **Arch Linux**
- Non-default Options/Preferences in Temporary Containers: 
Isolation > Global: I have all options set to **If the Navigation Target Domain does not match the active Tabs Domain (Subdomains won't get isolated)**
- Other installed Add-ons + Version: 
Canvas Defender	1.1.0
Decentraleyes	2.0.3
Firefox Multi-Account Containers	6.0.0
Flagfox	6.0.4
Google search link fix	1.6.7
HTTPS Everywhere	2018.4.3
NoScript	10.1.7.5
Privacy Badger	2018.3.21
Simple Tab Groups	2.5.3
uBlock Origin	1.15.24	true
Video DownloadHelper	7.2.2
MathML Copy	1.3.2
Terms of Service; Didn’t Read	0.6.2

### Actual behavior
I have Isolation > Multi-Account Containers > "Open new Temporary Containers if a Permanent Container Tab tries to load a Domain that isn't assigned to "Always open in" that container" set to **Disabled**, but if a tab in a permanent container opens another domain, it still opens a new temp.

### Expected behavior
It should remain in that permanent container
[firefox_temp-container_debug.txt](https://github.com/stoically/temporary-containers/files/1879029/firefox_temp-container_debug.txt)

**Comment by stoically** [comment]
Hey, thanks for the report.

Per Domain or Global Isolation always does what it says - the Multi-Account Containers Isolation is just a feature on top to avoid loading of not with MAC assigned URLs in Permanent Containers; it doesn't disable Per Domain or Global Isolation.

In you case you'd have to configure for the Domain where you don't want the configured Global Isolation to apply a specific Per Domain Isolation and set it e.g. `Never` where applicable. Hope that helps, let me know if not.

**Comment by physkets** [comment]
Ah, in that case, isn't that description a little misleading? Because what I escribed is what I expected from that option.

But do you think it can be made to work that way? Because I think it would be very useful.

The scenario in which I need it the most is 'payment portals'. Lots of websites where I have to buy things (most of which I have permanent containers for) re-direct to a variety of payment portals, and this fails if I have Global options set to opening new temporary containers.

**Comment by stoically** [comment]
@physkets Yep, good idea, added to the #104 list. I'll also try to clarify the MAC Isolation - any suggestions what could help here?

**Comment by physkets** [comment]
The option: *Open new Temporary Containers if a Permanent Container Tab tries to load a Domain that isn't assigned to "Always open in" that container* should then be left for when you complete that feature.

Instead you can call it *Open new Temporary Containers if a Permanent Container Tab tries to load a Domain that is assigned to "Always open in" that container*

The only difference being **isn't** -> **is**. Both these options can be under Isolation > Multi-Account Containers, where it is right now.
