### ISSUE TITLE
Windows Shortcut

### ISSUE THREAD

**Issue by stoically** [stoically/temporary-containers#123]
So, it seems like Alt+Shift+T on windows opens the tools menu now. I'm pretty sure I've tested that and the reason for changing was that Alt+C opened the history menu (which doesn't seem to happen anymore). I guess this needs a change again.

**Comment by listalltabs** [comment]
Just so you know, Alt+Shift+T is now working again with TC 0.89, on both v59.0.3 and up-to-date Nightly v61.

If possible, it would still be nice to have Alt+C become the shortcut on Windows sometime, for consistency across systems, and just because it's *so* much more convenient. :)

**Comment by vertigo220** [comment]
It should just be customizable so the user can set it to whatever they want. Personally, I'd prefer to just set it to Ctrl+T to replace the standard tab opening with a new container tab.

**Comment by stoically** [comment]
@listalltabs 

Interesting. The changes keep happening huh. :) I have to check if Alt+C opens the History Menu again on Windows (maybe only with certain Keyboard Layouts) before changing.

@vertigo220 

Customizable isn't supported by Firefox unfortunately. You have to hardcode the shortcuts in the `manifest.json`. You can build your own Shortcut-Handler completely in JavaScript and embed it as contentscript, but doing so would still clash with existing Hotkeys and doesn't work on restricted pages like e.g. `about:` or `moz-extension:`

**Comment by listalltabs** [comment]
As noted by @r-a-y  in #60, Alt+Shift+T is no longer working again, in either v60 or v62. It's back to bringing up the Tools menu on the Menu Bar! So weird! Alt+C is looking better every day! :smile: 

For the record, I can't find any mention of Alt+C ever bringing up the History menu, so maybe that was just another glitch too!

**Comment by r-a-y** [comment]
FWIW, I would also prefer <kbd>Alt</kbd> + <kbd>C</kbd>.

It's the same shortcut as with the Containers On The Go extension and is simpler to hit than <kbd>Alt</kbd> + <kbd>SHIFT</kbd> + <kbd>T</kbd>.

**Comment by stoically** [comment]
Alt+C published with version 0.90
