### ISSUE TITLE
Multi Account Containers Isolation: permanent containers whitelist

### ISSUE THREAD

**Issue by ThinkChaos** [stoically/temporary-containers#124]
I use the "Open new Temporary Containers if a Permanent Container Tab tries to load a Domain that isn't assigned to "Always open in" that container" option.
I'd still like to be able to go to navigate anywhere in some permanent containers.

My use case is having multiple accounts on one site: I can't associate the site to a single container using "Always open in", so I open a tab of the permanent container I use for account X, and go to the site.
With Multi Account Containers isolation, instead of using the container I chose, it opens in a temporary container.

**Comment by stoically** [comment]
Hey, you're right, that's definitely that needs to be added. It's on the list over in #104 - you can follow progress there. A workaround to get redirected domains on the "Always open in" list is to temporarly set `network.http.redirection-limit` in `about:config` to 0. Hope that helps.
