### ISSUE TITLE
Containers are not created automatically and manual button is greyed out

### ISSUE THREAD

**Issue by roanutil** [stoically/temporary-containers#131]
Temporary Containers Version: .87
Firefox Version: 59.0.2
Operating System + Version: Windows 10 Pro Ver 1709 Build 16299.371
Non-default Options/Preferences in Temporary Containers: Automatic mode, Random color/icon, Global Always, Multi-Account Containers Enabled
Other installed Add-ons + Version: 1Password 4.7.0.90, Cisco WebEx 1.0.14, Diable WebRTC 1.0.20, HTTPS Everywhere 2018.4.11, Privacy Badger 2018.4.10, uBlock Origin 1.15.24

### Actual behavior
..No containers are created for new tabs, links, etc. Cannot click the new container button manually. It's greyed out.

### Expected behavior
..New containers should be created somehow.

**Comment by Perflyst** [comment]
Do you use the private mode? This addon will not work in private browsing mode.
If you are not aware of this, check `about:config` for `browser.privatebrowsing.autostart` if it is true or false.

**Comment by roanutil** [comment]
@Perflyst That was it. Not sure why I had private mode enabled on this computer, but that was the problem.
