### ISSUE TITLE
Alt-C and Open New Tab not working

### ISSUE THREAD

**Issue by briant97** [stoically/temporary-containers#133]
I cannot use Alt-C and also when I set even a new tab option to open temp containers it doesn't appear to open with Red indicator that I am in a temporary container.  Maybe I have to many temporary containers installed?

- Temporary Containers Version: Latest
- Firefox Version: Latest
- Operating System + Version: Linux Mint 18.3
- Non-default Options/Preferences in Temporary Containers: 
- Other installed Add-ons + Version: 
Cookie AutoDelete	2.1.2	true	CookieAutoDelete@kennydo.com
Decentraleyes	2.0.3	true	jid1-BoFifL9Vbdl2zQ@jetpack
Facebook Container	1.3.1	true	@contain-facebook
Google Container	1.0.2	true	@contain-google
HTTPS Everywhere	2018.4.11	true	https-everywhere@eff.org
Privacy Badger	2018.4.23	true	jid1-MnnxcxisBPnSXQ@jetpack
Switch Container Plus	0.14	true	{d5ac33ed-723c-402b-b17c-e7bbb0d3a80d}
Temporary Containers	0.89	true	{c607c8df-14a7-4f28-894f-29e8722976af}
uBlock Origin	1.16.0	true	uBlock0@raymondhill.net
xclear	1.8.1-signed	false	xclear@as-computer.de

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce

1. ..
2. ..
3. ..

### Notes
..

**Comment by stoically** [comment]
Can you click the Temporary Containers Icon or is it greyed out? If you can click it, what happens if you click it?

If it is greyed out, you're probably in a "Private Window" or are in Permanent Private Mode. In both cases Containers don't work in general. You can disable Permanent Private Mode by not selecting "Never remember history" in the Firefox History options.

**Comment by briant97** [comment]
Yes I do have those settings on :(.  It was greyed out.

**Comment by stoically** [comment]
Then you need to change that setting. Related: https://github.com/mozilla/multi-account-containers/issues/469

**Comment by stoically** [comment]
Opened https://github.com/stoically/temporary-containers/issues/134 to maybe have a feature that informs users about the fact that it won't work.
