### ISSUE TITLE
Support  for Containerise? 

### ISSUE THREAD

**Issue by Zorroblanco** [stoically/temporary-containers#136]
Hi, do you support Containerise (https://addons.mozilla.org/en-US/firefox/addon/containerise/?src=search) or only Firefox Multi-Account Containers? I use Containerise and have this problem https://framapic.org/oqah5ugT2saL/Jw3TSVzm5R18.gif Firefox 59.0.3 (x86) win 7 ultimate (x32) option: isolation, global, navigation in tabs shoud open... if the navigation target domiain...
Thanks, and sorry for my english, i hope you understand

**Comment by stoically** [comment]
Support for Containerise will soon be implemented since https://github.com/kintesh/containerise/pull/18 is meanwhile published. You can follow progress here #15
