### ISSUE TITLE
Improvement suggestion for container name prefix

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#140]
Is it possible to add option to container name prefix, to be prefixed by opening domain?

Thank you
cheers

**Comment by stoically** [comment]
I guess I could add replacement variables like `%domain%` (host + public suffix) and `%fulldomain%` (fqdn) that could be entered in the Prefix field as advanced option.

**Comment by stoically** [comment]
Just realized that replacement variables wouldn't be so nice, since there are cases like the default ways of opening a new Temporary Container where there's no data available about domains. If you e.g. set the prefix just to `%domain%`, you would end up with just a number as container name. The other way might be a checkbox like "Use domain-name as prefix if available", but I personally feel like that's really confusing. Which way would you prefer and where do you see the benefit in the feature itself?

**Comment by crssi** [comment]
> Just realized that replacement variables wouldn't be so nice, since there are cases like the default ways of opening a new Temporary Container where there's no data available about domains. If you e.g. set the prefix just to `%domain%`, you would end up with just a number as container name,

I really don't see any downsides to this.

Maybe it would also be nice to hard-prefix the number itself like `#1`. `#2`, `#3`.. etc.

Do not forget to trim() at the end of naming generation process.

Let's sleep over. :smile:

**Comment by listalltabs** [comment]
If the container name includes a domain, what would happen if there are two or more domains open in the same container? e.g.

- open site A in tmp1234
- open new tmp1234 tab
- open site B in that new tab

What would the container name be if a domain name was incorporated into it? To ensure site B didn't open in the same container as site A, isolation would need to be taken a step further I'd guess! :)

**Comment by stoically** [comment]
@crssi 

> I really don't see any downsides to this.

In this case - I've added it accordingly, will be available with the next release.

> Maybe it would also be nice to hard-prefix the number itself like #1. #2, #3.. etc.

You can do that by just adding a # as last character in the prefix.

> Do not forget to trim() at the end of naming generation process.

I don't want to limit people in being creative, even with whitespaces. :D


@listalltabs 

The number is always present in the container name, so the change would only affect the prefix of the container name, nothing else.

**Comment by crssi** [comment]
On 0.90beta1 this now works perfectly.

Thank you

**Comment by stoically** [comment]
It's also published as version 0.90 now, good to know it works for you!

**Comment by hackel** [comment]
I just enabled this feature, and the issue @stoically mentioned is a minor annoyance.  In my case, I just went with "%domain% - tmp", so each time I open a new tab, it gets named e.g. " - tmp3" and that name doesn't change once I actually go to a domain, thereby defeating the whole point.  This isn't an issue if I enable "Don't reopen New Tabs in Temporary Containers," though I find the privacy implications concerning.

**Comment by crssi** [comment]
@hackel 
I am going only with "%domain% #". "tmp" is just unnecessary bloat.

I can write the way I am using TC, if you are interested?

**Comment by hackel** [comment]
@crssi I see what you're saying, but how do you differentiate temporary containers from permanent containers?  Just based on whether they have a number at the end?  The default name when you convert a temporary container to permanent is the domain name, so it's hard to tell at a glance.  And as you said, without a trim, the issue is still there, just less visible.

**Comment by crssi** [comment]
@hackel 
I am also using DDG as search service, but I am using only over navigation bar.
I don't use permanent containers. I did those at the past, but I didn't like the idea and frankly I don't know why I would need a permanent containers.
I happens to me quite often that I want to open same web service but logged in as different account.

This is how I have configured TC (start with default settings):
```
  Temporary Containers; https://addons.mozilla.org/firefox/addon/temporary-containers/ (https://github.com/stoically/temporary-containers/)
    General
      Automatic Mode: Check
      [PERSONAL CHOICE] Container Name Prefix: %domain% #
      [PERSONAL CHOICE] Random Container Color: Check
      [PERSONAL CHOICE] Container Icon: fingerprint
      Container Number: Reuse available numbers
      Delete no longer needed Temporary Containers: 2 minutes after the last tab in it closes
      Click [Save]
    Isolation
      Per Domain
        Domain pattern: *
          Always open in new Temporary Containers: enabled
          Click [Add or Edit]
        Domain pattern: duckduckgo.com
          Always open in new Temporary Containers: enabled
          Click [Add or Edit]
      Global
        Mouse Clicks on Links should open new Temporary Containers
          Middle Mouse: If the clicked Link Domain does not match the active Tabs Domain (Subdomains won't get isolated)
        Click [Save]
    NOTE: CTRL+SHIFT+T = Undo closed tab(s)
```

As you see I also distinguish containers by color and not only a domain+number.

Additionally to TC, I am using [Context Plus](https://addons.mozilla.org/firefox/addon/context-plus/) to switch between context (migrating tab into another container).

I did use M-AC and Containerise, but I had a problem with those, so I have ditched them.

I am using Firefox with user.js and profile described at `https://github.com/crssi/Firefox/blob/master/user-overrides.js` which is supplement to https://github.com/ghacksuserjs/ghacks-user.js.

I understand that everyone has its own modus operandy browsing and experience the web, I am just saying how I am doing it.

If you have any questions, let me know.

Cheers

**Comment by crssi** [comment]
Oh, forgot to explain some more...

LMC (left mouse click) should net open URL in a new container, otherwise we have breakages on login pages where login is redirected to login provider and the back to visiting page.
MMC (middle mouse click) forces to open URL in a new container id the domain is different.
When clicking on a DDG search results I am using MMC.
If for any reason I do a LMC then back action will force to open DDG in a new container to avoid container infection.

**Comment by fishzle** [comment]
I have been using "%domain% #" as the container name for about 2 weeks now. Thank you - very useful.

However, previous containers that were tmp% are still visible in the menu.
Also new closed windows that are %domain%# are also still visible, after the timeout.

So, in summary, "delete container when $timeout has occurred" doesn't work well when the name is "dynamic".

Can share any data you need,
