### ISSUE TITLE
Opening tab in the already used container when same target domain

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#143]
- Temporary Containers Version: 0.90beta1 (also 0.89)
- Firefox Version: 60
- Operating System + Version: Windows 10
- Non-default Options/Preferences in Temporary Containers:
1, Isolation -> Global -> middle mouse = If the clicked Link Domain does not match the active Tabs Domain (Subdomains won't get isolated)
2. Automatic mode

### Actual behavior
Opening a more than on link by middle click opens a new tab in a **different** container for every link when a domain does match the active Tabs Domain

### Expected behavior
Opening a more than on link by middle click should open a new tab in a **same** container for every link when a domain does match the active Tabs Domain

### Steps to reproduce
Go to comment `https://github.com/ghacksuserjs/ghacks-user.js/issues/172#issuecomment-387608582` and middle-click all 4 links... every link should open in a new tab but in the same container... instead every link is opened is the new tab and new container.

**Comment by stoically** [comment]
This is expected behavior. Every new Mouse Click gets isolated on it's own and doesn't know anything about the other clicks.

**Comment by crssi** [comment]
Is it possible to make an option to force the behaviour I would like to achieve?
That is to open new link in the same container of already opened some other tab with the same domain/subdomain.

The problem is that in current case when opening more links with the same domain, they opens each in a separate container and I have to login to each one separately or I need to use WE like "Switch Container" and do a switch for each tab.

Damn, if my writing makes sense... I am sorry if I have written in non-understandable manners.
Please, if you don't understand what I mean, let me know and I will try to explain differently.

Thank you
Cheers

**Comment by stoically** [comment]
In theory it's possible. You could e.g. show a list of open tabs when a link is clicked and if you choose a container from that list open the link in that tab. And I'm sure there are plenty of others ways to handle this. I'm open for pull requests, but I'm probably not gonna implement such a feature myself. However, a similar functionality is already available under right-click on links and selecting "Open Link in new Container Tab ->" and then selecting the appropriate container.
