### ISSUE TITLE
Improvement suggestion: Back/Forward implementation

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#144]
Is it possible to internally track visited pages to some depth (let say for example 10 steps) to implement sort of back/forward capabilities?
In that case browsing experience would be really improved.
I don't mean to keep containers... those can be destroyed (if last opened tab in this container), just possibility to go URL back and/or forward.

Cheers

**Comment by stoically** [comment]
You can use the Firefox button "History" to get that behavior. Please note that the recently closed tabs only are visible if its container isn't deleted yet (so 15mins visible by default).

![image](https://user-images.githubusercontent.com/29637501/40250809-be2d92c4-5ad7-11e8-9e85-390f0e5d3554.png)
