### ISSUE TITLE
Clean deleted temporary containers reference from storage.js file as well when deleted

### ISSUE THREAD

**Issue by ba0m** [stoically/temporary-containers#145]
Thsi is especially true when the "Keep Counting" setting is on, the storage.js file will get filled with tons of hundreds of now deleted containers. It should get cleaned from it as well when the user delete them from gui..

**Comment by ba0m** [comment]
ie: ![](https://i.imgur.com/Sw9D76y.png)

**Comment by stoically** [comment]
Yep, that's a known problem and file over at MAC. I provided a PullRequest that waits to get merged https://github.com/mozilla/multi-account-containers/issues/1140
