### ISSUE TITLE
Automatic mode: open tmp container directly

### ISSUE THREAD

**Issue by Perflyst** [stoically/temporary-containers#150]
- Temporary Containers Version: 0.90
- Firefox Version: 60.0.1
- Operating System + Version: Ubuntu 16.04 (4.15.0-22)
- Non-default Options/Preferences in Temporary Containers: Advanced -> General -> Don't reopen

### Actual behavior
No difference between these two settings after new Firefox version(update to v60).

### Expected behavior
Don't reopen should directly open (with automatic mode) a new temporary container in a new tab.

### Steps to reproduce
1. Setting: Advanced -> General -> Don't reopen
2. Save settings, close settings tab
3. Open new tab

### Notes
Even if there is a certain risk, this option is required for e.g. searx. If you open a new tab with a new tmp container via the icon directly, searx works. If you search via the adress bar, however, only the searx start page is displayed.

I don't know exactly how this works in the background, because a cookie is not set. Neither does anything written into memory that could be made visible through the developer tools.
Server side?

### Debug log
I'll make one if you need it.

**Comment by stoically** [comment]
This should be fixed since Firefox version 61. Let me know if it's still a problem.
