### ISSUE TITLE
Feature Request: Custom domain rule for always no container 

### ISSUE THREAD

**Issue by Perflyst** [stoically/temporary-containers#152]
It would be nice if there will be a setting with which you could open a domain in a new tab (with Automatic Mode) in a nocontainer.

If you set `always open in new temporary: disabled` in isolation tab (what I actually thought it would work that way), nothing happens at all and everything is the same as before.

However, if you switch off the automatic mode and then explicitly enable a domain `always open in new temporary: enable` this domain is gets contained.

One would have to pay attention, however, whether advanced -> reopen or don't reopen is set.

**Why?**
Currently I can only think of my own problem. searx happens to have problems with containers. Since searx has no utm parameters (e.g. `?search=%s`), neihter it does not work with cookies or other local storage.

Sometimes it works, sometimes it doesn't. I don't know on what that depends, I'm currently trying to figure out exactly how searx processes the search query in the background and why containers (can) interfere.

**Comment by stoically** [comment]
[Containerise](https://addons.mozilla.org/firefox/addon/containerise/) has a feature to always open specific websites in "No Container" - though you'd have to use version 2.4.0 until https://github.com/kintesh/containerise/pull/49 gets merged and published or you will run into problems.

A possible solution in TC would be to allow editing of the advanced preference "Ignore requests to".

**Comment by crssi** [comment]
Glad to see you back. I was a little worried. :wink: 
Actually then only thing I miss is an option to open external induced link (like in email client) in the already present container for the same domain, but only when we have one container (but can be more than one tab) for that particular domain.

To explain better:
I do follow what is happening on github over email notifications.
Then when I open a URL on email github notification, it opens the browser in a guthub.com container.
Then I do a login.
After I click URLs on all other github mail notifications it would be nice that those would open in the same container, not to need to login on every tab again, or to migrate (using WE [Context Plus](https://addons.mozilla.org/firefox/addon/context-plus/)) the tab into the first github.com container.

Do you find this interesting?
Should I open a new "issue" for this case?

Thank you and cheers

**Comment by TheBolliwood** [comment]
Have you tried using [Firefox Multi-Account Containers](https://addons.mozilla.org/de/firefox/addon/multi-account-containers/) and assigning the tab to a manually created container? If I understood your problem, that's the way it works for me.

**Comment by Perflyst** [comment]
This would work for most cases, BUT some search sites which do POST requests have issues with containers in general not only temporary containers.

**Comment by crssi** [comment]
@TheBolliwood 
I did use M-AC, but its unreliable and config non-exportable.
And then I have used Containerise, also unreliable.

The next thing is that I don't want to have any permanent container.
Every container should be destroyed.

**Comment by stoically** [comment]
@crssi The use-case you're describing is different from what Perflyst requested, so this would belong into a new issue. However, I'm not sure how to implement this - it would probably need a "Open all new tabs in this Temporary Container" or something.

**Comment by stoically** [comment]
[v1.0beta4](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta4) allows to configure domain patterns to ignore requests in the advanced preferences.
