### ISSUE TITLE
Automatic mode, closed FF and temporary container

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#153]
- Temporary Containers Version: 0.90
- Firefox Version: 60.0.1
- Operating System + Version: Win 10
- Non-default Options/Preferences in Temporary Containers: Automatic mode
- Other installed Add-ons + Version: None, only TC (for test)

### Actual behavior
Page does not open in Temporary Container

### Expected behavior
Page should open in Temporary Container

### Steps to reproduce
Close Firefox.
Click on external link.
Firefox starts opening external link but not in TC as it should.

If more info is needed, let me know.

Cheers

**Comment by curiosity-seeker** [comment]
Yes, confirmed. I think it's a race condition. If Firefox is already open this problem does not occur.

**Comment by curiosity-seeker** [comment]
Might be related to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1457224) bug.

**Comment by crssi** [comment]
Aaaaa.... yes the uBO setting was the thing from the past memory and I have confused it with pref.

Thank you @curiosity-seeker.

It looks like we can't do anything and just humbly wait for mozilla to sort this out.
