### ISSUE TITLE
Incompatible with Windscribe, possibly other browser based VPNs?

### ISSUE THREAD

**Issue by thewan056** [stoically/temporary-containers#154]
- Temporary Containers Version: 0.90
- Firefox Version: 60.0.1
- Operating System + Version: Windows 10 1803
- Non-default Options/Preferences in Temporary Containers: 
- Other installed Add-ons + Version: Windscribe 2.3.7, Firefox Multi-Account Containers 6.0.0

### Actual behavior
Temporary containers show blank page. Sites there are supposed to open in permanent containers open in temporary containers instead and show blank pages.

### Expected behavior
Website loads normally while connected to VPN and open accordingly to assigned containers

### Steps to reproduce

1. Install Windscribe VPN Addon and connect to any server.
2. Open any website, temporary or permanent.
3. Website loads blank page

### Notes
New Firefox installation, trying out VPN options to get GDPR compliant webpages for extra privacy.

**Comment by stoically** [comment]
Did I understand you correctly that the behavior is also reproducible with just permanent containers? If so, then here is the wrong place to file the Issue. You should file here https://github.com/mozilla/multi-account-containers/issues or here https://bugzilla.mozilla.org

Feel free to comment if this only happens with TC and maybe we can figure out the underlying problem.
