### ISSUE TITLE
Ignored option: Mouse Clicks on Links should open new Temporary Containers: If the clicked Link Domain does not exactly match the active Tabs Domain (Subdomains also get isolated)

### ISSUE THREAD

**Issue by GingerPlusPlus** [stoically/temporary-containers#160]
- Temporary Containers Version: 0.90
- Firefox Version: 60.0.1 (64 bit)
- Operating System + Version: Windows 10
- Non-default Options/Preferences in Temporary Containers: Automatic mode,  Mouse Clicks on Links should open new Temporary Containers: If the clicked Link Domain does not exactly match the active Tabs Domain (Subdomains also get isolated)
- Other installed Add-ons + Version:
```
Enhancer for YouTube™	2.0.71	true	enhancerforyoutube@maximerf.addons.mozilla.org
Firefox Multi-Account Containers	6.0.0	true	@testpilot-containers
Octotree	2.4.6	true	jid1-Om7eJGwA1U8Akg@jetpack
Privacy Badger	2018.5.10	true	jid1-MnnxcxisBPnSXQ@jetpack
Tab Snooze	0.1.4	true	{10d756ed-15e2-49f2-bad0-59bb8c19296a}
Temporary Containers	0.90	true	{c607c8df-14a7-4f28-894f-29e8722976af}
Tree Style Tab	2.4.24	true	treestyletab@piro.sakura.ne.jp
Facebook Container	1.3.1	false	@contain-facebook
Mind the Time	2.2.0	false	jid0-HYNmqxA9zQGfJADREri4n2AHKSI@jetpack
Privacy Settings	0.3.4	false	jid1-CKHySAadH4nL6Q@jetpack
Snooze Tabs	1.1.0	false	snoozetabs@mozilla.com
```

### Steps to reproduce
1. Set Mouse Clicks on Links should open new Temporary Containers: If the clicked Link Domain does not exactly match the active Tabs Domain (Subdomains also get isolated),
2. Open a page in a permanent container,
3. Middle-click on a link to another domain.

### Actual behavior
Link gets opened inside permanent container.

### Expected behavior
Link should be opened in new temporary container.

[temporary-containers-log.txt](https://github.com/stoically/temporary-containers/files/2076995/temporary-containers-log.txt)

**Comment by stoically** [comment]
The website you're testing the feature on uses javascript eventhandlers on non-<a>-elements. Unfortunately there's nothing I can do about that. You can use navigation isolation instead for that page, that catches all requests. Hope that helps.
