### ISSUE TITLE
Ctrl/Cmd+Left Mouse

### ISSUE THREAD

**Issue by Sada-Mio** [stoically/temporary-containers#162]
- Temporary Containers Version: 0.90
- Firefox Version: 60.0.2
- Operating System + Version: Win10
- Non-default Options/Preferences in Temporary Containers: Isolation > Global > Ctrl/Cmd+Left Mouse: Never 
- Other installed Add-ons + Version:

### Actual behavior
Opens in tmp container

### Expected behavior
Opens in same/current container

### Notes

- RMB open link in current container -> opens in tmp
- Ctrl + LMB -> opens in tmp
- Right click open link in different container -> opens in the select container

**Comment by stoically** [comment]
The website you're testing the feature on uses javascript eventhandlers on non-<a>-elements. Unfortunately there's nothing I can do about that. You can use navigation isolation instead for that page, that catches all requests. Hope that helps.
