### ISSUE TITLE
Cookie AutoDelete in combination with containers? The sense?

### ISSUE THREAD

**Issue by Ratator** [stoically/temporary-containers#164]
Hello everybody

I harden my Firefox. As far as I could read through it is recommended to use CAD (Cookie AutoDelete) with TC (Temporary Containers).

I can not understand. TC deletes my cookies when closing a tabs / container **or not?** And FF (Firefox) even deletes my entire OWD (Offline Website Data) at the exit, which is all very desirable in terms of privacy.

For what Cookie AutoDelete in combination with containers? That makes no sense for me.

Many Thanks.

**Comment by crssi** [comment]
Yes and no.
If you have "permanent" containers with extensions like [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) or [Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/), then those containers will not be destroyed and CAD will help you to remove cookies there, but only if the pref `privacy.firstparty.isolate` is set to false.

**Comment by Ratator** [comment]
Many Thanks.

If I may ask, how trusting is the container feature in Firefox? Does it replace the procedure with multi-profiles?

**Comment by crssi** [comment]
Container feature is quite good, but not bulletproof, yet. See https://github.com/stoically/temporary-containers/issues/127#issuecomment-402049377
I don't understand second question.

**Comment by stoically** [comment]
Like @crssi already said, CAD in addition is mainly for your permanent containers, not the tmp ones.

Profiles isolates really everything  from each other (more OriginAttribute data and history/bookmarks/firefoxaccount), so it enhances privacy - but even with profiles it makes sense to use containers on top.

**Comment by crssi** [comment]
Just to add.
If you don't need cookies and if you set firefox to delete cookies on shutdown, then CAD or simmilar are not needed at all, IMHO.
I have ditched CAD in favor to sanitize cookies on shutdown.

Cheers
