### ISSUE TITLE
Feature Request: improve the "new temporary container icon" behavior when it is added to the top "toolbar"

### ISSUE THREAD

**Issue by arigit** [stoically/temporary-containers#166]
Using the "compact" firefox theme without a menu bar.

Feature Request: improve the "new temporary container icon" behavior when it is added to the top "toolbar" (dropped to the right of the tabs) by:

#1 supporting the same behavior of the "+" (New Tab) icon that will stay always close to the right edge of right-most tab, so easier to reach with the mouse. Right now, the "New Temp Container" icon can be added to the top toolbar but it will stick to the right edge of the toolbar (or to the left-most position in the toolbar) regardless of where the last opened tab is.  Using "customize toolbar" and adding a "Flexible Space" between the icon and the Window Controls moves the icon somewhat closer to the Tabs but it remains static, looks awful.

#2 support "overloading" the "+" (New Tab) icon in the same way that the Multi-Container extension does: When pressing and holding the "+" icon, a menu is displayed that allows opening of the type of container to open ("Personal", "Work", etc"), can we please have a "Temporary Container" option there.
Another nice touch would be to open a temp container when alt-clicking or shift-clicking the "+" icon.

Having #2 would perhaps relieve the need of #1 and would allow us to replace the "Add Temp Container" Icon altogether with the standard "+" icon.

**Comment by mike2212** [comment]
Just adding visuals for `#1` suggestion:

Issue: 
![image](https://user-images.githubusercontent.com/324325/51807512-9a835500-227f-11e9-93f8-eaa356dc09ae.png)

Simulated solution:
![image](https://user-images.githubusercontent.com/324325/51807517-a40cbd00-227f-11e9-9ac4-a76bf958e94f.png)

**Comment by rusty-snake** [comment]
#2 is a firefox buildin (`about:config`: `privacy.userContext.longPressBehavior`) and auto active if an AddOn use the "Container-API".

**Comment by stoically** [comment]
`#1`: This is not supported by Firefox, an Add-on can only set "tabstrip" as location, nothing more than that.

`#2`: This is also not supported by Firefox. There's only the baked in standard behavior of long-pressing which, like mentioned by @rusty-snake, is automatically activated when a container Add-on is installed.

You could open issues on the Firefox bugtracker for those requests.
