### ISSUE TITLE
Whitelist some domains to use no container in automatic mode

### ISSUE THREAD

**Issue by aeris** [stoically/temporary-containers#171]
Hi,

Currently, auto mode breaks behavior on few domains.

* Unable to use the search feature on the address bar

At least when using StartPage in POST mode
Seems POST data were suppress during tmp container redirection, and so you are redirecting to the home page (no search query)
Doesn't work even if you stick StartPage to a named container (+ always open on this container)

* Unable to use multiple containers to manage multiple accounts

In my case, at least on Github and Twitter
I manager multiple accounts (perso, pro, association…), and so I use containers to open a domain multiple time, with extension like MAC or "[Switch Container](https://addons.mozilla.org/en-US/firefox/addon/switch-container/)"
With TC, I need to stick thoses sites to a named container (currently my "Personal") to avoid to use a tmp container and to stay logged.
But in this case, I can’t use MAC or SC, the tab is always redirected to the pinned container, and so multiple tabs with the same domains but different containers is no more possible.

I try to use the "Isolation / Per domain" feature of TC to disable "Always open in new Temporary Containers" for such domain to be able to stay on the default container for such sites, but it doesn't seem to work…

Would it be possible to add a domain whitelist to disable TC for them (like AMO or Pocket in "Advanced / General" settings)?

Regards,

**Comment by jaysonwcs** [comment]
I need to use an extension for Toggl and, when I need to login the first time, I must login using the default container. And sometimes I need to check the Toggl report. When I click on the extension icon using automatic mode, it creates a new temporary container, but in this case I need to keep it on the default container.

It would be nice to have the option to whitelist, becuse this kind of issue depends on the exensions installed on each Firefox installation, and this is impossible to predict.

**Comment by stoically** [comment]
Closing in favour of #152 which requests the same, indeed nice to have, feature.
