### ISSUE TITLE
Per-domain isolation exclusion list cleared when editing

### ISSUE THREAD

**Issue by neekt** [stoically/temporary-containers#172]
Hi there,

Just a minor bug/annoyance to report here. When editing isolated domain entries, the list of excluded target domains is cleared in the edit options. This means that every time I want to add another exclusion to a particular isolated domain, I need to re-add all of the other domains that I want excluded. The other isolation options seem unaffected (i.e., work as expected).

Running version 0.90 on Firefox 61.0.1 and macOS 10.13.6 (High Sierra).

Thank you for maintaining a great extension!

**Comment by stoically** [comment]
Fix released with version 0.91

@electricessence Could you clarify how exclusion doesn't work for you? In general it should work, just editing would not load the already excluded domains, as described by OP.
