### ISSUE TITLE
Cookies in SiteSecurityServiceState.txt are not temporary

### ISSUE THREAD

**Issue by ImBehindSevenProxies** [stoically/temporary-containers#173]
hello, the supercookies in SiteSecurityServiceState.txt are not cleared, they persist between temporary containers.

i have set the file to read only for now but not sure about the negative effects for my non temporary tabs

**Comment by crssi** [comment]
Delete that file and make a folder with the exact same name to prevent some update to remove read only attribute.
There will be no side effect. At least I am using "the folder" variant for a year or two and never had a problem.

**Comment by stoically** [comment]
This is something that can't be solved from an Add-on but rather is a candidate for the [Firefox bug tracker](https://bugzilla.mozilla.org/).
