### ISSUE TITLE
TC messes up with New Tab Tools and Switch Container, makes it impossible to add new sites to permanent containers

### ISSUE THREAD

**Issue by ysalmon** [stoically/temporary-containers#174]
- Temporary Containers Version: 0.90
- Firefox Version: 61.0.1
- Operating System + Version: Kubuntu 18.04
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version: Firefox Multi-Account Containers	6.0.0, New Tab Tools	89.1,Switch Container	0.8

### Actual behavior
Websites which are not assigned to a specific ("always open in") container in Multi-Account Container opened from a new tab are opened in a new temporary container. This make sin impossible to assign new websites to containers, because there is no way to load them into a permanent container.

### Expected behavior
The website should be loaded in the current container, or absence of a container (unless it has been assigned to a specific container in M-AC).

### Steps to reproduce

- Create a new tab in no container through Firefox standard interface. Navigate to a website via the address bar or the tile view provided by New Tab Tools.
- Create a new tab in specific container through M-AC interface. Navigate to a website via the address bar or the tile view provided by New Tab Tools.

### Notes
- The first case (containerless new tab) is problematic only of TC is set to Don't reopen New Tabs in Temporary Containers but instead on navigation.
- The second case is exhibited whether TC is set to Reopen New Tabs in Temporary Containers or Don't reopen New Tabs in Temporary Containers but instead on navigation.

Opening a "new" website out of containers and switching it to a permanent container with extensions like Switch Container also do not work because TC diverts it back to a new temporary container.

This problem disappears if "Open new Temporary Containers if a Permanent Container Tab tries to load a Domain that isn't assigned to "Always open in" that container" is disabled. Maybe a whitelist / exemption list there would be useful.

[TC.log](https://github.com/stoically/temporary-containers/files/2261660/TC.log)

**Comment by stoically** [comment]
Closing this in favour of #170 

> Maybe a whitelist / exemption list there would be useful.

This could be achieved when #152 is implemented.
