### ISSUE TITLE
Latest Containerise (2.5.0) does not work well together with Temporary Containers

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#177]
Hi
After today's update of [Containerise](https://addons.mozilla.org/firefox/addon/containerise/) (ver 2.5.0) the funny things happens when using also [Temporary Containers](https://addons.mozilla.org/firefox/addon/temporary-containers/) ver (0.9.0)

Firefox 61.0.2, 64bit.
Windows 10, 64bit.

Steps to reproduce (**no.1**)
1. In Containerise define `*.github.com , GITHUB`
2. In "Temporary Containers" set Isolation->"Multi Account Containers" to **Enable**
3. Click to open any github.com link from external program (I did from my email client)

Result:
The tabs start to spawn up indefinitely,

Expected result:
Only one tab should open

Steps to reproduce (**no.2**)
1. In Containerise define `*.github.com , GITHUB`
2. In "Temporary Containers" set Isolation->"Multi Account Containers" to **Disable**
3. Click to open any github.com link from external program (I did from my email client)

Result:
Two (2) tabs opens,

Expected result:
Only one tab should open

The samo issue I have posted also here https://github.com/kintesh/containerise/issues/38, since I am not sure where the problem source actually is.
If its not in TC, then this should be treated as informational only.

**Comment by TiagoTiago** [comment]
Happens with me too (is there a "+1", or "upvote", or similar functionality on GitHub, or is commenting with "can repro" the expected behaviour?)

**Comment by TiagoTiago** [comment]
The infinite tabs thing may be related to #130 which doesn't seem to involve Containerise

**Comment by stoically** [comment]
This is due to a change in a recent containerise version. I've opened https://github.com/kintesh/containerise/pull/49 which fixes the issue.

**Comment by stoically** [comment]
Containerise 3.0.0 with the fix got published.
