### ISSUE TITLE
onMessageExternal ??

### ISSUE THREAD

**Issue by earthlng** [stoically/temporary-containers#178]
Why are you using `onMessageExternal` instead of `onMessage` [here](https://github.com/stoically/temporary-containers/blob/master/src/background/runtime.js#L15)?
`onMessageExternal` allows **any extension** to trigger `createTabInTempContainer` (and any other functions you might add there in the future). Not *that* bad but still seemingly unnecessary.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime

> - `runtime.onMessage`
> Fired when a message is sent from either an extension process or a content script.
> - `runtime.onMessageExternal`
> Fired when a message is sent from another extension.

**Comment by stoically** [comment]
There was someone who wanted the feature of opening new temporary containers with a gestures extension - that's why I added a way to send messages from other extensions. It's documented in the [wiki](https://github.com/stoically/temporary-containers/wiki/API) too.
