### ISSUE TITLE
Address bar is not focused when opening a new tab

### ISSUE THREAD

**Issue by Spakman** [stoically/temporary-containers#180]
- Temporary Containers Version: 0.90
- Firefox Version: 63.0b3
- Operating System + Version: Arch Linux (up-to-date)
- Non-default Options/Preferences in Temporary Containers: I changed a few things but I don't remember which ones are the defaults. Let me know if I can help more here though.
- Other installed Add-ons + Version:

> Firefox Multi-Account Containers	6.0.0
> uBlock Origin	1.16.20
> uMatrix	1.3.14

### Actual behavior

On opening a new tab, the address bar is not focused.

### Expected behavior

On opening a new tab, the address bar should be focused.

### Notes

I'm not sure exactly when this behaviour changed (it used to be focused on new tab), but it was "recently".

**Comment by pixelplumber** [comment]
Also seeing this behaviour in the last week or so on both windows 10 and OS X.

Disabling temporary containers restores focus to address bar on the new tab page.  

**Some things I noticed:**
After a new tab is created and the focus in not in the address bar, clicking the home button twice more reloads the new tab page and the focus is in the address bar on the third load. 

I guess the difference is that in the first open of the new tab page the default container transitions to a temporary container (loses focus), second load doesn't transition, but seems to have the same behaviour, but the third load sets focus.

**Versions:**
- temporary containers: 0.90
- multi-account containers: 6.0.0
- 64.0a1 nightly on OS X High Sierra.
- 63.0b4 dev ed on Win10

**Comment by Spakman** [comment]
A workaround for now that I've found is to set `browser.newtabpage.enabled = false` in about:config. This brings up an empty tab that isn't in a container but searching or entering a URL triggers the creation of a new container (at least with my settings).

**Comment by Perflyst** [comment]
@Spakman seems like this is a workaround for this problem but still another bug.
You can set this to false via firefox settings. Set "New Tabs" under "Home" to "Blank page".

Why this is a bug too? If you use search engines via adress bar which uses POST requests they are not working (they did before with this setting to false).

**Comment by stoically** [comment]
I can't reproduce this issue with Firefox 65. If this is still an issue it would be a candidate for the [Firefox bug tracker](https://bugzilla.mozilla.org) since TC isn't involved in the process of focusing the address bar.
