### ISSUE TITLE
Suggestion: Option to not switch the container in case of redirection

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#182]
Is it possible that you would add an option (checkbox), which would provide possibility not to switch containers when redirection happens.

I meet many cases when I need to login, where login provider is at different domain (which does not mean different domain owner) and login breaks on redirection into different container.

The same happens on payment processes, where one site redirects to, for example, paypal and then back to the original site. Such cases leads to payment breakages.

I know we can use Containerise addon or such, but in that case we need to anticipate breakage up front and its a mess to configure many to many.

Thank you and cheers

**Comment by stoically** [comment]
I like the idea, however I don't think it's possible to differentiate between normal navigation and redirects. What I'm planning to implement with #104 is a "Temporarily disable Isolation" button in the popup. However you would still need to know that isolation will take place before-hand or do the procedure (payment) twice. This actually causes me some headaches too since some redirections cause unwanted isolation but I'm still unsure how to solve that.

**Comment by crssi** [comment]
Actually I have already found a "solution" or better say desirable "modus operandy".

This is my current config in addition to default:
```
    General
      Automatic Mode: Check
      Container Name Prefix: %domain% #
      Random Container Color: Check
      Container Icon: circle
      Container Number: Reuse available numbers
      Delete no longer needed Temporary Containers: 2 minutes after the last tab in it closes
      Click [Save]
    Isolation
      Per Domain
        Domain pattern: duckduckgo.com
          Always open in new Temporary Containers: Enabled
          Mouse Clicks on Links should open new Temporary Containers [Left Mouse]: Allways
          Click [Add or Edit]
      Global
        Mouse Clicks on Links should open new Temporary Containers
          Middle Mouse: If the clicked Link Domain does not match the active Tabs Domain (Subdomains won't get isolated)
        Click [Save]
```

Idea is that left click does not invoke creation of a new container, except on a DuckDuckGo results page.
This way logon pages works as intended.
Opening a new tab obviously creates a new container.
This way the container is destroyed sooner or not so later, clearing all storages/cookies behind.
What I am missing now, that manual interaction/altering UrlBar would open in a new container, except when new destination is same domain/subdomain as current one.

If I haven't describe myself understandable or if you have any questions regarding this, please, let me know.

Thank you and cheers
This is tight together with the question https://github.com/stoically/temporary-containers/issues/205

**Comment by stoically** [comment]
Like your setup!

However, I want

> What I am missing now, that manual interaction/altering UrlBar would open in a new container, except when new destination is same domain/subdomain as current one..

too, which is accomplished by "Navigating in Tabs" "does not match", with the nice side-effect that just left-clicking is enough and isolation does the rest. However it comes with the cost of some redirect breakage.

Also Isolation with Mouse Clicks unfortunately [does not always work](https://github.com/stoically/temporary-containers/wiki/Isolation-Notes#mouse-clicks-exception).

**Comment by crssi** [comment]
Thank you :smile:, I am flattered that you like my setup.

I have tried that too and the desired functionality about altering URL in urlbar works, but left click to login where you are redirected invokes a new container, so login fails.
Open for example https://worldoftanks.eu and click login (right upper screen)... click on login should not open in a new container.

Cheers

**Comment by stoically** [comment]
Yeah, currently I set "Navigating in Tabs" temporarily to "Never" when dealing with such cases. It's cumbersome. However it's possible to add the domain to the Per Domain Isolation and add the redirected domains to the Exclude list, but that still means it breaks at least once and it's even more cumbersome. I hope to get around to at least implement something that makes this process less painful.

**Comment by crssi** [comment]
Don't over complicate and give you additional work, if there is no simple solution. :wink: 

Thank you

**Comment by crssi** [comment]
I have updated my previous post https://github.com/stoically/temporary-containers/issues/182#issuecomment-461550333.

The following lines were missing, but needed when right-click on selected URL and open should always go into a new container:
```
      Per Domain
        Domain pattern: *
          Always open in new Temporary Containers: enabled
          Click [Add or Edit]
```

Cheers

**Comment by stoically** [comment]
[v1.0beta4](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta4) allows to globally disable Isolation in the popup (circle icon) and also to globally exclude permanent containers / domain patterns. That should help with the payment/SSO stuff.
