### ISSUE TITLE
Feature Request: No colour on tab

### ISSUE THREAD

**Issue by Genius1237** [stoically/temporary-containers#183]
This is more of a feature request, hence I'm ignoring the template.

Is it possible to have an option where we are able to make the colour of the container not appear on the tab list at the top of the screen. It becomes a bit distracting and is easy for me to work without the colour appearing.

**Comment by stoically** [comment]
It's not possible for Add-ons to change the colors. However there's [something in the Wiki](https://github.com/stoically/temporary-containers/wiki/Container-Colors) that can help with changing the colors.
