### ISSUE TITLE
Feature request: one-click button to open current page in a temporary tab

### ISSUE THREAD

**Issue by mkeroppi** [stoically/temporary-containers#185]
A one-click button (either in context menu and/or tab menu) to open current page in a temporary tab.  Thanks.

**Comment by stoically** [comment]
You can enable the TC popup in the Advanced preferences (first checkbox). In the popup click the top-left menu icon, select "Actions" and there you have a "Open Tab URL in new Temporary Container". Hope that helps.

**Comment by mkeroppi** [comment]
I wanted to request a "one-click" button, which is more convenient.  This takes 4 clicks.

**Comment by stoically** [comment]
An advanced preference to show the "Actions" in the Context Menu could be possible. That would still require 2 clicks. Not sure if that's worth?

**Comment by mkeroppi** [comment]
What about putting something in the top right-click menu of a tab?

**Comment by stoically** [comment]
The Context Menu of the tab itself you mean? Sure that would work too, still needs 2 clicks though. But I guess it would be nice to have.

**Comment by mkeroppi** [comment]
Yes.  Or on the right-click menu of the page. Or both.
These features would be intuitive and nice to have.

**Comment by stoically** [comment]
[v1.0beta6](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta6) includes the possibility to change the default popup tab in the advanced preferences. So you could set it to "Actions" and with that have a fast access to the "Open Tab URL in new Temporary Container" option.

**Comment by stoically** [comment]
[v1.0beta14](https://github.com/stoically/temporary-containers/releases) now has an additional advanced preference keyboard shortcut (<kbd>Alt</kbd>+<kbd>O</kdb> by default) which can open the current tab URL in a new Temporary Container. That combined with the default popup tab hopefully covers your requirement - let me know if not.
