### ISSUE TITLE
How to turn a temporary container into a permanent one?

### ISSUE THREAD

**Issue by klint** [stoically/temporary-containers#186]
Hello
Is there a way to turn a temporary container into a permanent one? by keeping all context already set for the temporary one, of course.
Thank you

**Comment by rusty-snake** [comment]
@klint 
See [Here](https://gist.github.com/rusty-snake/99a9626ce5687c0aaa42f0b8768e63a3)

**Comment by klint** [comment]
Excellent, it works well, thank you :)
