### ISSUE TITLE
Instapaper extension needs cookie exclusions (similar to Pocket)

### ISSUE THREAD

**Issue by zswanson** [stoically/temporary-containers#193]
- Temporary Containers Version: 0.90
- Firefox Version: 63.0.3 (x64)
- Operating System + Version: Windows 10 1803
- Non-default Options/Preferences in Temporary Containers: 
Automatic Mode enabled
Global Isolation - all set to "subdomains do not get isolated"
"Don't reopen new tabs in Temporary Containers but instead on navigation" (set because the new tab flicker was driving me nuts)
Isolation - MultiAccountContainers - disabled

- Other installed Add-ons + Version:
Cisco Webex Extension	1.1.0	
Facebook Container	1.4.2	
Firefox Multi-Account Containers	6.0.0
Instapaper	1.0.4	
LastPass: Free Password Manager	4.19.0.5	
Reddit Enhancement Suite	5.12.8	
Temporary Containers	0.90	
uBlock Origin	1.17.2	

### Actual behavior
Using the instapaper extension to save a page, a new tab opens up in my Instapaper permanent container, asking me to approve the saving of the page. The note from Instapaper states: 
> Under normal circumstances, you shouldn't need to see this page. Please check your browser’s cookie settings and enable unrestricted third-party cookie access for www.instapaper.com. If you’re being sent through this page, Instapaper’s support for logged-in sites cannot function properly.

As the warning states, this prevents instapaper from getting access to content that's behind a login (ie a paywall site).

### Expected behavior
Under normal operations, without TemporaryContainers enabled, the Instaper extension does not open a new tab, does not need confirmation, and can access content from the logged in pages using your cookie settings for that session.

**Comment by stoically** [comment]
The progress for implementing a global exclusion for domain patterns will be tracked in #152

**Comment by cr1za** [comment]
I have the same issue. I configured to have *instapaper.com* to open in a Multi-Account container, so the page I want to save opens in a new tab, but then I have to confirm the save as described above.
