### ISSUE TITLE
Feature request: remove containers on browser window close + let to choose timeout value

### ISSUE THREAD

**Issue by alexgpot** [stoically/temporary-containers#194]
- Temporary Containers Version: 0.90
- Firefox Version: 60
- Operating System + Version:
- Non-default Options/Preferences in Temporary Containers:
Delete no longer needed Temporary Containers (After the last tab in it closes);
Notification when Temporary Containers are deleted (checked)
- Other installed Add-ons + Version:

### Actual behavior
I can see containers that are no longer used are being removed in ~10 seconds.
When I close and reopen Firefox, notification says some containers have been removed.

### Expected behavior
It would be nice to control the timeout with a possibility to set it to 0, so a container is removed instantly.
It would be nice to have containers removed before browser window is closed.

**Comment by stoically** [comment]
It's not possible to remove the TCs on browser close since there's no such hook in Firefox that allows to do that.

The timeout of 10seconds is needed to give Firefox some time to handle tab closing. In my testing it would lead to bugs otherwise where containers aren't removed at all.

**Comment by Kraxys** [comment]
> 
> 
> It's not possible to remove the TCs on browser close since there's no such hook in Firefox that allows to do that.
> 
So, were it possible to remove the TCs at least on browser's start?

**Comment by stoically** [comment]
[15 seconds after startup](https://github.com/stoically/temporary-containers/blob/229c3dbbcead05bcc2aec5a0e0a9505f83705f31/src/background/runtime.js#L131-L138) a TC cleanup takes place, which means removing all containers that don't have open tabs anymore (with a 5 seconds pause after each container).
