### ISSUE TITLE
just some minor Wiki stuff

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [stoically/temporary-containers#196]
Hi @stoically  - we're going reference your extension (and wiki) directly in the our ghacks user.js :+1:  Hope everything is well :) I was just perusing the wiki

Sorry for not using the issues template.

re: https://github.com/stoically/temporary-containers/wiki/Browser-fingerprinting

> [Tor Browser] Though, it doesn't support containers yet due to the fact it's still on Firefox Version 52 ESR, but that will change with the upcoming Firefox 60 ESR, and with that Tor Browser should get container support too.

Because TB always opens in PB mode, containers are not available (although they (Arthur and GK) are talking about changing this, it won't be anytime soon, certainly not in TBv8* / ESR60* based builds). You could also remove the old ESR52 info.

> make you *easier fingerprintable* (in a couple of places)

Not sure if English is your native language, but "makes you more easily fingerprintable" is the way to say this

-- 
debatable stuff - up to you

Tying in IP with FP'ing:
- "In practice, most of the time it's already enough to fingerprint you with your "Internet Address" (IP).."
-  "[Tor browser] and also anonymize (to some extent) your IP. "

To me IP is tracking, not FP'ing. When mitigating FP'ing etc, it is always assumed that the real IP is masked. It's an assumption. When anonymizing yourself (either lowering or randomly raising entropy), what's the point in wearing a mask, changing your gait, disguising your voice, and changing your clothes, when you keep wearing a name tag with your real name on it. :)

If it were me, I would make that clear in the first sentence, that revealing your IP is a tracking mechanism, and effectively negates any FP'ing mitigation.

> "[Tor browser] and also anonymize (to some extent) your IP. 

How does it anonymize your IP "to some extent" - it does. That's the whole point. It's trustless. It uses the Tor protocol. Network traffic is anonymized (i.e I do not mean the user reveals ID'ing behavior or information by logging in to services, or via their actions, comments = OpSec).

---

Anyway .. truck on :kiss:

**Comment by stoically** [comment]
> we're going reference your extension (and wiki) directly in the our ghacks user.js

Great, thanks! :)

> Because TB always opens in PB mode

I didn't know that, good to know. Changed the wiki accordingly.

> Not sure if English is your native language, but

It's not and I changed the sentence.

> To me IP is tracking, not FP'ing

I'd say that tracking and FP'ing basically have the same underlying goal. Why else would you FP someone if not to track him?

> How does it anonymize your IP "to some extent"

Tor is still vulnerable to attacks, such as the traffic correlation / timing attack.

**Comment by Thorin-Oakenpants** [comment]
Hey @stoically 

I don't want to get in a long discussion about it, but fundamentally when dealing with (browser) FP'ing, this term refers to gaining browser characteristics ONLY, as a science, to get enough entropy to **uniquely** identify someone

> I'd say that tracking and FP'ing basically have the same underlying goal

Of course. But they are not the same. Tracking is a larger set and includes FP'ing 

Tracking (within a service, as well as across the web) includes at least the following: IP addresses, cookies & local persistent data techniques, using third party logins for services, using logins in the first place, analyzing mouse movements and writing styles and typing characteristics, .. and lots more.

In other words FP is a subset of tracking.

from the wiki: 
> Browser fingerprinting is the process of accumulating data about your browser with the goal to make you uniquely recognizable, or fingerprintable, without the need of any storage-related data

IMO it's really "...without the need for **any other tracking or ID'ing mechanism**, such as local persistent storage, IP addresses)"

When Tor Browser, or Mozilla in the Tor Uplift look at a FP'ing issue, not one starts talking about IP and needing to use VPNs, etc. No-one starts talking about needing to clear cookies or IDB. Just like no-one starts talking about OpSec and how to navigate the web anonymously. FP'ing is a science within it's own right.

Anyway: I'm not writing an award winning essay here, so it's all a bit muddled and off the top of my head, so I'm probably not explaining it well. 

it's your wiki :) Peace out :kiss:

**Comment by stoically** [comment]
Hey @Thorin-Oakenpants 

appreciate the feedback. I've changed the Wiki accordingly to differentiate between FP and Tracking, thanks!

Cheers

**Comment by Thorin-Oakenpants** [comment]
No worries. I was doing some reading just before ... and it was described as such

Tracking is linking the fingerprints (the author was talking about FP'ing and how it has two parts, one of which was stability of the FP)

So is essence, every single site could give you an ID, but it takes someone behind the scenes to collect it all, and join the dots = tracking. Tracking is the goal, FP'ing and cookies etc are the means.

Hope that makes sense.
