### ISSUE TITLE
how to exclude/whitelist a domain?

### ISSUE THREAD

**Issue by atomGit** [stoically/temporary-containers#197]
TC .9
FF 64

i'm trying to allow cookies permanently for a domain (searx.me) so i can save my settings - is this possible?

TC is set to auto to open everything in a tmp container

i'm using a slightly relaxed version of the ghacks config - FPI is off, remember history is custom, cookies are not cleared on exit

when i click the toolbar icon -> save - i'm expecting the domain to be whitelisted, but apparently it isn't - i'm not seeing any different behavior

then there's the per-domain list which asks for a domain pattern, so i stuck searx.me in there and clicked add - again, the domain is still opened in a tmp container 

i don't understand the difference between the pop-up form and the per-domain one in settings, or why when i add a domain from the pup-up, it doesn't appear in the per-domain settings

to add to the confusion, there's 2 domain patterns in the settings, the 2nd to exclude - i tried adding the domain there and again there's no difference

1) is it possible to load a domain in a tmp container while keeping it's cookie across sessions and, if not...

2) is it possible to whitelist/exclude a domain so it never opens in a tmp container while auto tmp is enabled?

3) why is Multi-Account Containers suggested when AFAIK it's feature set seems to be already built-in to v64? is this add-on needed to achieve my objective?

**Comment by rusty-snake** [comment]
* Install Multi-Account Containers (MAC)
  * Go to the TC Settings
  * Disable Auto mode
  * Create a new container in MAC (Name: searx.me)
  * Open searx.me in the searx.me container.
  * Go to the MAC PopUp and click "Always open in searx.me"
  * Go to the TC Settings
  * Enable Auto mode
  * Go to Isolation -> Multi-Account Containers  ( In the TC Settings)
  * choose Enable

**Comment by atomGit** [comment]
thanks for the tip rusty - appreciated

while this works, it's a bit of a convoluted process that, imo, needs to be simplified (if possible given limitations of the current add-on api)

this process should be as easy as clicking the TC icon to open the pop-up and assigning the current domain to a perm container

i also still don't understand why, if for instance, you enable 'allow in permanent containers' from the pop-up, the domain never shows up in the isolation -> per-domain settings in the options tab, or why if i re-open the domain it's not listed in either place - seems like the setting is not being stored?

**Comment by rusty-snake** [comment]
It works for me, did you click save in the PopUp?

**Comment by stoically** [comment]
Yeah, adding domains to MAC permanent containers is something that needs work but also depends on MAC implementing an API. Progress is tracked in #170
