### ISSUE TITLE
Tab order breaks when using isolation

### ISSUE THREAD

**Issue by kilotaras** [stoically/temporary-containers#202]
- Temporary Containers Version: 0.90
- Firefox Version: 64.0
- Operating System + Version: OS X 10.13.6
- Non-default Options/Preferences in Temporary Containers: Isolation -> Global -> clicks should open in new container
- Other installed Add-ons + Version: None (clear profile)

### Actual behavior

Tabs order is HN fronpage, HN comments, link

### Expected behavior

Tabs order is HN frontpage, link, HN comments

### Steps to reproduce

1. Go to https://news.ycombinator.com/ (or any other aggregator)
2. cmd-Click on first link AND first "XXX comments"
3. tab with page from link (new container) is opened to the right of parent, and then comment page is opened between them.

### Notes

This completely breaks tree style tabs, which shows correct order of tabs but processes click in order they are shown in top bar.

[log.txt](https://github.com/stoically/temporary-containers/files/2734421/log.txt)

**Comment by stoically** [comment]
The default behavior of Ctrl/Cmd+Click (and Middlemouse click) is to open a new tab directly to the right of the currently open tab. That's what TC does too. It basically takes the index (position) of the tab it closes and creates the new tab at that index. So the actual behavior "frontpage, comments, links" is expected. You can test this without TC too.

Could you further explain how this "breaks tree style tabs", maybe adding a screenshot?

**Comment by kilotaras** [comment]
More info about TST issue was/is https://github.com/piroor/treestyletab/issues/2119. It was fixed there.

It looks like multi-account containers have the same issue https://github.com/mozilla/multi-account-containers/issues/1029 and can probably be only fixed when (if ever) browser API for changing tab cookieStoreId is added.

**Comment by stoically** [comment]
Oh well, I just tested the tab opening myself and you're right, the expected order would be "frontpage, link, comments" since that's the default in Firefox until something "resets" the order. Related: https://github.com/mozilla/multi-account-containers/issues/1030

This is unfortunately not an easy fix since it would mean to keep track of tab interactions and set the position dynamically based on it.

**Comment by stoically** [comment]
Fixed in version 0.102.
