### ISSUE TITLE
What does mean "Navigating in Tabs should open new Temporary Containers" setting?

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#205]
Does the `Navigating in Tabs should open new Temporary Containers` setting means entering/changing URL in URLBAR (user interaction) or it means changing URL with the mouse click event or it means both?

It puzzles me, since I would expect this setting would invoke only when user interacts with URLBAR and not when mouse event is triggered.

Cheers

**Comment by stoically** [comment]
It means any navigation inside a tab, that is manually entering an URL into the address bar, mouse clicking on links or redirects invoked from the page itself. Hope that helps.

**Comment by crssi** [comment]
Thank you.
Is it possible to split "entering URL into address bar" and "mouse clicking on links or redirects" into two different options?

Cheers

**Comment by stoically** [comment]
Unfortunately that's not possible since both address bar / mouse clicks navigation look the same to the underlying API.

**Comment by crssi** [comment]
Understood. :cry: 
Thank you @stoically
Cheers
