### ISSUE TITLE
Add Exclude Target/Link Domains to address bar icon options

### ISSUE THREAD

**Issue by grenzor** [stoically/temporary-containers#206]
Currently when editing/creating per domain settings from the address bar icon the Exclude Target/Link Domains option is missing. Please add this so this option can be configured like just like the other per domain options.

**Comment by stoically** [comment]
[v1.0beta4](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta4) allows to configure global and per domain excluded target domains.
