### ISSUE TITLE
Start Firefox in a temporary container

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/temporary-containers#207]
To start Firefox, I go through this process each time:

1. Launch Firefox.
2. Wait for all extensions to load.  I can tell when they are loaded by the Temporary Containers toolbar button changing to its custom icon.
3. Press the Temporary Containers toolbar button.
4. Close the tab that's to the immediate left of the new temporary container.

Ideally, I would like to avoid steps 3 and 4 by having Temporary Containers start Firefox in a new temporary container.

Can you do this?

**Comment by rusty-snake** [comment]
TC has an `Instead of creating a new Tab replace the currently active Tab` option, (TC Settings -> Advanced -> General) may it helps you. Depending on your workflow.

**Comment by Gitoffthelawn** [comment]
@rusty-snake Thank you for your recommendation.  I tried it out, and I'm not seeing a difference.  Thus, 2 questions:

1. What is that option supposed to do?
2. How does that option solve my original request?

Thanks again!

**Comment by rusty-snake** [comment]
@Gitoffthelawn 

1. Have you click the Save-Button at the bottom?
2. Not at all, but if it's enough for you, it's faster than if it still have something to implement.
 For example if you have a worklfow where you almost never open a new tab

**Comment by stoically** [comment]
Automatic Mode automatically reopens default container tabs into temporary container ones on browser start too - or changes the TC icon to have the A-badge if the "Don't reopen" advanced preference for Automatic Mode is active. Could you use the Automatic Mode or are you looking for a distinct option for your use-case?

> 1. What is that option supposed to do?

Normally if you use Isolation new Tabs are opened if isolation takes place, with that option enabled the current Tab is replaced instead.

**Comment by Gitoffthelawn** [comment]
@rusty-snake 

1. Yes :)
2. Thank you.  My workflow does involve frequently opening new tabs.

**Comment by Gitoffthelawn** [comment]
@stoically Thanks for your reply.

> Could you use the Automatic Mode or are you looking for a distinct option for your use-case?

Yes, I am using Automatic Mode.  Works great for me.  The only exception is that when I start FF, I start it with a single blank tab (I don't use session restore).  That blank tab opens as a global tab (not a container), but I would like it to be a TC container.  That way, I can get right to work in a temporary container using that initial blank tab instead of having to go through the 4 steps outlined in my initial post.

**Comment by crssi** [comment]
@Gitoffthelawn does the initial blank tab, when used (entering address into urlbar), auto transform to a container?

**Comment by Gitoffthelawn** [comment]
@crssi wrote:
> @Gitoffthelawn does the initial blank tab, when used (entering address into urlbar), auto transform to a container?

Oh my.  I'm feel embarrassed.  It does.

All this time, I see that it's not in a container, so I just avoid it and then close it.

Well, I'll close *this* now.  Thank you, and please pardon me for not seeing that.

P.S. I will add that it would be better if it just started as a container, but auto-transforming into one is an acceptable workaround.

**Comment by crssi** [comment]
Welcome my friend. :smile: 
I think that `about:blank` cannot be opened in a container (see https://github.com/stoically/temporary-containers/issues/146#issuecomment-461752760), but Automatic Mode will close that tab and open a new one, with a desired destination, in a container anyway... sot it should be fine.

You can also check "my approach" at https://github.com/stoically/temporary-containers/issues/182#issuecomment-461550333 :wink:, if you find it helpful. 

Cheers

**Comment by Gitoffthelawn** [comment]
I've had a little time to play with it, and I want to make sure I'm understanding what I think I'm understanding.  :wink: 

@stoically and @crssi What I want it for `about:blank` to be opened in a new container, but according to crssi's useful link, it doesn't sound possible (at least for right now).

So what I'm doing now (thanks to crssi's suggestion) is to type a URL into the urlbar for `about:blank` and have it auto-convert to a new container.  What I'm wondering is: *Does this (essentially) do the same thing as manually opening a new container, and opening the URL from that container?*

**Comment by crssi** [comment]
It appears so from what I am seeing.
But to be 100% sure, we would need @stoically to answer.

**Comment by stoically** [comment]
@Gitoffthelawn 
> Does this (essentially) do the same thing as manually opening a new container, and opening the URL from that container?

Yes. With Automatic Mode enabled requests in the Default Container are blocked and reopened in a TC - since that's what's happening with links opened from an external program too.

**Comment by Gitoffthelawn** [comment]
@stoically 

Thank you!

This is still a feature request, but according to the link that @crssi kindly provided, it currently is not possible.

Would like to keep this as an open feature request, or close it as "not possible"?

**Comment by stoically** [comment]
I'd say it's enough to track it in #146 since the feature is implemented, just doesn't work with `about:blank` tabs yet.

**Comment by Gitoffthelawn** [comment]
@stoically 

Sounds great, thanks!
