### ISSUE TITLE
Cannot move tab to existing container when isolation is active

### ISSUE THREAD

**Issue by vbrandl** [stoically/temporary-containers#208]
- Temporary Containers Version: 0.91
- Firefox Version: 65.0.1
- Operating System + Version: Arch Linux
- Non-default Options/Preferences in Temporary Containers:
   * Open new Temporary Containers if a Permanent Container Tab tries to load a Domain that isn't assigned to "Always open in" that container
   * Notifications
- Other installed Add-ons + Version:
   * Decentraleyes	2.0.9
   * Firefox Multi-Account Containers	6.1.0
   * HackBar	2.1.2
   * KeePassXC-Browser	1.3.2
   * Old Reddit Redirect	1.1.2
   * Startpage.com — Datenschutz-Suchmaschine	1.1.3
   * Temporary Containers	0.91
   * Tridactyl	1.14.8
   * uBlock Origin	1.18.4

### Actual behavior

When trying to move a tab to an existing container, while the URL is not assigned to the container, the tab will be moved to a new temporary container

### Expected behavior

The tab should be moved to the specified container.

### Steps to reproduce

(Assuming example.com is not assigned to any container yet):

1. Navigate to example.com in the default container
1. Right-click on the tab and move to e.g. your work container
1. example.com will be opened in a new temporary container

**Comment by crssi** [comment]
But, isn't that expect-able when `Open new Temporary Containers if a Permanent Container Tab tries to load a Domain that isn't assigned to "Always open in" that container` is used?

**Comment by vbrandl** [comment]
I agree, but I would argue, that explicitly moving containers should be an exception to the rule

**Comment by crssi** [comment]
I am not sure that TC can/could detect such actions to be then able to react as you wish.
You could try my approach described [here](https://github.com/stoically/temporary-containers/issues/182#issuecomment-461550333).
Additionally to upper, I am using [Context Plus](https://addons.mozilla.org/firefox/addon/context-plus/) for migration from one container to another.
I am not using M-AC, due to some limitations and non-consistency.

It works for me very well.

Cheers

**Comment by stoically** [comment]
@vbrandl Like mentioned by @crssi it's not possible for TC to detect the container change since there are no such hooks or events to tap into. So it's unfortunately not possible to implement.
