### ISSUE TITLE
Convert a temporary tab to permanent container renames existing permanent container

### ISSUE THREAD

**Issue by ipwnponies** [stoically/temporary-containers#210]
I have a site that's already associated with a permanent container. I wanted to move it to a separate container. I used action to "Convert to Temporary Container", then "Convert Temporary Container to Permanent". 

- Temporary Containers Version: 0.91
- Firefox Version: 65.0
- Operating System + Version: OSX 10.14.2 (Mojave)
- Non-default Options/Preferences in Temporary Containers: `Automatic mode` is enabled
- Other installed Add-ons + Version:

```
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
HTTPS Everywhere	2019.1.31	true	https-everywhere@eff.org
KeePassXC-Browser	1.3.2	true	keepassxc-browser@keepassxc.org
Privacy Badger	2019.1.30	true	jid1-MnnxcxisBPnSXQ@jetpack
React Developer Tools	3.6.0	true	@react-devtools
Redux DevTools	2.17.1	true	extension@redux.devtools
Simple Tab Groups	3.3.7.1	true	simple-tab-groups@drive4ik
Stylus	1.5.2	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
Tab Session Manager	4.5.2	true	Tab-Session-Manager@sienori
Temporary Containers	0.91	true	{c607c8df-14a7-4f28-894f-29e8722976af}
Tridactyl	1.14.7	true	tridactyl.vim@cmcaine.co.uk
uBlock Origin	1.18.4	true	uBlock0@raymondhill.net
Violentmonkey	2.10.1	true	{aecec67f-0d10-4fa7-b7c7-609a2db280cf}
ADB Helper	0.12.1	false	adbhelper@mozilla.org
Todoist: To-Do list and Task Manager	6.31	false	support@todoist.com
```
### Actual behavior
Tab was convert to temporary container. Then tab was converted to a permanent container, named with the site's domain (i.e. container named "www.google.com").

It didn't create a new container, it renamed the original permanent container and kept all the settings, including the sites that are already associated with it.

### Expected behavior
Converting a temporary tab into a permanent container should always create a new permanent container. It should also remove the tab from the former container it used to belong to.

### Steps to reproduce

1. Go to google.com, create a permanent container, and always google.com in the container.
1. Name the container "Googly moogly"
1. Go to github.com, make it also always load in "Googly moogly" container.
2. Open new temporary tab, go to github.com, which will redirect to permanent container.
3. Use temporary container actions to convert to temporary container.
4. Use temporary container action to convert temporary container to a new permanent container.
1. Check container settings. There will only be one permanent container, "www.github.com".
1. Confirm that both "github.com" and "google.com" are now in the "www.github.com" permanent container.

### Notes
..

**Comment by stoically** [comment]
Converting containers is expected to not create new containers but just rename the existing container (and put them on or remove them from the list of Temporary Containers). The reasoning behind this is that converting should keep the website data / container settings, something that's not possible if the website would be opened in a new container.

In your case a possible way to do it would be to use the actions to "Open Tab URL in new Temporary Container" and after that convert that TC to a permanent one by also using the actions. Hope that helps.

**Comment by ipwnponies** [comment]
Ah I understand now, I misunderstood the meaning of "Convert to Temporary/Permanent Container" to mean "convert current tab to ...". I think putting this button next to "Open Tab URL in temporary container" was my point of confusion: one button acts on the current tab/url; the other acts on the container.

Maybe changing the wording to "Open Tab URL in temporary container" + "Convert Googly moogly container to Temporary container" to make the distinction clearer. Or adding a UI separator element to put the buttons into separate sections. Just my opinion on UX, hope this feedback helps.
