### ISSUE TITLE
Twitter redirector leaves blank tab

### ISSUE THREAD

**Issue by todduk** [stoically/temporary-containers#215]
- Temporary Containers Version: **0.91**
### Actual behavior
Clicking a redirection/shortened link will open the new tab in either the specified site container or a new temporary container. An example of a link from twitter; https://t.co/Asx7a4tsfD

### Expected behavior
The site opens in the expected container, but the redirect page remains open rather than being closed.
Meaning if I open the above link from the URL bar or by clicking the link on twitter, a twitter redirect tab opens for the redirector url, which is blank, and another tab opens for the directed url, in this case youtube, which opens in my youtube container.

### Steps to reproduce
1. Click or paste this url; https://t.co/Asx7a4tsfD

**Comment by todduk** [comment]
I was able to fix this by checking the 'Creating new Temporary Containers in case of Isolation and Left Mouse Clicks' in the advanced tab. I've removed some details above.

**Comment by stoically** [comment]
TC Version 0.102 now has a dedicated preference for that. Advanced > Automatically close left-over redirector tabs after 2 seconds.
