### ISSUE TITLE
Automatic deploy

### ISSUE THREAD

**Issue by Snussmumric** [stoically/temporary-containers#216]
Hello. We want to use your add-on in our company. How could we automatically deploy settings in case of several PC users? Maybe common folder for add-on or registry settings?

**Comment by stoically** [comment]
Hi! One way to have preferences automatically populated would be by copying the Add-on storage to its appropriate location in the [profile folder](http://kb.mozillazine.org/Profile_folder). Inside the profile it should be in `browser-extension-data/{c607c8df-14a7-4f28-894f-29e8722976af}/storage.js` (that's the TC id).

Note however that with Firefox 66 the Add-on storage is [automatically migrated to IndexedDB](https://blog.mozilla.org/addons/2019/02/15/extensions-in-firefox-66/). After that migration the storage is located at `storage/default/moz-extension+++<Internal UUID>^userContextId=4294967295/idb/`. The `Internal UUID` is different with every unique installation of an Add-on (`about:debugging` has that information) and so copying just the storage is impractical. In this case copying the complete profile would be a possibility (or keep relying on the `storage.js` migration).

**Comment by Snussmumric** [comment]
Well, i mean i could install plugin by copying extension to C:\Program Files (x86)\Mozilla Firefox\browser\extensions folder. I thought i could make something similar with storage.js

**Comment by stoically** [comment]
AFAIK extension storage is only used from the profile folder and not from the program files. So the only way I know of is copying into the correct profile folder.

**Comment by rusty-snake** [comment]
@Snussmumric maybe [this](https://addons.mozilla.org/en-US/firefox/addon/enterprise-policy-generator/) can be usefull for you.

**Comment by Snussmumric** [comment]
@stoically thank you for support

@rusty-snake we already configure Firefox via config file. Is it possible to change plugin  settings with this tool? I thought it’s just for browser.

**Comment by rusty-snake** [comment]
@Snussmumric Ok if have testet: you can use it for install AddOn, but not for configure AddOns. I think the only way to configure AddOns in FF-Quantum is a Script (e.g. Bash, PowerShell, Python, …) that copy files to the user profile and then start FF.

**Comment by stoically** [comment]
Closing as this seems to be resolved.

**Comment by stoically** [comment]
@Snussmumric FYI, configuration through managed is now supported since [v1.4beta1](https://github.com/stoically/temporary-containers/releases). Usage is [documented in the wiki](https://github.com/stoically/temporary-containers/wiki/Managed-Storage).
