### ISSUE TITLE
add a setting to hide temporary containers in context menu?

### ISSUE THREAD

**Issue by Lockdis** [stoically/temporary-containers#219]
despite of having set a short time (15mins) before deleting temporary containers and set the setting to off ![2019-03-10_05-34](https://user-images.githubusercontent.com/45907176/54081077-b9551c80-42fe-11e9-899d-f5c89d1ec05c.png) it's pretty annoying to have so many of items in the contextual menu, the setting is not working? thanks

![2019-03-10_05-26](https://user-images.githubusercontent.com/45907176/54081029-a4c45480-42fd-11e9-86ca-af8ffc291121.png)

**Comment by stoically** [comment]
The "Context Menu" advanced preference only hides the "Open Link in new Temporary Container" button. The "Open Link in New Container Tab >" context menu you referrering to is native in Firefox and so TC can't hide containers there - this would need support from the [WebExtensions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API) and thus a [Firefox Bugzilla](https://bugzilla.mozilla.org/) ticket.
