### ISSUE TITLE
This add-on is not available on your platform - on Linux and Windows with Firefox 65

### ISSUE THREAD

**Issue by MurzNN** [stoically/temporary-containers#226]
I try to install extension from https://addons.mozilla.org/en-US/android/addon/temporary-containers/ webpage, but got the error:

> This add-on is not available on your platform

I try this with Firefox 65.0.1 (64-bit) on Ubuntu Linux 18.04 and Windows 10, both shows same error.

**Comment by stoically** [comment]
TC is not available on android. Try https://addons.mozilla.org/addon/temporary-containers/ instead.

**Comment by MurzNN** [comment]
Ow, sorry, I googled wrong url of extension :)
