### ISSUE TITLE
Isolation rules based on container name

### ISSUE THREAD

**Issue by leromarinvit** [stoically/temporary-containers#230]
I'd find it useful to be able to set isolation rules based on (permanent) container names. This would make it easy to allow sites using authentication with multiple cross-domain redirects to work.

Currenly, you can add a domain to "Exclude Target/Link Domains", but if that domain redirects to another one, the original rule no longer matches and the default rules will apply. One could create an explicit rule for that domain, but this is cumbersome, and the rule would also match if the authentication request didn't come from the domain matched in the first rule

Example:

foo.com: I can create a rule that matches this domain
login uses bar.com: I could exclude that domain in the first rule
redirect to baz.com: the first rule doesn't match, I'd have to create a rule for bar.com, which would also apply if the original request came from xyz.com

What I'm looking for:

foo.com: I assign that to a permanent container "foo" using some other extension, and create a rule matching this container
bar.com: is loaded in the same container because of this rule
baz.com: still in the same container - but in a temporary container if the original request came from xyz.com

This is somewhat related to #104, but not quite the same because it would provide more flexibility.

**Comment by stoically** [comment]
Per Container Isolation rules would indeed be more powerful than just excluding containers from isolation. I like the idea.

**Comment by stoically** [comment]
Maybe it would also be nice to just add a container dropdown/multiselect to the Per Domain Isolation page. One could then just add a `*` regexp rule for a specific container to have the "exclude container" functionality - and also have the ability to create more specific rules for specific containers.

**Comment by stoically** [comment]
[v1.0beta4](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta4) allows to globally exclude permanent containers and target domains from Isolation (in the preferences and popup), that should help with your use-case. Let me know if you need even more fine-grained configurations.
