### ISSUE TITLE
Local storage for about:newtab in temporary containers fill up the hard drive

### ISSUE THREAD

**Issue by maxnordlund** [stoically/temporary-containers#232]
- Temporary Containers Version: 0.91
- Firefox Version: 66.0.1
- Operating System + Version: Mac OS X 10.14.3
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version: MAC and Switch Container

I'm not sure if this is really an issue with temporary containers, but the constant creation of new containers certainly exaggerates the effect.

I noticed that my hard drive suddenly was out of space, and after some digging around I found `~/Library/Application\ Support/Firefox/Profiles/*.default/storage/default`. AFAIK Firefox stores all pages localstorage here, with a `^userContextId=` suffix to differentiate containers.

The problem is that `about:newtab` creates/request the use of localstorage, which Firefox happily gives it, allocating 5Mb per the standard. If you create say a couple of thousand of temporary containers you can see how quickly this eats up your hard drive. (Note that the page doesn't need to use all 5Mb of space, Firefox allocates all of it upfront, which I'm guessing is to make it easier to handle failure upfront and not some random time later.)

For now I run this periodically to keep things under control:

```sh
set -l storage_dir ~/Library/Application\ Support/Firefox/Profiles/*.default/storage/default

find $storage_dir -name "*^userContextId=????" | xargs rm -r
find $storage_dir -name "about+newtab^userContextId=*" | xargs rm -r
```

---

The solution I believe is to destroy any and all storage created by a temporary container when it is garbage collected. But again, that might need new APIs in Firefox.

**Comment by stoically** [comment]
TC only uses one call to [`contextualIdentities.remove`](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/remove) to remove containers. That *should* take care of removing everything from disk too. Someone reported something similar on [Bugzilla 1474608](https://bugzilla.mozilla.org/show_bug.cgi?id=1474608). Maybe you want to chip in and let them know that it's also affecting about:newtab (and maybe that your hard drive is really not happy with the current situation in combination with TC).

Also, I'd advise to be careful with your shell workaround: starting with Firefox 66 Add-on storage is also stored in that location in the form of `moz-extension+++<Internal UUID>^userContextId=4294967295` - and it'll also affect permanent container storage or storage from currently open TCs.

**Comment by maxnordlund** [comment]
I see, I'll vote on that issue then and try to dig up some more info to get it fixed.

> Also, I'd advise to be careful with your shell workaround: starting with Firefox 66 Add-on storage is also stored in that location in the form of moz-extension+++<Internal UUID>^userContextId=4294967295 - and it'll also affect permanent container storage or storage from currently open TCs.

Thanks for the heads up, I didn't know about that change. It's a hack for sure, but should be safe since I use `????` glob and not `*`. I know it messes with the temporary containers, but as I see it they are going to be thrown away anyway. A better solution would be to look for modification time, and only delete files older that say 24 hours.

I'm going to change it to:
```
find $storage_dir -name "http*^userContextId=????" | xargs rm -r
```
Which won't match and extensions (or `file://`, but I can live with that).

Thanks for the info and the addon ❤️

**Comment by stoically** [comment]
> only delete files older that say 24 hours.

That would also affect permanent containers (MAC), if you browse in them and storage is changed. Currently your permanent containers are not deleted because their userContextId is <1000 and thus not matches your glob - though if you now create a permanent container, that would be affected too.

Related issues: #211 #127
