### ISSUE TITLE
[Cosmetic - Non-Critical] Container name not complete when navigating IP instead of non-IP URL

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#236]
- Temporary Containers Version: 0.93
- Firefox Version: 66.0.2
- Operating System + Version: Windows 10
- Non-default Options/Preferences in Temporary Containers:
Automatic Mode: Enabled
Container Name Prefix: %domain% #
Advanced -> General -> Automatic Mode: Don't reopen New Tabs in Temporary Containers but instead on navigation.
- Other installed Add-ons + Version: None
Go to FF options -> Home and set "New Windows and Tabs" to "Blank Page"

### Actual behavior
Open new tab.
Navigate to some lP address, for example 192.168.1.1
Container name is set as **1.1** as prefix with a sequence number as suffix.

### Expected behavior
Open new tab.
Navigate to some lP address, for example 192.168.1.1
Container name should be set as **192.168.1.1** as prefix with a sequence number as suffix.

Cheers

**Comment by stoically** [comment]
Nice catch. That's because the IP is passed into [psl.parse](https://github.com/wrangr/psl#pslparsedomain). I guess this needs an additional IP regexp check.

**Comment by stoically** [comment]
Published 0.94 with the fix.

**Comment by crssi** [comment]
Thank you :heart: , works like a charm.

Cheers
