### ISSUE TITLE
other languages

### ISSUE THREAD

**Issue by bogachenko** [stoically/temporary-containers#237]
Are you planning to translate the extension into **other** languages? I am from Russia, I want to see Russian. Other non-English-speaking people also want to see their languages ​​here, I think.

I can help translate, but only into Russian.

![2bb6dc0db7452e](https://user-images.githubusercontent.com/8535285/55419568-936d1180-5564-11e9-89c3-d4a68f6e7031.png)

**Comment by stoically** [comment]
Thanks for the offer. I'll look into adding support for translations.

**Comment by unbranched** [comment]
I join the queue for future translations.
