### ISSUE TITLE
Middle click keeps creating new containers for domains with "per-domain isolation"

### ISSUE THREAD

**Issue by anewuser** [stoically/temporary-containers#239]
I have the automatic mode turned off and the "no-history" option enabled for all temporary containers.  

After the last update, middle-clicking on links on the same domain set to `Per-domain isolation` keeps creating new containers. That behavior is set to `Global`, and `Global` is set to `Never`.

Temporary Containers 0.94
Firefox 66

**Comment by stoically** [comment]
Thanks for the report. Fixed in version 0.95.
