### ISSUE TITLE
"Open Link in a New Container Tab" context menu question

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#241]
Hi @stoically 

`Automatic mode = enabled/checked`

Open any page.
Right click on some link.
Select `Open Link in a New Container Tab` and then `No Container`.

Actual behavior: The new tab will open, but will not be contained in a new container.
Desired behavior: The new tab would open in a new container.

Workaround:
Create a per domain isolation rule `Domain Pattern = *` with `Always open in new Temporary Containers = Enabled`.

Is there a way to force a new container for such case, other than the explained workaround?

Thank you and cheers

**Comment by stoically** [comment]
Hey. It's expected behavior that the `Open Link in New Container Tab` context menu does what it's supposed to do. If you want to override that, you indeed have to use isolation. Either with your workaround or by configuring the `Navigating in Tabs` isolation (global or per domain).
