### ISSUE TITLE
Feature request: moveable "add to temporary container" button

### ISSUE THREAD

**Issue by supermamie** [stoically/temporary-containers#242]
- Temporary Containers Version: 0.95
- Firefox Version: 65.0.1
- Other installed Add-ons + Version: Tab Center Reborn 0.9.0

I installed Tab Center Reborn to have my tabs vertically.
I then disabled the default Firefox tab menu to avoid having tabs twice.

The problem I have is that I lost the button to open a new temporary container because this button is with the tabs.

Is it possible to add a new button that is moveable, so I'll be able to have it even with tabs hidden.

Thanks a lot.

**Comment by stoically** [comment]
Firefox supports that natively: right-click on the TC button, select "Customize..." and then move it where-ever you want. Hope that helps.

**Comment by supermamie** [comment]
I feel dumb, I reactivated the bar and indeed, the button is already movable.

Sorry for the useless ticket, and thanks for this great app.

**Comment by stoically** [comment]
No worries. Glad you like it!
