### ISSUE TITLE
Chromium support

### ISSUE THREAD

**Issue by vandreytrindade** [stoically/temporary-containers#243]
Hi! Is there any plan to make this extension also supported on Chromium based browsers?

**Comment by stoically** [comment]
The [containers feature](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities) is unique to Firefox and not available in Chromium, so it's not possible to support Chromium unless they implement that feature (which I highly doubt they'll do).
