### ISSUE TITLE
remove temporary container icon in urlbar

### ISSUE THREAD

**Issue by streetwolf** [stoically/temporary-containers#244]
- Temporary Containers Version:
- Firefox Version:
- Operating System + Version:
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce

1. ..
2. ..
3. ..

### Notes
..

**Comment by stoically** [comment]
Right-click on the icon, select "Customize..." and move the icon where-ever you want.

**Comment by streetwolf** [comment]
I mean the icon in the URL bar that in my case says TMP1 and a circle. I don't really need this as the tab is also underlined in the same color.

**Comment by stoically** [comment]
That can only be done with an `userChrome.css`.

**Comment by streetwolf** [comment]
Can you give me the code please?

_____
Gary


________________________________

**Comment by stoically** [comment]
```css
[id="userContext-icons"] {
  display: none;
}
```

might do the trick.

**Comment by streetwolf** [comment]
Yes that did the trick.  Thanks very much.

_____
Gary


________________________________
