### ISSUE TITLE
Do not create new containers if the current tab is already in a temporary container

### ISSUE THREAD

**Issue by anewuser** [stoically/temporary-containers#245]
I use Temporary Containers along Cookie AutoDelete and don't mind if all the domains in my isolation list use the same temporary container while browsing from one to another.

**Comment by stoically** [comment]
Could you provide preferences, steps to reproduce and expected/actual results? By default and with Automatic Mode TC doesn't open new TCs when already in a TC.

**Comment by anewuser** [comment]
With a clean Firefox profile:

1. Use the `Isolation` tab to set `example.org` and `*.iana.org` to always open in temporary containers with separate rules
2. Open https://example.org/
3. Click on the link to https://www.iana.org/domains/reserved or type it manually into the address bar. A new temporary container will be opened

Expected result: I want `*.iana.org` to be isolated only if the current container isn't temporary.

**Comment by stoically** [comment]
I see. Isolation should do exactly that; but I guess it'd be possible to add another checkbox to the `Always open in` preference which allows that behavior. A workaround is to use a regexp which includes both domains.

**Comment by stoically** [comment]
[v1.0beta14](https://github.com/stoically/temporary-containers/releases) now has an additional "Disable in Temporary Containers" preference for "Always open in".
