### ISSUE TITLE
A 'how do I do this?" question for you.

### ISSUE THREAD

**Issue by streetwolf** [stoically/temporary-containers#246]
- Temporary Containers Version:
- Firefox Version:
- Operating System + Version:
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce

1. ..
2. ..
3. ..

### Notes
..

**Comment by stoically** [comment]
Interesting question. The answer is:
