### ISSUE TITLE
How do I do this?

### ISSUE THREAD

**Issue by streetwolf** [stoically/temporary-containers#247]
I only want www.example.com to open in a temp container.  I do not want a temp container opened up when I click on a bookmark for example which opens up in the same tab.  How do I accomplish this?

**Comment by streetwolf** [comment]
Looks like my question is the same one as #245.

**Comment by stoically** [comment]
For clarification: You have a Per Domain Isolation `Always openin` for `www.example.com` configured and if you're already on `www.example.com` in a tab and click a bookmark leading to `www.example.com/foo` that should not open a new temporary container?

**Comment by streetwolf** [comment]
The site in question is www.softexia.com<http://www.softexia.com>.  I use a temporary container because for some reason this site in Firefox does not reload new content from it’s servers unless I do a manual refresh.  Containers, due to not reading from the cache, overcomes this behavior.  Btw… This site refreshes as needed automatically on MS Edge.

So I go to www.softexia.com<http://www.softexia.com> and the site displays new content if there is any.  Now if I click on my cnn.com bookmark icon CNN appears in the same tab with the orange stripe under the tab which I am assuming means a temp container.  I don’t need any other site to be in a container.
_____
Gary


________________________________

**Comment by anewuser** [comment]
What you want is to whitelist some of your bookmarks for them to never open in temporary containers.  There's already a feature request for that: https://github.com/stoically/temporary-containers/issues/152 (check the other extensions suggested in the comments),

You can also just hold the <kbd>Ctrl</kbd> key while clicking on your bookmarks. That makes them open in a new normal tab.

**Comment by stoically** [comment]
Yeah, @anewuser is correct, that's currently not supported and requested in #152.

Another workaround than holding the <kbd>Ctrl</kbd> key would be to configure `browser.tabs.loadBookmarksInTabs` to `true` in `about:config` - that would load bookmarks always in new tabs, even when left-clicking.
