### ISSUE TITLE
Question: Service Workers cache isolation

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#253]
@stoically, just a question...

Is Service Workers (SW) cache isolated by TC and when container is destroyed is the SW cache also cleared/destroyed?

Thank you upfront

Cheers

**Comment by stoically** [comment]
Hey. Yep, you can check `about:serviceworkers` and see that they have `^userContextId=` attached. Which means they are inside the container, and are also removed when the container is removed.

**Comment by crssi** [comment]
That is great. Thank you again for clarification and very fast reply.

And THANK YOU for TC. :heart: 

Cherrs
