### ISSUE TITLE
Per domain redirect issue with kobo

### ISSUE THREAD

**Issue by AeliusSaionji** [stoically/temporary-containers#254]
Ultimate goal: reduce use of things that can't be exported or backed up. MAC, as far as I know, can't be backed up. So I hope to start using TC rules more often rather than relying on permanent containers.

I'm trying to create a per-domain rule that will allow me to navigate kobo's multidomain website without switching containers- which obviously logs me out.

I do have automatic mode enabled.

`*.kobo.com` exclude domain `*.kobobooks.com`
`*.kobobooks.com` exclude domain `*.kobo.com`

Expected behavior: don't create a new temporary container when trying to access a page on a different domain.

Headache inducing actual behavior: excluded domains are completely ignored and a new container is always generated.

**Comment by AeliusSaionji** [comment]
Since `kobobooks.com` is already passed through in a redirect back to `kobo.com`, I can't even add it to a permanent container anyway.

**Comment by stoically** [comment]
To debug please open the Developer Tools (Ctrl+Shift+I) `Network` Tab, select `HTML`, check `Persist Logs`  and then do the navigation that triggers the TC isolation. Of interest are only the requests with `Cause document`. Are only requests involved whose `Domain` matches the patterns accordingly?

**Comment by AeliusSaionji** [comment]
The developer tool is not tracking across containers, so I can't get any debug information.

**Comment by stoically** [comment]
Ah, true, the canceled request isn't visible in the `Network` tab.

In this case you'd need to take a look at the [debug output](https://github.com/stoically/temporary-containers/wiki/Debug-Log). You can `Filter output` by `marked request as canceled` to see the revelant request urls.

**Comment by AeliusSaionji** [comment]
OK, problem 1
The sign-in page doesn't properly redirect to `kobo.com`. Instead, a new tab/container is opened for that.

```
"[cancelRequest] marked request as canceled" {"requestId":"11331","url":"https://www.kobo.com/","originUrl":"https://authorize.kobo.com/us/en/signin/signin/kobo?workflowId=6e4c8118-4f54-489a-8541-af2d0617c9ea","method":"POST","type":"main_frame","timeStamp":1557269725785,"frameId":0,"parentFrameId":-1,"proxyInfo":null,"ip":null,"frameAncestors":[],"tabId":142} log.js:16:7
"[cancelRequest] marked request as canceled" {"requestId":"11331","url":"https://www.kobo.com/","originUrl":"https://authorize.kobo.com/us/en/signin/signin/kobo?workflowId=6e4c8118-4f54-489a-8541-af2d0617c9ea","method":"POST","type":"main_frame","timeStamp":1557269725785,"frameId":0,"parentFrameId":-1,"proxyInfo":null,"ip":null,"frameAncestors":[],"tabId":142} log.js:16:7
```

---

Problem 2

```
"[cancelRequest] marked request as canceled" {"requestId":"12153","url":"https://secure.kobobooks.com/profile?wslang=en-US","originUrl":"https://www.kobo.com/","method":"GET","type":"main_frame","timeStamp":1557270041601,"frameId":0,"parentFrameId":-1,"proxyInfo":null,"ip":null,"frameAncestors":[],"tabId":145}
```

**Comment by AeliusSaionji** [comment]
Globally I have it set such that subdomains don't get isolated, so I'm not even certain why problem 1 is happening.

![image](https://user-images.githubusercontent.com/4342746/57338491-8ad7a000-70fb-11e9-8f69-2faecab1626f.png)

**Comment by stoically** [comment]
Thanks for looking into it. Unfortunately I can't spot what's wrong here with the given information. Could you provide the full debug logs? That'd be helpful!
