### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by kriom** [stoically/temporary-containers#255]
Hi,

Just to know.
For you, does it seems possible to make this extension work for the Android version of Firefox ?

Best regards

**Comment by stoically** [comment]
Hey,

as mentioned in the [limitations](https://github.com/stoically/temporary-containers#limitations), Firefox on Android [doesn't support managing tabs as containers](https://bugzilla.mozilla.org/show_bug.cgi?id=1398097) yet. If that is resolved, I'll be happy to look into Android support.

**Comment by kriom** [comment]
Thank you very much for this answer ! 👍
