### ISSUE TITLE
Excluded domain empty list

### ISSUE THREAD

**Issue by Modged** [stoically/temporary-containers#256]
Hello I have an issue I can't exclude a domain every try return an empty list.
I tried to switch tab and click "save" but it doesn't keep my excluded domain "No Domains excluded"
Am I doing something wrong ?

**Comment by stoically** [comment]
It might be a bit confusing, but excluding of domains is not global, but per domain. So you need to add a Per Domain pattern and then you're able to add excluded domains to that pattern.

E.g.
``` 
Per Domain Pattern: example.com
Excluded Domain Pattern: www.iana.org
```

meaning, that if you're on `example.com` you can navigate to `www.iana.org` and that triggers no isolation. Global exclusion is a work in progress - you can follow #104 regarding that.

Hope that helps, and sorry for the confusion.
