### ISSUE TITLE
Home Button for Firefox Top Sites/Default Home page behavior from TempContainer

### ISSUE THREAD

**Issue by slaingod** [stoically/temporary-containers#257]
This may or may not already be possible, hard to tell from the plethora of options and wording, but I am looking for a specific behavior where I always want the Top Sites/Firefox Home (Default) page to be excluded. In particular, if I am in a temporary container and hit the home button or shortcut, I don't want to be in a container when that Firefox Home (Default) page loads, which is not the current behavior I am seeing. 

This isn't strictly speaking a 'new tab', just that I want to hit home on a tab and not have to care which kind of tab I am in before continuing.

Thanks in advance, and apologies if this is already possible and I am simply not seeing how to do it.

**Comment by stoically** [comment]
Excluding domains completely isn't yet possible, the issue regarding the implementation for that is #104. However, you could define a Per Domain Pattern of `*` and put the desired domains in the `Exclude Domains` part for that pattern, although this only works for if you're already on a fully loaded website, not for new navigations (from e.g. a new tab) to excluded domains.

But if I understand you correctly, you want that if you're already in a temporary container and click the home button, it'll push you out of the container and into the default container?

**Comment by slaingod** [comment]
Correct! Wasn't sure if the Firefox Home (Default) Top Sites etc page was special though, so wanted to include that aspect of it.

**Comment by stoically** [comment]
Pushed to `master` and available in the next [beta](https://github.com/stoically/temporary-containers/releases): When `Automatic Mode` with Advanced preference `Don't reopen` is active, clicks on the home button will reopen the home tab in the default container. Due to Firefox API limitations it's not possible to explicitly open `about:home`, but it needs to open `about:newtab` instead. Hope that helps, let me know if not.

**Comment by stoically** [comment]
Now available in [v1.0beta15](https://github.com/stoically/temporary-containers/releases).

**Comment by slaingod** [comment]
SO works great with Automatic mode, but I don't use the extension in Automatic mode (I typically only use the extension for a few specific sites). Is there a way to make it work in non-Automatic too? 

I guess I could try and invert my use of the extension and try and mark all of the sites I don't want the extension to isolate, but that is a lot more sites, not sure how that will work out.

I may take a look at the commit you did for this and see if it can be tweaked for my needs and make a PR if so:
[Commit](https://github.com/stoically/temporary-containers/commit/ab6e9ae7fe16171df06cf4a476b3e415ee4b6958)

But looking at your commit history, you activity on this extension is awesome! I have an extension I built for work for dev process integration between github, jenkins and a tracking site, so know how finicky these things can be. Thanks so much for your dedication!

**Comment by stoically** [comment]
Thanks for the kind words.

The problem with reopening in the default container when clicking the home button if Automatic Mode is disabled, is that it might unexpectedly break isolation. With Automatic Mode a new navigation opens in a temporary container again - but without, you start navigating in the default container, even though you were previously in a temporary container. So yeah, I'd rather not implement that by default - but I'd be open to make it an optional advanced preference. Currently no time to work on TC, but if you want to look into a PR I can certainly get it merged.

**Comment by slaingod** [comment]
Yea, I expected it might lead to YAS, yet another setting, lol. 

So yea, just tried it out, and moving the code up above the 'if not automatic active, return' at https://github.com/stoically/temporary-containers/commit/ab6e9ae7fe16171df06cf4a476b3e415ee4b6958#diff-bced2cf2909d018c01966975ccefc833R158
and getting rid of the automatic mode check in that commit does what I was hoping for. 

That said, you raise a good point about needing to very containment, but not sure exactly how the containment might break with this. It does seem to open top sites tab(new tab) in the temp container, and then close and reopen it in default container with that tweak, so are you saying the reopened default container new tab might be contaminated with the other container somehow still?

**Comment by stoically** [comment]
With that change you probably get an endless loop of closing / opening new tabs with Automatic Mode enabled; and it'll show the "Automatic Mode Don't reopen"-badge on the toolbar icon.

What I was trying to say was, let's assume we implement the change: an user opens a TC (without automatic mode) and starts navigating in it. Visiting websites in that TC is now contained. The user now clicks the home button and doesn't pay attention to the fact that it gets reopened in the default container. The following navigations now happen in the default container and aren't contained anymore in the TC the user initially opened. And that's what I'd like to prevent.

**Comment by slaingod** [comment]
Yea, I hear you. For me, mentally speaking when I get back 'home' I have the sense that I would be in the default container, but I can see how someone else might expect something different/have a different mental model and it would need to be explicitly called out/configurable.

**Comment by slaingod** [comment]
(Also, I am not seeing an issue with endless loop, just FYI, but there may very well be some configuration of the settings that does.)
