### ISSUE TITLE
Want to select some containers not to be deleted

### ISSUE THREAD

**Issue by Yuugao** [stoically/temporary-containers#258]
It is desirable to be able to achieve selective retention of the container. The current option only allows the container to be deleted when the last tab is closed (immediately, 2 minutes later, 5 minutes later, 15 minutes later), but some containers are useful and hopefully retained manually.

I know that the temporary container can be converted to a permanent container in the popup, but after changing to a permanent container, I need to re-enter the account and password to complete the login. (This is a page opened from an external application and cannot be set to a permanent container in advance.)

**Comment by stoically** [comment]
Converting to a permanent container is indeed the way to go for your use-case. Internally the container is basically just renamed and the icon gets changed, then the tab is reloaded so the change gets visible. Storage/Cookies aren't touched in any way. So if you get logged out from the site, the reason might be another Add-on that cleans the data when you "leave" the site (when the Tab is reloaded) - do you maybe have such Add-ons active?
