### ISSUE TITLE
Temporary Containers button is missing in Firefox Toolbar panel

### ISSUE THREAD

**Issue by MurzNN** [stoically/temporary-containers#260]
- Temporary Containers Version: 0.97
- Firefox Version: 67.0 (also prevoius 66.*, 65.* versions)
- Operating System + Version: Ubuntu Linux 19.04
- Non-default Options/Preferences in Temporary Containers: fresh install with default settings

### Actual behavior
After installing extension, as I understand, the Create new temporary tab must be added, but nothing new added to toolbar, also I can't see Temporary Containers button in Customize buttons list. Other extension items like right-click menu "Open link in new temporary container tab" show normally.

### Expected behavior
Where can be the problem? How can I add "New temporary tab" to panel?

**Comment by MurzNN** [comment]
Installed extensions:
```
Application Menu
Auto Tab Discard
Containers Sync
Containers theme
Disable JavaScript
Display #Anchors
Filter Drop-Down Menu
Firefox Multi-Account Containers
Form History Control (II)
Foxy Gestures
Image Picka
Instagram Video Controls
JSON Lite
Location Switcher
Open bookmark in Container Tab menu item
Open image in a new tab
Plasma Integration
Popup window
RESTClient
Switch Container Plus
Table2Clipboard
TabSubmit Basic
Temporary Containers
Tree Style Tab
TST Colored Tabs
VkOpt
```

**Comment by stoically** [comment]
Maybe you're hitting https://github.com/stoically/temporary-containers/issues/259#issuecomment-494059384 as well?

**Comment by MurzNN** [comment]
Yes, thanks! Can't find this issue before creating this, sorry...
