### ISSUE TITLE
Container Colors on Wiki needs update

### ISSUE THREAD

**Issue by sbr61** [stoically/temporary-containers#265]
### Version
- Temporary Containers Version: 0.98
- Firefox Version: 67.0
- Operating System + Version: Windows 10 Pro 1809

### Problem

The description in the Wiki how to change the temporary containers color is no longer valid.

### Solution

The method to be used now is:

    .identity-color-red {
      --identity-tab-color: #000000 !important; /* tab bar */
      --identity-icon-color: #000000 !important; /* address bar */
    }
in `userChrome.css` and

    [data-identity-color="red"] {
      --identity-icon-color: #000000 !important; /* multi-account containers menu */
    }
    
    .identity-color-red {
      --identity-icon-color: #000000 !important; /* multi-account containers preferences */
    }
in `userContent.css`.

### References
See the Bugzilla issue [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1479433) and the Mozilla changeset [here](https://hg.mozilla.org/mozilla-central/rev/45e56d6e9dd0).

**Comment by stoically** [comment]
Thanks, Wiki updated!
