### ISSUE TITLE
Is there any way to prevent the creation of a container from hijacking what I'm typing in the url bar?

### ISSUE THREAD

**Issue by ilikenwf** [stoically/temporary-containers#267]
If not, can we replicate the entire urlbar within the addon, so that we can have a seamless transition without the jerkiness and occasional cutting off of whatever we type in the address bar?

Ex: I do a ctrl+t, type a url or partial - sometimes what I type is lost or truncated once the addon spawns a container in the new tab. Likewise, sometimes ctrl+click opens two tabs of the same link, like with google search results.

**Comment by stoically** [comment]
You can configure the `Automatic Mode` to `Don't reopen new tabs` in the `Advanced` preferences. Unfortunately there's no other solution to this, since an Add-on can't get access to the content of the address bar. Hope this helps.

**Comment by ilikenwf** [comment]
In some testing I found this to be mostly specific to google with ctrl+click, but found that using a userscript to remove google result link tracking fixed the doubling up of tabs.
