### ISSUE TITLE
Please add option to suppress Reopen Confirm tab

### ISSUE THREAD

**Issue by sbr61** [stoically/temporary-containers#268]
### Configuration
- Temporary Containers Version: 0.98
- Firefox Version: 67.0
- Operating System + Version: Windows 10 Pro 1809
- Non-default Options/Preferences in Temporary Containers:
    Automatic mode
- Other installed Add-ons + Version:
    Tree Style Tab, version 3.0.17
- Firefox preferences:
    General/Startup/Restore previous session enabled

### Actual behavior
I had a problem where the TC _Reopen Confirm_ page that gives the choice between a temporary container and a multi-account container caused a complete loss of the tab tree structure of some hundred tabs that I had created with the Tree Style Tab extension. The problem occurred after startup of Firefox at the first activation of a (discarded) tab in a temporary container for an URL that I had added with _Always open in this container_ before I exited Firefox (see the [TST issue here](https://github.com/piroor/treestyletab/issues/2305)).

The reload on the tab activation caused the tab to be replaced with the _Reopen Confirm_ tab, and the selection I then made caused another tab replacement. I am not sure whether you can do something about that problem, but if you try to reproduce, note that it took a rather long time (more than 10 seconds) until the selection on the _Reopen Confirm_ page was processed. So maybe the problem is related to time and only occurs when really a lot of tabs are open.

Together with TST, the _Reopen Confirm_ tab is a really dangerous operation. As it is only documented on the [Automatic Mode](https://github.com/stoically/temporary-containers/wiki/Automatic-Mode) page in the wiki, I tried to suppress the _Reopen Confirm_ tab by switching off _Automatic Mode_, but without success.

### Expected behavior
It would be very helpful if you could provide an option to suppress the _Reopen Confirm_ dialog. That is, when suppressed, a new tab for an URL assigned to always open in a multi-account container should go to the multi-account container, but a reload of a tab with the same URL in a temporary container should stay in that temporary container. This would allow to prevent that dangerous situation together with TST.

**Comment by stoically** [comment]
The "Reopen Confirm page" is part of MAC, not TC. Automatic Mode just reopens the Confirm page again, so you can choose a TC instead of the Default Container.

> but if you try to reproduce, note that it took a rather long time

That's a known and already fixed bug (https://github.com/mozilla/multi-account-containers/pull/1387), but not yet released. Workaround: Don't click the bold text on the button.

> a new tab for an URL assigned to always open in a multi-account container should go to the multi-account container, but a reload of a tab with the same URL in a temporary container should stay in that temporary container

It's MAC deciding whether to show the Reopen Confirm page or not. So unfortunately there's nothing on TCs end that can be done about it. But it looks like TSTs author is already working on a fix in https://github.com/piroor/treestyletab/issues/2305.
