### ISSUE TITLE
"Reopen in container" opens a temporary container anyway

### ISSUE THREAD

**Issue by coaxial** [stoically/temporary-containers#269]
I am probably missing something, but can't figure out what: when navigating to a website with automatic mode enabled, it will load in a temporary container. That's fine. But then I want to reload that tab in a particular container rather than a temporary one, so I right click on the tab and select Reopen in container > My container. This however triggers yet another reload and the tab is eventually open in a new temporary container, rather than My container. Because of this, I can't manually assign a website to always open in its own permanent container so I don't lose login state.

Why is this happening? What am I doing wrong?

**Comment by crssi** [comment]
If you want to "fix" some domains to specific container, you can try [Containerise](https://addons.mozilla.org/firefox/addon/containerise/). It works very good together with TC.

If you want "migrate" a tab from one container to another, you can peek into [Switch Container Plus](https://addons.mozilla.org/en-US/firefox/addon/switch-container-plus/) or [Context Plus](https://addons.mozilla.org/firefox/addon/context-plus/).

In case you are interested into my TC approach, you can take a look mine [configuration](https://raw.githubusercontent.com/crssi/Firefox/master/temporary_containers_preferences.json).
Left mouse click doesn't leave container, so cross domains logins does not break and your friend is middle mouse click, which always open into a new container, when domain or subdomain is different. Maybe in the future I will switch left and middle mouse click actions.

Cheers

**Comment by stoically** [comment]
> Why is this happening? What am I doing wrong?

You probably have Navigation Isolation active, which results in the described behavior. There's unfortunately no way to detect the "Reopen" action and respect it in TC in this case.

You could either switch to a relaxed configuration as described by @crssi or use the TC popup (you can activate it in the advanced preferences at the top), click the menu icon top left, go to actions, and choose "convert to permanent container".

**Comment by stoically** [comment]
@coaxial Just realized that I was wrong - if you have just Global or Per Domain Isolation enabled, reopening in permanent containers should work just fine. Do you by chance also have Multi-Account Containers Isolation enabled? If that's the case, you might want to check out https://github.com/stoically/temporary-containers/issues/170#issuecomment-506464287.

**Comment by stoically** [comment]
If you don't have MAC Isolation enabled, that would be a bug. Let me know and I'll reopen the issue and a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) would also very helpful in that case.

**Comment by dvandersluis** [comment]
I am running into this as well, I do not have Multi-Account Containers Isolation enabled, but "Reopen in Container" is opening a new tab and leaving the old one.

[temporarycontainer.log](https://github.com/stoically/temporary-containers/files/3356741/temporarycontainer.log)

**Comment by stoically** [comment]
@dvandersluis That's expected Firefox behavior, Reopen actually opens a new tab instead of replacing the current one - that's probably because the original tab would lose it's history. The issue described here is about reopening in permanent container not working, but getting intercepted by TC isolation.

**Comment by stoically** [comment]
Though, if you're looking for replacing when reopening, then you might want to check out my [Switch Container Plus](https://addons.mozilla.org/firefox/addon/switch-container-plus/).

**Comment by dvandersluis** [comment]
Maybe I misunderstood, but before installing TC, the Reopen context menu item would close the old tab, and now it doesn't anymore. My apologies if this is unrelated. (For what it's worth, I was already using Switch Container, but I tried your Switch Container Plus instead and the behaviour is the same).

**Comment by stoically** [comment]
Yeah, seems unrelated, not sure why that behavior changed for you - and the log shows also no unusual activity from TC.

**Comment by stoically** [comment]
FWIW, the reopen context menu is Firefox native and there are no Add-on APIs to change it's behavior in any way.

**Comment by dvandersluis** [comment]
Thanks @stoically, I'm not sure what's going on then. Sorry again for the noise in this issue!
