### ISSUE TITLE
Choose a default pane for pop-up

### ISSUE THREAD

**Issue by foxdan** [stoically/temporary-containers#270]
As I'm using TC in Automatic Mode it would be nice if there was an option for the default pane to show up when opening the TC popup as the only option I'm after here mostly is `Hamburger -> Actions -> Convert to Permanent Container`

**Comment by stoically** [comment]
[v1.0beta6](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta6) includes the possibility to change the default popup tab in the advanced preferences.
