### ISSUE TITLE
Exclude colors from random container color

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/temporary-containers#271]
FF v67.0.4 64-bit, TC v0.101

Before updating to TC v0.101, [Containers Theme extension](https://addons.mozilla.org/firefox/addon/containers-theme/) always showed a color for each temporary container.

Now, with TC v0.101, the Containers Theme extension *usually* shows a color, but sometimes uses the color gray.

Perhaps you can fix this?

Thanks!

**Comment by stoically** [comment]
This would need a feature to exclude colors when random container colors is selected. Firefox 67 added the "toolbar" color, which is black or gray, depending on your theme.

**Comment by foxdan** [comment]
👍 this is a feature I'd like for a different reason.

To use different random colours from those I use for permanent containers to still easily distinguish amongst them.

Happy to have a look at this if PRs are welcome.

**Comment by Gitoffthelawn** [comment]
@stoically 
Interesting.  Thanks.  I never encountered gray until today, even though FF 67 has been out for a while.  I wonder why.

Is the fence icon a new FF 67 icon as well?  It seems now to be in the rotation when Random Container Icons is enabled.  Does it have any special meaning, or is it just another random icon in this case?

**Comment by stoically** [comment]
@foxdan Sure, PRs are more than welcome. I'd imagine to use a [multiple selection](https://semantic-ui.com/modules/dropdown.html#multiple-selection) and either hide it until random container color is selected, or make it a separate option in the advanced tab. Sorry for the code mess, good luck and let me know if I can be of help.

@Gitoffthelawn The fence is just another icon, also added with Firefox 67. Version 0.101 made the new color and icon available in TC.

**Comment by stoically** [comment]
@foxdan Just FYI, the latest added feature (#104) required a multiple selection too and I found it a bit tricky to fill it with values programmatically and get the selected values afterwards. That's what worked for me: [options.html](https://github.com/stoically/temporary-containers/blob/0fa8e9f3a9bf7ec2d300d7444731624ea3638d97/src/ui/options.html#L187-L190), [options.js](https://github.com/stoically/temporary-containers/blob/0fa8e9f3a9bf7ec2d300d7444731624ea3638d97/src/ui/options.js#L116-L119), [shared.js](https://github.com/stoically/temporary-containers/blob/0fa8e9f3a9bf7ec2d300d7444731624ea3638d97/src/ui/shared.js#L97-L102)

**Comment by stoically** [comment]
[v1.0beta14](https://github.com/stoically/temporary-containers/releases) allows excluding of colors and icons when random is selected.

@foxdan Sorry about inviting you to PR and then doing massive refactorings.

**Comment by Gitoffthelawn** [comment]
@stoically Thanks for your hard work!  Could it be possible to add colors (and maybe even icons)?

**Comment by stoically** [comment]
That's not supported by the Firefox API, so I can't help with that. Related: https://github.com/mozilla/multi-account-containers/issues/391
