### ISSUE TITLE
Ability to configure popup icon first page

### ISSUE THREAD

**Issue by grenzor** [stoically/temporary-containers#276]
In the new beta it always opens the Global Isolation page which I rarely use (by the way TC doesn't save Global Isolation settings when you configure in the popup, I can open new issue if you want). I usually use Per-Domain isolation tab/page the most. Is it possible to make the first opening page of the popup configurable?

**Comment by stoically** [comment]
Yeah, I'll add an option to configure the default popup tab. When doing that, I'll migrate existing users with enabled popup to Per Domain Isolation as default. Tracking work in #270.

**Comment by grenzor** [comment]
Thanks.

Do you want me to open a new issue about this?
>by the way TC doesn't save Global Isolation settings when you configure in the popup

**Comment by stoically** [comment]
I've picked that up in https://github.com/stoically/temporary-containers/issues/277#issuecomment-506658844.
