### ISSUE TITLE
Some beta suggestions

### ISSUE THREAD

**Issue by grenzor** [stoically/temporary-containers#278]
Just some suggestions I had from using the new beta version for a little bit

- A lot of dropdown menus in the settings (in Per domain isolation, Advanced general, etc.) are all collapsed by default. Could they be expanded by default or at least remember user selections if they expand particular dropdown headers? There's quite a few headers I'd like to keep expanded for good but right now going away or closing the settings page will make all the dropdown headers go back to collapsed again.

- In my opinion there's too much space between domains in the Per-Domain patterns isolation settings page which makes scrolling slightly longer if there are a lot of domains. Is it possible to make the edit/delete icons smaller and the gaps between the domains smaller?

Will keep testing the beta version and see if I could perhaps suggest anything else. Thanks for the great work @stoically

**Comment by stoically** [comment]
Thanks for checking out the beta!

> all collapsed by default

Would you be OK with an advanced configuration that expands *all* options by default? Currently only dropdowns with non-default preferences are expanded.

> there's too much space between domains in the Per-Domain

I agree, wasn't too happy with that either. I'll look into making it a bit smaller. While I'm at it, would you like to see a filter by text box for that list?

**Comment by grenzor** [comment]
>Would you be OK with an advanced configuration that expands all options by default? Currently only dropdowns with non-default preferences are expanded.

Sure, that works for me.

>While I'm at it, would you like to see a filter by text box for that list?

That's a good idea, it would be very useful.

**Comment by stoically** [comment]
[v1.0beta6](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta6) includes the suggestions as well as the possibility to change the default popup tab and filter the per domain list. I've decided to make Per Domain Isolation the default tab. Let me know if you want to see anything else changed. Thanks!

**Comment by grenzor** [comment]
It looks like the new Expand all option doesn't stick. Once you refresh/reopen the settings page the options become collapsed again (even though the option is ticked)

**Comment by stoically** [comment]
Could you export the preferences and check if `expandPreferences: true` is in there?

**Comment by grenzor** [comment]
`expandPreferences: true` is there

**Comment by stoically** [comment]
Thanks for letting me know! Fixed in the next beta.

**Comment by grenzor** [comment]
Some suggestions below about v1.0. Posting here just to keep it in a single issue rather than creating multiple issues for each suggestion, hope you don't mind @stoically.

- In the older versions in the per-domain isolation tab it used to show all the isolation rules for the domain pattern when hovering over the pattern which was nice. Is it possible to bring that back?
- In the popup, when you click the domain filter textbox the popup jump up so domain patterns below can't be seen without scrolling down again. It should probably keep its position or jump down instead.

**Comment by stoically** [comment]
Thanks for the follow-up. I'll look into getting those suggestions (back) in.
