### ISSUE TITLE
Error while loading preferences.

### ISSUE THREAD

**Issue by YaagoRo** [stoically/temporary-containers#279]
- Temporary Containers Version: 0.103
- Firefox Version: Fennec 66.0.5
- Operating System + Version: Fire OS 4.5.5.3
- Non-default Options/Preferences in Temporary Containers: none
- Other installed Add-ons + Version: Cookie AutoDelete 3.0.1, uBlock Origin 1.18.4, uMatrix 1.3.16, Youtube Audio 0.0.2.2 (disabled)

### Actual behavior
Error while trying to access the options page.  
Restarting the browser didn't work.  
Hitting "Reset storage" gives the output "No confirmation".

### Expected behavior
Loading the preferences.

### Steps to reproduce
1. Hit the 'Options' button on the addon-page in about:addon

### Notes
This is the error message:

Error: Type error for parameter permissions (Error processing permissions.0: Value "history" must either: must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], be one of ["browserSettings"], be one of ["cookies"], be one of ["downloads", "downloads.open"], be one of ["topSites"], be one of ["webNavigation"], be one of ["webRequest", "webRequestBlocking"], or be one of ["activeTab", "tabs"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["telemetry"], be one of ["theme"], be one of ["browsingData"], or match the pattern /^experiments(\.\w+)+$/) for permissions.contains.

**Comment by stoically** [comment]
Could you give [v1.0beta14](https://github.com/stoically/temporary-containers/releases) as spin and see if that helps? There's refactoring regarding handling that kind of error in it.

**Comment by stoically** [comment]
Let me know if the beta doesn't fix it, thanks!

**Comment by YaagoRo** [comment]
It didn't solve the issue.  Instead, now another error message shows up: "Add-on not initialized yet, please try again".

**Comment by stoically** [comment]
Interesting. Yeah, I'm still in the process of making that error-page somwhat useful in the beta, including showing the error if one occurs and a button like "reload add-on".

Since the `permissions.contains` call isn't in the code anymore - something else must fail here. Would you mind checking the Add-on and Developer Tools consoles for any errors? That'd be helpful!

- Add-on console: please follow the instructions for "[debug log while the add-on initializes](https://github.com/stoically/temporary-containers/wiki/Debug-Log#while-the-add-on-initializes)", but instead of `log.DEBUG=true`
- Developer Tools: With the options page open press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> and copy the content of the "console"

Thanks!

**Comment by stoically** [comment]
Also, btw, do you have custom `about:config` settings? I'm asking because the error you reported doesn't make any sense from the Firefox WebExtensions API perspective - `history` is definitely a valid permission string (or otherwise the Add-on would've never worked).

**Comment by stoically** [comment]
Ah, wait. I've just realized that your OS is `Fire OS`, which is Android-based. The container feature is unfortunately not available on Android. Here's the Firefox Bug tracking that: https://bugzilla.mozilla.org/show_bug.cgi?id=1398097

Sorry, but you can't use TC on Fire OS until Firefox supports containers on Android.

**Comment by YaagoRo** [comment]
> Ah, wait. I've just realized that your OS is `Fire OS`, which is Android-based. The container feature is unfortunately not available on Android. Here's the Firefox Bug tracking that: https://bugzilla.mozilla.org/show_bug.cgi?id=1398097
> 
> Sorry, but you can't use TC on Fire OS until Firefox supports containers on Android. In fact, it shouldn't let you install the Add-on on addons.mozilla.org because of that - it's marked as Android-incompatible.

Thanks for taking your time, though. Yeah, I really was happy when your container app (loving it) showed up as compatible with the Android Firefox at addons.mozilla.org.  Maybe the settings it here should be changed, so it shows up as not compatible.  Then you had less error reports like this :-D
