### ISSUE TITLE
Allow resetting container number

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/temporary-containers#280]
When the "keep counting" option is enabled (which is the default), the container numbers eventually get so large they become less useful and take up more space in the location bar.

Can you add an option so the user can manually reset them to 1?  

Or perhaps even an option to automatically reset them to 1 once they hit 4 digits?

**Comment by stoically** [comment]
I'll add the current container number together with a reset button to the statistics tab (if keep counting is active).

**Comment by Gitoffthelawn** [comment]
Sounds great!  Thanks!

**Comment by stoically** [comment]
By the way, as a workaround until I get around to implement this, it's possible to reset the number by executing

```
tmp.storage.local.tempContainerCounter = 0;
tmp.storage.persist();
```

on the [debug console](https://github.com/stoically/temporary-containers/wiki/Debug-Log).

**Comment by stoically** [comment]
Another maybe useful setting might be "Reset after browser restart"

**Comment by Gitoffthelawn** [comment]
> Another maybe useful setting might be "Reset after browser restart"

That sounds like a great idea. :+1:

**Comment by stoically** [comment]
Added in [v1.4beta1](https://github.com/stoically/temporary-containers/releases).

**Comment by Gitoffthelawn** [comment]
Thank you!  I'll check it out soon.
