### ISSUE TITLE
Hide counter / Container Number

### ISSUE THREAD

**Issue by maverick74** [stoically/temporary-containers#281]
Is it possible to create an option to hide the container number?

e.g.: I've set the container name from "tmp" to "" in order to hide it.

can the same (or similar) be done to hide the number?

the thing is that i don't care about which container i'm in. In fact, even the container icon could be hide, if you ask me... but i think the icon is only possible from userChrome.css...

**Comment by stoically** [comment]
The container number is also a way to check whether Isolation worked or not - hence why I didn't implement a hide number option. However, if #228 gets implemented, it could always store/show, say, the last 20 isolations or something, and so there would be a convient way to check if isolation worked, even with container number hidden.

**Comment by maverick74** [comment]
@stoically about the icon, there's nothing to do about it except in userChrome.css, right?

or could it be hidden as well?

**Comment by stoically** [comment]
Yeah, at least I'm not aware of a way to do that other than the userChrome.css

**Comment by stoically** [comment]
Something I noticed: Firefox throws an error when trying to create a container with an empty name (and the `Add` button stays inactive on `about:preferences#containers`). So completely blank name isn't possible. However, creating with container name ` ` (one whitespace) is possible, hah.

**Comment by stoically** [comment]
Added in [v1.4beta1](https://github.com/stoically/temporary-containers/releases).

**Comment by maverick74** [comment]
Hi @stoically,

How do i hide it (where's the option)?

**Comment by stoically** [comment]
@maverick74 hey. You'd have to install the beta version, its not in the stable version yet. There you find it in the preferences under General > Container Number > Hide number

**Comment by maverick74** [comment]
found it!

I had the stable version and tryied to update to the beta and assumed it did update, but it somehow did not install.

I had to download the xpi, remove the stable and install the beta to get it.

Working fine now, Thanks @stoically

**Comment by stoically** [comment]
Yeah, I hit that problem as well, seems like some kind of Firefox bug. For me it worked to disable the Add-on and then install the xpi. Glad it works now for you!
