### ISSUE TITLE
open permanent containers

### ISSUE THREAD

**Issue by seebye** [stoically/temporary-containers#285]
I searched for issues (search term: permanent) which handle this problem, but I didn't found any.  
So I'm creating a new one.  

There are some sites which require to be registered to participate and I don't want to login on these sites each time I open them.  
So I searched for how to create a permanent container and found the following issue which describes how to do that: https://github.com/stoically/temporary-containers/issues/95
Although the permanent container won't be used on opening the site instead it creates a new temporary container.  
Also if I press "Convert to Permanent Container" a second time in such a tab a **new** permanent container will be created.  

---

I read a few new issues which mentioned firefox's multi account containers and found that the permanent containers are listed in it and that it's possible to reopen them.

---

So.. I think it would be great if it would be possible to use the permanent container by default  if a **new** tab tries to open a site which is assigned to the domain of the permanent container.

**Comment by stoically** [comment]
Hey, please check the "How to stay logged in on some websites in Automatic Mode?"-section on [AMO](https://addons.mozilla.org/firefox/addon/temporary-containers/). Handling Permanent Containers in general (besides the convert button) is not in the scope of TC. Hope that helps, let me know if it doesn't.
