### ISSUE TITLE
Do you accept requests for compatibilities with other containers extensions?

### ISSUE THREAD

**Issue by Fanolian** [stoically/temporary-containers#286]
Reference: #125, #261 

Thank you for supporting some other popular containers extensions. There are, however, still many similar extensions which contain other popular services and may conflict with TC. (I use [Amazon Container](https://github.com/Jackymancs4/contain-amazon) which causes infinite loop of respawning containers like what TC did to facebook container.)

Do you accept requests for compatibilities with other containers extensions? I understand this will increase your workload and divert your time from improving the core features of TC. So I think I should ask before making a request.

Thank you for your extension.

**Comment by stoically** [comment]
Sure, no problem, I can add compatibility with other Container Add-ons on demand. It's just copy&paste. (and a pitty that the original Facebook Container didn't open up the API to other extensions, that way all forks would provide their URLs, oh well)

**Comment by stoically** [comment]
Though, if you're asking for compatibility with Container Add-ons that aren't forks from Facebook Container (like #261) - that needs to be investigated on a case-by-case basis and almost certainly depends on whether the other Add-on has or is willing to provide an API.

**Comment by MikeRixWolfe** [comment]
Hello, I'm also running into the infinite loop of temp containers spawning too, when using it in combination with the Containerise extension. Though it's not a Facebook Container fork, it's more of a MAC alternative that allows defining containers explicitly and with wildcards, would it be something you could investigate adding compatibility for similarly?

Thanks for your work 😀

**Comment by MikeRixWolfe** [comment]
Let me know if you'd prefer I open a new issue for this

**Comment by crssi** [comment]
> 
> 
> Hello, I'm also running into the infinite loop of temp containers spawning too, when using it in combination with the Containerise extension. Though it's not a Facebook Container fork, it's more of a MAC alternative that allows defining containers explicitly and with wildcards, would it be something you could investigate adding compatibility for similarly?
> 
> Thanks for your work grinning

[https://github.com/kintesh/containerise/issues/70#issuecomment-509492949](https://github.com/kintesh/containerise/issues/70#issuecomment-509492949)

**Comment by stoically** [comment]
Amazon Container compatibility added in v1.1. In general im open to add compatibility, as long as it's possible and not too hard. Please open a new issue per Add-on so I can decide on a case-by-case basis. Thanks.
