### ISSUE TITLE
Repeatedly opens tabs

### ISSUE THREAD

**Issue by ever-forgotten-92** [stoically/temporary-containers#288]
With the latest release automatic mode opens the same tab repeatedly. Example:

1. From new tab page, type "google.com"
2. Extension opens a new tab for google.com, that tab opens a new one and so forth indefinitely. None of the tabs actually open google.com 

Maybe a redirect issue?

**Comment by stoically** [comment]
Do you by chance have Containerise installed? If so, please update to it's latest version (3.2.0) - see: #287

**Comment by ever-forgotten-92** [comment]
That fixed it, thank you.
