### ISSUE TITLE
Prompt to add domain to a permanent MAC container

### ISSUE THREAD

**Issue by Arthaey** [stoically/temporary-containers#292]
I like the global isolation + MAC feature (thank you!), and I understand the workaround of temporarily disabling it in order to add a new domain to a permanent container.

However, there's a somewhat common workflow that could be a smoother user experience. Let me explain:

### Current behavior
1. I open a new tab in one of my permanent MAC containers.
1. I type a URL into the address bar, intending for it to open in the container I just opened.
1. TC redirects to a temporary container.
1. I realize that I haven't added that domain to the container yet. ;)
1. I disable* global isolation.
1. I open another new tab in the permanent container.
1. I re-type the URL into the address.
1. I add it to the permanent container via the MAC "always open in" option.
1. I re-enable global isolation.

### Desired behavior
1. I open a new tab in one of my permanent MAC containers.
1. I type a URL into the address bar, intending for it to open in the container I just opened.
1. TC prompts me, "Do you want to always open <domain> in <container>?"

If I click "**yes**":

4. TC adds this domain to the permanent container's "always open in" list.
1. The page loads in the container.

If I click "**no**":

4. TC redirects to a temporary container.

\* _By the way, thank you for making the tab bar icon have a very obvious red exclamation point when isolation is disabled!_ :)

**Comment by stoically** [comment]
Thanks for kind words. MAC Isolation is part of Isolation in general, so implementing #282 would cover the "prompt" feature. As for automatically adding domains to MAC, there's no API available for that yet - if the open PR https://github.com/mozilla/multi-account-containers/pull/1197 implementing that gets merged one day, I'll reopen and track progress in #170.
