### ISSUE TITLE
"Advanced > Cookies" section doesn't render

### ISSUE THREAD

**Issue by r-a-y** [stoically/temporary-containers#293]
- Temporary Containers Version: 1.1
- Firefox Version: 68
- Operating System + Version: Windows 10
- Non-default Options/Preferences in Temporary Containers: Automatic Mode, custom cookies are the main ones.
- Other installed Add-ons + Version:

### Actual behavior
The "Advanced > Cookies" configuration section does not render.

### Expected behavior
The cookies UI should render like in previous versions :)

### Steps to reproduce

1. Go to the Options page and navigate to "Advanced > Cookies"
2. Section is blank.

### Notes
Let me know if you need any other info and thanks for maintaining such an important addon!

**Comment by stoically** [comment]
That's unfortunate and sadly I'm unable to reproduce. My guess was that it might have something to do with the added fields `firstPartyDomain` and `sameSite`, but installing older versions, adding cookies, and upgrading works as expected for me.

Could you check the Developer Tools, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> console on the Cookies tab and see if anything pops up?

If there's nothing, the only way to reproduce might be if you could provide your preferences export. That'd helpful. If you have sensitive cookies, maybe consider sending the export by email to stoically@protonmail.com - I'll delete after debugging. Thanks!

**Comment by r-a-y** [comment]
In the console log, I'm getting the following message:

```
TypeError: "domainCookie is null"
    cookieKeys moz-extension://f2279708-711b-4545-8217-8777eefcc203/options.3b0b4fa8.js:1075
    cookieKeys moz-extension://f2279708-711b-4545-8217-8777eefcc203/options.3b0b4fa8.js:1075
    render moz-extension://f2279708-711b-4545-8217-8777eefcc203/options.3b0b4fa8.js:1097
    de VueJS
    render moz-extension://f2279708-711b-4545-8217-8777eefcc203/options.3b0b4fa8.js:1097
    de VueJS
    render moz-extension://f2279708-711b-4545-8217-8777eefcc203/options.3b0b4fa8.js:1097
    VueJS 21
vue.runtime.min.js:6:11718
```

Perhaps there was an issue in the migration to 1.1?

**Comment by stoically** [comment]
Thanks, that's helpful! Well, I think in older versions I just called `delete` on the respective array entry, which leaves an empty entry, and that's why the UI breaks. Added a skip for such cases - could you try [v1.2beta1](https://github.com/stoically/temporary-containers/releases) and see if it works for you?

Also, I'm not using `splice` to remove entries, which actually removes the entry.

**Comment by r-a-y** [comment]
That appears to have fixed things.  Thanks for the quick turnaround, stoically!

Feel free to close this one unless you wanted to do anything else here.

**Comment by stoically** [comment]
Glad it works! :)
