### ISSUE TITLE
Unable to login into web accounts with MAC enabled

### ISSUE THREAD

**Issue by mrtootoo** [stoically/temporary-containers#294]
With all cookies, data, and cache cleared, I am unable to log into an account within its assigned container.  The log in screen always pops to a tmp container even though the domain is the same as the assigned container.  Once credentials are saved with MAC disabled, all works well with MAC enabled.  This is only an issue when cookies, data, and cache are cleared.

-->
- Temporary Containers Version: 1.1
- Firefox Version: 68.0
- Operating System + Version:  UbuntuMate Release 18.04.2 LTS (Bionic Beaver) 64-bit
- Non-default Options/Preferences in Temporary Containers: Automatic Mode
- Other installed Add-ons + Version:
Amazon.com	1.1	TRUE
Bing	1	TRUE
CSS Exfil Protection	1.0.15	TRUE
Decentraleyes	2.0.12	TRUE
Disconnect	5.19.2	TRUE
Don't track me Google	4.22	TRUE
DuckDuckGo	1	TRUE
eBay	1	TRUE
Firefox Multi-Account Containers	6.1.0	TRUE
Flagfox	6.1.15	TRUE
Google	1	TRUE
Google search link fix	1.6.8	TRUE
hotfix-update-xpi-intermediate	1.0.6	TRUE
HTTPS Everywhere	2019.6.27	TRUE
Privacy Possum	2019.7.18	TRUE
Private browsing theme	2.1	TRUE
Simple Translate	2.1.0	TRUE
Temporary Containers	1.1	TRUE
Twitter	1	TRUE
uBlock Origin	1.20.2	TRUE
User-Agent Switcher	1.3.2	TRUE
Wikipedia (en)	1	TRUE
Bypass Paywalls	1.4.3	FALSE
CanvasBlocker	0.5.12	FALSE
Cookie AutoDelete	3.0.2	FALSE
Disable Autoplay	1.2	FALSE
Easy Youtube Video Downloader Express	15.7	FALSE
Lockbox	2.1.0-alpha	FALSE
Privacy Badger	2019.7.1.1	FALSE

**Comment by stoically** [comment]
The login probably navigates probably to a target domain which is a) different from the tab domain and b) not assigned to "always open in" that container in MAC - which leads to isolation.

A workaround is to check with isolation disabled which domains are involved, and add them as excluded target domain, either global or per domain.

(You could also configure `network.http.redirection-limit` in `about:config` temporarily to `0` and assign the domain to MAC that way).

Hope that helps - let me if it doesn't.

Related: #170

**Comment by mrtootoo** [comment]
Maybe I don't understand, but my understanding is that the target domain (not the complete URL) is the same as the tab domain and assigned to "always open in" that container in MAC.  

"A workaround is to check with isolation disabled which domains are involved, and add them as excluded target domain, either global or per domain."

So to disable isolation, is that accomplished by unchecking Automatic Mode or disabling MAC?

**Comment by stoically** [comment]
Disabling isolation can be done globally in the popup (circle icon in the top nav), or by disabling MAC Isolation separately. Automatic Mode isn't part of isolation.

Logins often redirect over a subdomain or thirdparty domain (Single sign-on). Disable isolation, open the Developer Tools network tab with `Persist Logs` checkbox activated and `HTML` selected - and then login to see all involved domains.

**Comment by mrtootoo** [comment]
Is there a way I can open a link in the default tab with MAC enabled?
I don't think MAC lets you set default tab as a fixed tab.  With MAC enabled, I can not open anything in the default tab (except a local html file).  So is there a way I can open a link in the default tab with MAC enabled?

I am not sure if this is the best place to post,  Please let me know if there is a better way to get support?  Thanks.

**Comment by stoically** [comment]
Not possible with MAC. Your best bet would be to use Containerise, which lets you assign domains to "No Container" - and Containerise assigned domains are ignored from TC.

Hope that helps - and it's fine to ask here.

**Comment by mrtootoo** [comment]
Your suggestion to use Containerise along side temporary-containers has worked great.  However, I have noticed after going several days, I will check Firefox’s Cookies and Site Data.  I will see the data from a few sites that are not white listed saved.  I did not see any cookies from these sites.  So I am curious how that data got saved if the container was deleted.

**Comment by stoically** [comment]
Glad it worked out.

There's an open issue about Firefox not removing all storage when containers are removed, see https://bugzilla.mozilla.org/show_bug.cgi?id=1474608 and #127. Note however, that such storage isn't accessible by any container or website since the underlying userContextId (container id) is different.

**Comment by mrtootoo** [comment]
Thanks.  I actually just came back to edit my last.  It occurred to me that sometimes e-mail links open in the e-mail container.  I was thinking this was the possible source.  Re-enabling MAC took care of the accidental openings.  I will wait and see how well MAC, Facebook Container, Containerise, and temporary-containers play together.
