### ISSUE TITLE
Automatic Mode not picking up mouse clicks from "Text Link webext" addon

### ISSUE THREAD

**Issue by r-a-y** [stoically/temporary-containers#295]
- Temporary Containers Version: 1.1
- Firefox Version: 68.0.1
- Operating System + Version: Windows 10
- Non-default Options/Preferences in Temporary Containers: Automatic Mode + Cookies
- Other installed Add-ons + Version: Text Link webext 1.1.0

### Actual behavior
Ensure Temporary Containers is set up to use Automatic Mode.

I use the addon [Text Link webext](https://addons.mozilla.org/en-US/firefox/addon/text-link-webext/) to transform text links into URLs via a double-click mouse action.  When I double-click on a text link, a new tab opens with that URL.

In a previous version of Temporary Containers, this new tab would open in a temporary container.  In v1.1, this new tab opens in the Default Container.

### Expected behavior
When I double-click on a text link, a new tab opens with that URL.  This new tab should open in a new temporary container if Automatic Mode is on.

### Steps to reproduce

1. Install the "Text Link webext" addon
2. Ensure Temporary Containers is set up for Automatic Mode
3. Double click on the following text link - `https://wikipedia.org`
3. A new tab should open with `https://wikipedia.org` as the URL.  Check to see if this new tab is using a new temporary container.

### Notes
Let me know if you need anything else from me to debug.

**Comment by crssi** [comment]
Hmmm... here it works as it should.

My prefs: `https://github.com/crssi/Firefox/blob/master/temporary_containers_preferences.json`

Cheers

**Comment by r-a-y** [comment]
Weird... it's working for me now after restarting Firefox!

Disregard 😅
