### ISSUE TITLE
Use same container while opening an external link

### ISSUE THREAD

**Issue by chrisyue** [stoically/temporary-containers#297]
Is there a way I can set using the same container when I open an external link (from, for example, MSN) if the link has the same domain as the container using (or flaged)?

**Comment by stoically** [comment]
It's not possible to differentiate between externally opened links and links opened by a tab, which makes it impossible to implement such a feature. Though, even if it'd be possible, having that option would mean that any link could open in any already open temporary container at any given time, e.g. if you switched tabs or windows before opening an external link - breaking isolation where you wouldn't expect it.

If you want to open a specific domain in the same container I'd go with [Multi-Account Containers](https://github.com/mozilla/multi-account-containers) or [Containerise](https://github.com/kintesh/containerise) and pin the domain to a specific container. Hope that helps.
