### ISSUE TITLE
Right clicking on links causes context menu item under the mouse to be clicked

### ISSUE THREAD

**Issue by dako98** [stoically/temporary-containers#300]
- Temporary Containers Version: 1.2
- Firefox Version: 68.0.2 (64-bit)
- Operating System + Version: Ubuntu 19.04
- Non-default Options/Preferences in Temporary Containers: 

General:
  * Automatic Mode: on
  * Show popup when clicking toolbar icon : on
  * Container Number : Reuse available numbers

Isolation:
* Navigation:
  * Target Domain: Different from Tab Domain & Subdomains

- Other installed Add-ons + Version:
Name 	Version 	Enabled 	ID
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
Dark Reader	4.7.16	true	addon@darkreader.org
Decentraleyes	2.0.12	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Enhancer for YouTube™	2.0.95	true	enhancerforyoutube@maximerf.addons.mozilla.org
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
HTTPS Everywhere	2019.6.27	true	https-everywhere@eff.org
LastPass: Free Password Manager	4.31.2.3	true	support@lastpass.com
NoScript	11.0.3	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Plasma Integration	1.5	true	plasma-browser-integration@kde.org
Privacy Badger	2019.7.1.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Temporary Containers	1.2	true	{c607c8df-14a7-4f28-894f-29e8722976af}
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.21.2	true	uBlock0@raymondhill.net
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org

### Actual behavior
Right-clicking on links, so that the context menu will appear under the mouse (i.e. right part of screen) would cause the context menu entry to be clicked.

### Expected behavior
Right-clicking brings up the context menu and does not click any of the menu entries.

### Steps to reproduce

Maximized browser window. In temporary container tab. Right mouse button.

1. Open a webpage with links on the right side of the page.
2. Right-click on a link, so that the context menu would open under the cursor, not beside it.
3. The context menu option that was under the cursor would be presses (ex. Open in new tab, open in new private window, view page source).

### Notes
Make sure the menu entry is right under the mouse cursor, approximately the vertical middle of the menu item.
Disabling the extension fixes the problem.

Bonus points if you provide a debug log:

[Temporary-containers-DEBUG.txt](https://github.com/stoically/temporary-containers/files/3536949/Temporary-containers-DEBUG.txt)

**Comment by stoically** [comment]
Unfortunately there's no [context menus API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus) to control that behavior, it's only possible to control which menu items show up and what happens if they're clicked - so that's a Firefox bug which you'd need to report on [bugzilla](https://bugzilla.mozilla.org/) instead.

**Comment by stoically** [comment]
Though, if you don't need the TC context menu entry, maybe disabling it in the preferences under `Advanced > Context Menu` also helps.

**Comment by dako98** [comment]
Disabling the context menu entries still doesn't fix the issue.
The problem does not occur if the extension is disabled, so I don't think it's a Firefox issue.

**Comment by stoically** [comment]
There's no way (API or content scripts) for Add-ons to programmatically click on the context menu. So having TC enabled might cause some side-effect in Firefox itself leading to the bug, but it's not TCs code causing it.
