### ISSUE TITLE
Window-based containers option

### ISSUE THREAD

**Issue by Jeremia-h** [stoically/temporary-containers#302]
I think it could be useful to have temporary containers based on the window. This way, the container is based on which Firefox window instance you have running rather than each tab. Maybe an option to select it next to automatic mode.

**Comment by stoically** [comment]
Problems I see with such a configuration:

* Isolation should *always* open new TCs, so it would still open new TCs in the given window
* Opening links in external programs might open the link in the wrong window if you don't carefully make sure that you had a given window active before opening the link - which might lead to links opened in the wrong "temporary window container"
* windowIds are not persistent between browser restarts, so it's tricky to find the "correct temporary window container" - and "restore previous session" complicates things even more

Given that I'm unfortunately not open to such configuration.

Maybe give [Sticky Containers](https://addons.mozilla.org/firefox/addon/sticky-containers/) a try instead - though, I've never tested if it plays nice with TC.
