### ISSUE TITLE
Periodical memory usage spikes

### ISSUE THREAD

**Issue by kotyhoroshko2** [stoically/temporary-containers#304]
- Temporary Containers Version: 1.3
- Firefox Version: 69.0
- Operating System + Version: Ubuntu 19.04
- Non-default Options/Preferences in Temporary Containers: 
[temporary_containers_preferences_2019-9-11_22.34.44.json.txt](https://github.com/stoically/temporary-containers/files/3602513/temporary_containers_preferences_2019-9-11_22.34.44.json.txt)

- Other installed Add-ons + Version:

### Actual behavior
Occasionally, memory usage by WebExtensions process starts growing rapidly. It takes about 30 seconds to reach the peak at ~2 GB and then it quickly gets back to normal.
I managed to screenshot about:memory page at the peak usage. It looks like the memory is used by Temporary Containers addon.

![Знімок екрану з 2019-09-11 11-30-20](https://user-images.githubusercontent.com/45513802/64729339-a86fa880-d4e5-11e9-80f8-4b259f656d5f.png)

### Expected behavior
The addon should not consume unreasonably high amounts of memory.

### Steps to reproduce

1. Launch Firefox.

It does not seem that there is a user action that triggers it. I remember it happened once while the browser was not in focus at all.

**Comment by kotyhoroshko2** [comment]
> Did you monitor about:performance as well to make sure it's TC consuming the memory?

I have just checked about:performance but it does not report high memory usage by TC while the issue happens. I could see high CPU usage though:

![about:performance screenshot](https://user-images.githubusercontent.com/45513802/64923884-18807600-d7e7-11e9-9b8d-0ee9e3d0023e.png)

I think I have an explanation of this. Previously I noticed that manually invoking garbage collection ("GC" button in about:memory) makes the memory usage by WebExtensions process almost instantly go back to normal for a moment. (But then it continues to grow.)
I believe that that means that all of those allocations are temporary objects, which get unreferenced immediately and thus cannot be attributed to any page/add-on.
> Do you have a lot of tabs open when it happens?

Yes. Many more than 100.

Also, on the screenshot in my first message it is possible to see that a big part of that memory is multiple copies of URL-encoded images (mostly icons). I would guess that those might be clones of tabs.Tab.favIconUrl field.

**Comment by stoically** [comment]
Interesting. 13.5 MB memory is already unusually high - and I can see how GC might be the reason for `about:performance` not showing the memory, though, if `about:memory` reports it accurately for the given extension, it *should* also be shown on `about:performance`.

Just to make sure: TC has the Internal UUID `00f4cffb-4a9b-412f-9347-8eba9ab427e4` in your Firefox? You can check on `about:debugging#/runtime/this-firefox` (the Internal UUID is unique per installation).

Would you mind providing a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) for the time frame when the issue happens?

**Comment by stoically** [comment]
And what's your average memory usage from TC without the issue?

**Comment by kotyhoroshko2** [comment]
> TC has the Internal UUID 00f4cffb-4a9b-412f-9347-8eba9ab427e4 in your Firefox?

Yes
![about:debugging screenshot](https://user-images.githubusercontent.com/45513802/64926955-d23e0d80-d80c-11e9-83d8-f4d8ff4c0a4a.png)

> And what's your average memory usage from TC without the issue?

On fresh start was is 2.5 MB.
After some usage it went to 3.8 MB.
Then the issue happened and it jumped to ~14 MB.
Then it went back to 3.7 MB.

I will try to collect more info.

**Comment by stoically** [comment]
Did some refactoring regarding container cleanup in #305 and published as v1.4, it doesn't use browser APIs in intervals at all anymore. So hopefully that addresses the memory spike as well. Please let me know if it pops up again.

**Comment by accountForIssues** [comment]
I am facing this issue since a week or two.

Firefox 116.0.3 (could have been in earlier versions as well)

I rarely keep any tabs open and usually delete containers on my own as well once I'm done.

Recently, I started noticing my memory usage going very high especially when I'm not using the browser. Once it got to 99% and my OS started killing other processes.

As soon as I start using the browser or open and close a new tab, the usage resets to normal values. It was even difficult to take this screenshot as it immediately reset the high usage.

settings - [temporary_containers_preferences_2023-08-29_15.17.56.json.txt](https://github.com/stoically/temporary-containers/files/12464949/temporary_containers_preferences_2023-08-29_15.17.56.json.txt)

The screenshot was taken when 3-4 containers were present. However, no tabs except one about:preferences were open.

![image](https://github.com/stoically/temporary-containers/assets/52367365/b83ba05d-45fd-41ca-839c-63275615ad63)
