### ISSUE TITLE
Setting cookies doesn't seem possible?

### ISSUE THREAD

**Issue by iKarith** [stoically/temporary-containers#306]
Testing with version 1.3.

This might be me simply not understanding how to use this feature, given that it's basically undocumented:

> Set Cookies
> Sometimes you might want to set and send a specific cookie even when browsing in a Temporary Container. The advanced Set Cookies feature lets you configure on which websites cookies should be set. Setting cookies can make you easier fingerprintable. Especially when they contain user/session-specific data. Avoid setting cookies if you can.

I set the required values:

Domain Pattern: localhost
domain: [blank]
expirationDate: [blank]
firstPartyDomain: [blank]
httpOnly: [blank]
name: ae
path: [blank]
sameSite: [blank]
url: localhost
value: d

Typically I'd set an expirationDate, but "win the tab closes" is more than sufficient if the cookie is going to be re-set every time it needs to be set. (Also, I tried setting it, which didn't help.)

You might have guessed what I'm _actually_ trying to do here, as ae=d sets DuckDuckGo to dark theme. But no combination of anything I can think of to type into Domain Pattern, domain, url, and path results in the cookie actually being set—checked by opening the dev tools and seeing what's listed under storage after opening localhost.

I had this feature working with an older profile and version of the extension, but had trouble figuring it out to set that up as well, so if I am simply not understanding how to do this correctly, I'm likely to edit src/ui/components/advanced/cookies.vue to explain how you do it, provide an example, and send you a PR for the sake of my own sanity the next time I have to rebuild a profile. ;)

Something else I might do (if it doesn't break the code to do it) is possibly reorder the form elements to group domain/url first, key/value next, expiration, and then everything else.

I think the fingerprintability of ae=d on DuckDuckGo is probably pretty low as it recently won their poll for most popular feature.

**Comment by stoically** [comment]
![image](https://user-images.githubusercontent.com/29637501/65506533-0cbe3f00-decc-11e9-8f9e-feed08cb6d5a.png)

works for me.

> given that it's basically undocumented

Well, it links to [cookies.set](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/set), which kinda documents it, but not really I guess. I'd be happy to put something into the Wiki and link there, if you want to write something up.

> I had this feature working with an older profile and version of the extension

It's now possible to export and import preferences, that might help with future migrations to new profiles.

> reorder the form elements to group domain/url first, key/value next, expiration, and then everything else.

Thanks for the suggestion, but I've intentionally chosen the same order as [cookies.set](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/set#Parameters) and would like to keep it that way.

**Comment by iKarith** [comment]
![Screenshot from 2019-09-24 06-36-25](https://user-images.githubusercontent.com/10780557/65516405-d4037300-de95-11e9-9eaa-684682e23f85.png)

That was the first thing I tried, exactly the setting you have. I then open a new tab (automatic is on), and type duckduckgo.com …

![Screenshot from 2019-09-24 06-36-40](https://user-images.githubusercontent.com/10780557/65516408-d4037300-de95-11e9-86fa-a28a877b50ad.png)

That doesn't look like dark mode.

![Screenshot from 2019-09-24 06-36-51](https://user-images.githubusercontent.com/10780557/65516409-d4037300-de95-11e9-894f-b25a01f4a5fa.png)

And the cookie isn't set. I disabled every other plugin just in case somehow there's a plugin that would somehow break this, but that didn't help.

**Comment by iKarith** [comment]
(save for DDG Privacy Essentials, which provides my search engine setting. I could remove that I suppose.)

**Comment by stoically** [comment]
Do you by chance have `privacy.firstparty.isolate` set to `true` in `about:config`? If that's the case you'd have to set `firstPartyDomain` to `duckduckgo.com` as well.

**Comment by iKarith** [comment]
Huh, how'd that get set? It was true, and I don't think that's the default. Sure enough setting it to false fixes the problem, as does setting firstPartyDomain as you suggest. Haven't decided which option I'm going to go with.

I'll write something up and get it to you.
