### ISSUE TITLE
Wiki: Create a link to the "support" issues

### ISSUE THREAD

**Issue by mdhooge** [stoically/temporary-containers#310]
Hello,

First of all, many thanks for your add-on. It is brilliant!

Since you took the time to flag some issues with a "Support" label, I think it'd be nice to reference them globally from the Wiki. This would be really helpful, at nearly no cost for you ;-)

https://github.com/stoically/temporary-containers/issues?q=label%3Asupport

**Comment by stoically** [comment]
Hey, happy you like it :)

Thanks for the suggestion, added the link to the wiki.
