### ISSUE TITLE
Always use the same temporary container unless creating a new one is explicitly requested

### ISSUE THREAD

**Issue by cy7yz2rj** [stoically/temporary-containers#312]
I want to make TC work in a specific way but I don't know how to achieve it or if it's possible at all.

Using Containerise, I have a list of domains configured to only open in their respective permanent containers, independently of how they're navigated to. This works fine.

What I also want is for everything else to open in the same, single temporary container (tmp1), unless explicitly requested by me (using CTRL + Left mouse for example) to open in different temp containers (tmp2, tmp3, etc).

**Comment by stoically** [comment]
I think the latest Containerise release has some form of default temporary container in the preferences - maybe that works for you? TC could then help with creating new TCs by using mouseclicks.

**Comment by cy7yz2rj** [comment]
I was unaware of that preference but at first glance it doesn't quite work the way I want.

When opening a folder of bookmarks, Containerise appears to create more than 1 temporary default container, even if the bookmarks are all the same domain. Still, it is closer to my goal than TC in automatic mode, which will (correctly) create 1 tmp for each tab.

Closing this as it's not a bug in TC, and thanks for your work on this great extension.
