### ISSUE TITLE
Automatically re-enable Isolation after a delay

### ISSUE THREAD

**Issue by mdhooge** [stoically/temporary-containers#315]
If you use this add-on, this is to have Isolation enabled most of the time. When one disables Isolation, this is to prevent the add-on to create a new temporary for a given action…
So it would be nice to be able to define in the options a delay after which the Isolation is enabled again.
Or maybe, a count: “Ignore the next N navigation actions” (with N=1 for most users). But I think this is less intuitive than a 5s delay (for example). Especially when there are a couple of redirections after login in to a site…

**Comment by stoically** [comment]
Would be nice to have indeed.

**Comment by mdhooge** [comment]
I'll dive into it as soon as I feel more confident with the code! A lot of JS habits to (re-)discover… :sweat_smile:
I'm actively on it! :crossed_fingers:

**Comment by stoically** [comment]
Cool! Let me know if I can be of any help :)

**Comment by stoically** [comment]
Published v1.9beta2 with the feature, thanks @rkodey!
