### ISSUE TITLE
Not working with Firefox 70

### ISSUE THREAD

**Issue by alphazo** [stoically/temporary-containers#316]
I heavily rely on this wonderful addon but I have noticed that it no longer works under Firefox 70. 
I'm running ArchLinux but the container option no longer works, neither when I open a new tab in automatic mode or by clicking on the the top right plus button (now greyed out).

**Comment by stoically** [comment]
Works just fine with Firefox 70 for  me. Grayed out icon normally means that you run in "Permanent Private Mode", which is activated by "Never remember history" in the Firefox Preferences - maybe that's the case for you?

**Comment by alphazo** [comment]
I have browser.privatebrowsing.autostart set to 1 in about:config and browser history to "Remember history" and this setting has been working for year with the addon.
I reverted back to browser.privatebrowsing.autostart=0 and temporary-containers working in regular windows. Now if I open a new private window then temporary-containers is not working anymore. 
For information I did enable "Run in Private Windows" in the addons setting.

**Comment by alphazo** [comment]
Sorry for the noise but I also downgraded to Firefox 69.0.3 and same issue with a brand new profile in Private mode.

**Comment by alphazo** [comment]
Went through old tickets to realize that TC is not available in private mode. I must have changed something in my config recently. I'm really sorry for the confusion.

**Comment by stoically** [comment]
No worries, happy you figured it out. Sadly containers are not available in private windows, maybe that changes one day. Related issue here: https://github.com/mozilla/multi-account-containers/issues/469.
