### ISSUE TITLE
Icon Popup

### ISSUE THREAD

**Issue by stoically** [stoically/temporary-containers#32]
- [x] Advanced preference to show the popup instead of opening Temporary Container when clicking the default Toolbar Icon
- [x] Advanced preference to show additional Icon in the address bar that reveals the Popup

The popup should let you
- [x] Configure Isolation per Domain
- [x] Open preferences
- [x] Convert Temporary to Permanent Container 
- [x] Convert Permanent to Temporary Container 
- [x] Open current Tab URL in new Temporary Container
- [x] Open current Tab URL in new "Deletes History Temporary Container" (if history permission was given)
- [x] Open a new "Deletes History Temporary Containers" tab (if history permission was given)
- [x] Convert "Deletes History Temporary Containers" to regular Temporary Containers to prevent deleting of history

Related: #16 #56 
Depends on: #91

**Comment by anewuser** [comment]
@andreicristianpetcu I read your comment saying that you'd likely contribute to Containers on the Go if it was open source, so [take a look  at this alternative](https://addons.mozilla.org/addon/temporary-containers/) and what's planned for it, if you haven't yet.

**Comment by andreicristianpetcu** [comment]
I already am a user :) Will contribute when I will have some time.

**Comment by stoically** [comment]
Here are the first steps towards a pageAction popup. It'll be opt-in with the advanced preferences.

![pageaction](https://user-images.githubusercontent.com/29637501/36397255-38fed5b8-15c2-11e8-9d32-e2f2507873ff.gif)

![image](https://user-images.githubusercontent.com/29637501/36397249-2e54d5b8-15c2-11e8-93ee-f51f1a99bb85.png)

**Comment by stoically** [comment]
I've published version 0.57beta1 on the beta channel. Any testing would be much appreciated.

**Comment by stoically** [comment]
Just published version 0.80 with the Icon Popup. It's possible to either show an additional Icon in the address bar or change the functionality of the Toolbar Icon to show the Popup.

@anewuser What might be interesting for you is that it's now also possible to configure "Always Per Domain" (previously "Always per Website") in the Popup.
