### ISSUE TITLE
Isolation based on webNavigation.TransitionType

### ISSUE THREAD

**Issue by stoically** [stoically/temporary-containers#327]
Would need the `webNavigation` permission, though that could be asked on-demand. The list of transition types can be found [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/transitionType). That might be useful to e.g. only trigger isolation when the user entered something into the address bar. The only issue might be that [`webNavigation.onCommitted` has no request id](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCommitted#details), and hence the decision must be made based on the `tabId`.

When/If implementing that, it might be worthwhile to consider changing the (Per Domain) Isolation UI to be more like something like [Request Control's Rules](https://addons.mozilla.org/firefox/addon/requestcontrol).

**Comment by crssi** [comment]
That is so thrilling. Cannot wait for it. Christmas is coming. 😄 👍

**Comment by stoically** [comment]
Welp, sorry to get you hyped @crssi, but it seems I was wrong. While the feature could be implemented, it wouldn't prevent the tab from actually connecting to the remote server (and potentially sending cookies), since the `webNavigation.onCommitted` docs say `At least part of the new document has been received from the server`.

**Comment by crssi** [comment]
If you open the bugzilla ticket then, please, make sure you post it here, so I/we can place a vote on bugzilla. 😉

Thank you

**Comment by stoically** [comment]
Here's the ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1600069

Putting this issue in the blocked by third-party column for now.

**Comment by crssi** [comment]
Voted 😄

**Comment by geeknik** [comment]
I marked the Mozilla bug as NEW for you so it maybe gets picked up quicker.
