### ISSUE TITLE
"Add-on could not be installed because it appears to be corrupt"

### ISSUE THREAD

**Issue by in4u** [stoically/temporary-containers#331]
- Temporary Containers Version: 1.3
- Firefox Version: 70.0.1

### Actual behavior
Firefox shows an update available for this add-on but fails to update when clicking the update option. Downloading and installing the XPI manually throws up an error: `This add-on could not be installed because it appears to be corrupt.`

### Expected behavior
Install / update should not fail.

### Notes
On trying to install the XPI as a temporary add-on in `about:debugging` resulted in an error: `manifest.incognito set to "not_allowed" is currently unavailable for use.`

I have set `extensions.allowPrivateBrowsingByDefault` to true so by resetting it in `about:config`, the XPI installation no longer showed the corrupt message but the regular permissions dialog while installing. On selecting `OK`, there was no subsequent message confirming successful install which is usually displayed in the top right hand side of Firefox. Closed browser and re-opened. Still v1.3. Tried again, same result.

I keep the `Update Add-ons Automatically` option disabled. So, manually checked for updates. Then clicked update option. The installed version still showed as 1.3. Tried again by installing as a temporary add-on in `about:debugging`. It worked! Removed the temporary add-on and restarted Firefox. The extension finally got updated, somehow!

**Comment by stoically** [comment]
Thanks for letting me know. Reported on Bugzilla: [1600423](https://bugzilla.mozilla.org/show_bug.cgi?id=1600423).

Leaving open for now for visibility.

**Comment by in4u** [comment]
One more thing, the extension's settings were reset after updating to 1.6. Good thing I had a previous backup though!

**Comment by stoically** [comment]
That probably happened while trying to get it installed/updated. Loading via `about:debugging` sometimes does weird things to Add-on storage. Happy you have an export.

**Comment by in4u** [comment]
Ah okay, cool. Thanks!

**Comment by stoically** [comment]
Bugzilla ticket got closed as "working as expected".

**Comment by PeterDaveHello** [comment]
I got the same problem here

![image](https://user-images.githubusercontent.com/3691490/88527424-d1caf180-d02f-11ea-9313-f9e836d79ec2.png)

Tor Browser 9.5.1 (based on Mozilla Firefox 68.10.0esr) (64-bit)
(`Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0`)
