### ISSUE TITLE
No automatic new container on new tab

### ISSUE THREAD

**Issue by keganlance** [stoically/temporary-containers#332]
The automatic mode behaviour changed with the last 30 november update.

How it worked before:
You open a new tab, the addon creates a new session container tab and closes the new tab.

How it works now with the 30 november update:
You open a new tab, nothing happens. Only when you then go to some website, it opens in a new container.

Problems with this behaviour are:
- Certain reserved domains like addons.mozilla.org don't open in a new session container
- This breaks search engines which use post requests as the post request is lost when the addon changes the container.

Is there any way we can get back to the behaviour before the 30 november update?

**Comment by stoically** [comment]
Do you have "new tabs" set to "Blank page" in the Firefox preferences? If so: Unfortunately it's not reliably possible to detect new tabs that are set to "Blank page", in order to reopen them in a TC, without introducing a lot of possible side-effects (#311, #321). So the only fix, unless we get an API from Firefox to detect new "Blank page" tabs, is to set it to "Firefox Home" instead.

**Comment by keganlance** [comment]
Thanks your your quick reply! I indeed have it set to about:blank. Just changed to about:home and solves the issue. Thanks for explaining why about:blank is an issue. And thanks for this wonderful addon!

**Comment by stoically** [comment]
Glad you like it and that about:home works for you! I'll look into opening a Bugzilla ticket and ask for the needed API.

**Comment by grahamperrin** [comment]
> … I'll look into opening a Bugzilla ticket and ask for the needed API. …

https://old.reddit.com/r/waterfox/comments/fzn7rw/-/fn5ytgy/ there's a note of the feature working with Firefox versions `74` and `75.0`. 

@stoically should this issue remain pinned? For users of Firefox ESR `68`, maybe?

**Comment by stoically** [comment]
@grahamperrin The issue unfortunately persists. Updated the title to clarify what this is about.

**Comment by TommieWong** [comment]
Any progress on this?
