### ISSUE TITLE
Settings view does not show current configuration

### ISSUE THREAD

**Issue by c7hm4r** [stoically/temporary-containers#339]
- Temporary Containers Version: 1.7
- Firefox Version: 71.0

### Actual behavior
Previous configuration is not loaded in settings view. I.e., e.g. automatic mode is active but unchecked in the settings view.

### Expected behavior
Current configuration is consistent with the settings view.

### Steps to reproduce
1. Create new profile, install TC
2. Open TC settings
3. Check automatic mode
4. Close TC settings
5. Open new tab → automatic mode works
6. Open TC settings

### Notices

Operating system: Fedora 31

**Comment by stoically** [comment]
Unfortunately can't reproduce. Could you check the Developer Tools console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) and see if logs any errors?

**Comment by c7hm4r** [comment]
In a newly created profile used to check the reproduction steps I had a settings tab open, I saw a message about some problems with fonts in the error console. Unfortunately, I reloaded the tabs an I am not able to reproduce this error message anymore. Except that there were and are no error messages. The problem with the settings view is still present, though.

**Comment by c7hm4r** [comment]
My operating system: Fedora 31

**Comment by stoically** [comment]
That's interesting. The preferences page loads the storage directly using the Firefox API, and if it would fail to do so, there would be an error (both in the UI and the console). So it seems that for some reason the storage isn't actually persisted. If you restart the profile (close the window running the profile and launch it again) is the Automatic Mode still active?

**Comment by c7hm4r** [comment]
No, it’s not active after profile restart.

**Comment by stoically** [comment]
In this case I would need a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log). ("Reproducing the issue" in this case is just ticking the checkbox after opening the preferences page)

**Comment by c7hm4r** [comment]
The debug log: [temporary_containers.log](https://github.com/stoically/temporary-containers/files/3935462/temporary_containers.log)

**Comment by c7hm4r** [comment]
```
ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. ExtensionStorageIDB.jsm:812
```
was colored red.

**Comment by c7hm4r** [comment]
This could be a Fedora issue: https://bugzilla.redhat.com/show_bug.cgi?id=1779570

**Comment by stoically** [comment]
Yep, looks like the Fedora FF71 binary is broken. Might want to downgrade or something. :)

**Comment by c7hm4r** [comment]
I cannot reproduce this with the upstream Firefox 71.0.
