### ISSUE TITLE
URL bar button greyed out

### ISSUE THREAD

**Issue by c7hm4r** [stoically/temporary-containers#340]
- Temporary Containers Version: 1.7
- Firefox Version: 71.0

### Actual behavior
The URL bar button is greyed out:

![grafik](https://user-images.githubusercontent.com/1974041/70379363-ee44dd00-192b-11ea-83a6-69d5a68c2326.png)

### Expected behavior
Button is not greyed out.

### Steps to reproduce
1. Create new profile
2. Install TC
3. Enable automatic mode in settings
4. Open new tab
5. Go to example.com
6. Click on ••• in the URL bar

**Comment by stoically** [comment]
That's expected behavior. The address bar icon (pageAction) is disabled by default. If you want to enable it you can do so by ticking the checkbox in the TC preferences under Advanced -> Popup.
