### ISSUE TITLE
Show toolbar popup with long press

### ISSUE THREAD

**Issue by rampaa** [stoically/temporary-containers#343]
I would find it easier if there was an option to make short pressing to toolbar icon open a new tab while long pressing to it opens the toolbar popup.

**Comment by stoically** [comment]
Thanks for the suggestion, but long clicking is not something Add-ons can influence using the API yet. However, it'll be possible soon to at least change the behavior when toolbar icon is middle-clicked or clicked with some modifier (ctrl, shift), that's tracked in #326.
