### ISSUE TITLE
Unable to recover URLs from closed temporary tabs

### ISSUE THREAD

**Issue by geeknik** [stoically/temporary-containers#344]
This behavior seems new to me. Maybe it's related to #263?

Create a new Nightly profile. 

Install Multi-Account-Containers and Temporary-Containers. Set Temporary Containers to Auto so that all new tabs go into a temporary container.  Then set TC to reuse available numbers and to delete the temporary container when the last tab in it closes. 

Create a container and assign a site like Twitter to always open in that container so that it in essence becomes a permanent container. 

Visit a random website in a temporary container tab, now open a new tab. Close the Twitter tab and the random website in a temporary container tab so that all you have left is the new empty tab.

Now perform an operation to Undo Close Tab.  A "New Tab" opens. Do it again and the permanent Twitter container re-opens. The URL that opened in the temporary container tab is lost forever. 

I don't have TC setup to delete history or anything like that, so I don't believe the URL should be lost if the temporary container it was opened in was deleted.

**Comment by stoically** [comment]
That's expected behavior. There's a tooltip when selecting the removal delay giving a hint that the delay is required to undo. That was implemented in #28 - it has details why undo doesn't work in case of instant removal. The reason it might now be more obvious is because since #305 the container removal is faster than before. Hope that helps.

**Comment by stoically** [comment]
Oh and btw, the URLs aren't deleted from history. They're just not in the "recently closed tabs" anymore, and hence undo doesn't work. You could check history to recover the URL.

**Comment by geeknik** [comment]
So is it a Firefox limitation in regards to containers? I guess I don't understand why the URL is lost when I'm not using the "Deletes History Temporary Containers" feature. I don't necessarily want the temporary container back, the URL can open in a new one for all that it matters.

**Comment by geeknik** [comment]
That seems like a silly limitation on the part of Firefox.

**Comment by stoically** [comment]
Well, it kinda makes sense. If the container is deleted you would open the URL in another container without being aware. While opening from history its more pro-active, because URLs from there open in the currently active container (normally).

**Comment by geeknik** [comment]
Well, except temporary containers are just that, temporary, so if undoing a tab close operation re-opens that tab in a new temporary container, I don't think anyone would be bothered by the behavior because isolation is working. But I'll just bump the timeout up to 2 minutes and hope the browser doesn't geek out when there is an abundant amount of temporary tabs to delete every 2 minutes.

**Comment by stoically** [comment]
Not everyone uses TC in Automatic Mode or with Isolation. So if you explicitly open a TC without having them, close it, it gets removed, and you undo, you'd end up with that URL in the default container.

Removing containers a lot of containers work good for me. There's a 2.5seconds delay between each removal which in my tests works fine when closing ~200 tabs at once.
