### ISSUE TITLE
Unless I don't know how to use the combo FF Multi-account Containers + Temporary Containers, or I'm using the wrong add-ons, setup for my basic use case is a bit of a pain. Help!

### ISSUE THREAD

**Issue by firepainting** [stoically/temporary-containers#352]
Just found out about containers. 

My use case is quite simple: 
- MAC for all sites I need to be logged in on all the time
- TC for everything else (even if it's a link found in a MAC tab)

On TC Preferences, I ticked `Automatic Mode` under `General`.

Under `Isolation` >> `Multi-Account Containers` >> chose `Isolate Navigations in Permanent Containers whose Target Domain isn't MAC-"Always open in" assigned to that container`. Problem here is that I need to Disable this just so I can save a new site in an existing MAC. If I don't disable it, the new site opens in a TC.  

For example:
1. (The setting under `Isolation` (stated above) is enabled.) Twitter.com is pre-saved in a "Twitter MAC." 
2. Open a new "Twitter MAC" tab, enter tweetdeck.twitter.com but this opens in a TC.
3. Go back to TC Preferences and Disable the Isolation setting.
4. Repeat step 2 and now tweetdeck.twitter.com opens in "Twitter MAC."
5. Click the MAC icon on browser and tick `Always open in Twitter MAC` (under Current Tab Tweetdeck) to save it.
6. At this point, with the setting disabled, I want all sites except twitter.com and tweetdeck.twitter.com to open in a Temporary Container. Moving on with the example, we're on tweetdeck.twitter.com. If I had a, say, Wikipedia link on this page and opened it in a new tab, that Wikipedia opens in "Twitter MAC," which I don't want, I want it in a TC. For that to happen I need to go back and enable the Isolation setting again.

How can I simplify this? Am I using the wrong add-ons/combo?

I open links in a new tab by `Right click` + `T`, I like this because it's the fastest.

TIA.

**Comment by stoically** [comment]
Please see #170.

Quickest way to dis/enable isolation currently is by activating the advanced > keyboard shortcut Alt+I. Another workaround is using [Containerise](https://github.com/kintesh/containerise) instead, which lets you edit assigned domains without navigating to the domain first. Hope that helps.

**Comment by firepainting** [comment]
Thanks! Didn't know about Alt+I. Will be looking into Containerise. Thanks so much for the add-on, I didn't realize its value :) I'm using the right combo after all.

**Comment by firepainting** [comment]
Hi again. I removed MAC and am playing with Containerise, but I can't figure out how to simultaneously log in on one site with two/multiple accounts, e.g., Google with a personal account and a work account. Does TC offer a workaround for this?

**Comment by stoically** [comment]
As [u/okradonkey said](https://www.reddit.com/r/firefox/comments/eh33r0/unless_i_dont_know_how_to_use_the_combo_ff/fcf8jrb/), you can't assign the same domain to multiple containers (yet, might one day be supported by MAC: https://github.com/mozilla/multi-account-containers/issues/1171).

**Comment by firepainting** [comment]
Thanks! Came here to tell you exactly about that :) Will be sticking to Containerise for now.
