### ISSUE TITLE
Temporary Containers for Firefox Android

### ISSUE THREAD

**Issue by skuz-o** [stoically/temporary-containers#354]
i noticed the add-on not being available for the Android mobile version of Firefox, since it's part of the browser setup i do for friends and family

actually the first times i tried i could actually install it into firefox but then it would not work. only after it became signaled as "not intended for this platform", so i guess something changed

so I'd like to ask why this is, and if there are plans to make it available for the android platform

annnnnd...thanks stoically and any other contributors for your work on this great add-on. it's a must-have for me since i discovered it!

hugs

**Comment by stoically** [comment]
Hey, glad you like it. Please see: https://github.com/stoically/temporary-containers/issues/255#issuecomment-490390608
