### ISSUE TITLE
how to load without any container?

### ISSUE THREAD

**Issue by rubaboo** [stoically/temporary-containers#357]
I like TC in automatic mode, but would like to have some sites load without any containers. Not in a permanent container, just no container, as if I don't have MAC nor TC installed in my Firefox. Looked at a bunch of issues here, still not clear if that is possible or not. If not, what would be a suggested setup for what I'm after? One permanent container for all of them? Some mode that is not automatic?

**Comment by stoically** [comment]
Glad you like it. The only way I'm aware of that would achieve that in automatic mode is using [Containrise](https://addons.mozilla.org/firefox/addon/containerise/) and binding domains to "No Container".

**Comment by crssi** [comment]
@rubaboo why would you like to open site in noContainer?
Maybe you would get best answer, if someone understood your needs. 😉

**Comment by rubaboo** [comment]
Because that is how Firefox does it, to begin with. I like the idea of automatic temporary containers by default. But if I want to have exceptions, I should not be forced to install another add-on for that. It should be as simple as adding the site to a whitelist - "no temporary containers for these sites".

**Comment by stoically** [comment]
A workaround in TC would be to disable automatic mode, add a per domain isolation rule with pattern `*`, enable `always open in` for it, and then add domains that should load in no container to the global isolation exclusion list.

This behaves similarly to how "advanced > automatic mode > don't instantly reopen" works.

**Comment by stoically** [comment]
Might also want to tick the two "disable" checkboxes under `always open in` if different target domain isolation isn't desired in temporary/permanent containers.

**Comment by stoically** [comment]
Given there are workarounds and that default automatic mode opens a new TC anyway, so "ignoring" certain domains would mean  actually reopening them in the default container in that case, I'm not interested in implementing such feature at this time.
