### ISSUE TITLE
Bug: "Deletes History Temporary Container"

### ISSUE THREAD

**Issue by opus-x** [stoically/temporary-containers#358]
Activating "Deletes History Temporary Container" (Advanced --> Delete History) does not obey the general setting of Automatic Mode (Advanced --> General) to NOT automatically create a new container when opening a new tab.

**Comment by stoically** [comment]
That's intended behavior, and documented in a tooltip when changing the advanced automatic preference after activating delete history - it reads: `"Deletes History Temporary Containers" always reopen new tabs to avoid leaving traces in recently closed tabs`. Hope that helps.
