### ISSUE TITLE
don't delete container if some domain is configured to always open on it

### ISSUE THREAD

**Issue by siran** [stoically/temporary-containers#370]
- Temporary Containers Version: 1.7
- Firefox Version: 74.0b3 (64-bit)

### Actual behavior
A temporary container is deleted although a domain has been configured to always open in that container

### Expected behavior
5. container tmp-458 shouldn't be deleted because some domain has been configured to always open in that container

### Steps to reproduce
1. Open a new tab -> new temporary container "tmp-458" is created
2. Navigate to any domain, say `t.co`
3. In multi-account-container extension, enable "always open in tmp-458`
(3.b maybe open the same domain in another temporary container to endure it opens again in tmp-458)
4. close all tabs tmp-458
(4.b maybe wait the timeout)
5. container tmp-458 is deleted

### Notes
Attached debug.log and preferences
[debug.log](https://github.com/stoically/temporary-containers/files/4208956/debug.log)
[temporary_containers_preferences_2020-2-15_14.56.24.json.txt](https://github.com/stoically/temporary-containers/files/4208959/temporary_containers_preferences_2020-2-15_14.56.24.json.txt)

**Comment by stoically** [comment]
That's expected behavior. Temporary containers should be, well, temporary - so if you close them, they get deleted. If you want the "Always open in" setting to persist - why not use a permanent container instead? Could even convert the temporary to a permanent one by using popup -> actions -> convert to permanent.

**Comment by siran** [comment]
Note 2:
If I instead create a new container from Multi-Account-Container, then this container doesn't get removed.
I think the issue is that temporary containers are being recognized by the add-on as temporary although I have chosen to use them permanently by enabling the "always open in xxx" option of Multi-Account-Containers.

My use case is to have a quick/easy/convenient way to create containers for domains I visit frequently but that I want to keep isolated from other containers.

**Comment by siran** [comment]
> Could even convert the temporary to a permanent one by using popup -> actions -> convert to permanent.

I didn't know about this. Thanks!

**Comment by stoically** [comment]
Yeah, I think that might be the best candidate for your use-case. It'll be available in the right-click on tab context menu in the future as well: #342

**Comment by stoically** [comment]
Oh, and if you want to make the actions menu the default when opening the popup - you could configure that in the advanced -> popup preferences.

**Comment by siran** [comment]
> Oh, and if you want to make the actions menu the default when opening the popup - you could configure that in the advanced -> popup preferences.

yes, this saves clicks! thanks!
