### ISSUE TITLE
One permanent container per domain

### ISSUE THREAD

**Issue by SeriousM** [stoically/temporary-containers#376]
Hi! I found your extension today and it is great and maybe exactly what I was searching for.

My usecase is that I want to have a permanent/temporary container per domain except I disable the isolation myself so that no domain can share data with other domains.

I tried the settings for Isolation > Per Domain with the rule `/http[s]?://([a-z0-9]+\.)*[a-z0-9]+\.[a-z]+/` which kinda worked, but when I open a domain a second time, a new container was created.

I also tried to convert the current temporary container into a permanent container, but when I open the same domain, a new temporary container will be created.
When I stick the target domain to the permanent container and open the target domain again, the extension is fighting with firefox and prompts me which container should now be used, the new temporary container or the permanent one.

Here are my settings for per domain, everything else is default.

![image](https://user-images.githubusercontent.com/462013/75192591-cb6cdc80-5754-11ea-82a0-5eef8fb085e0.png)

Maybe this extension suits my case, maybe not.. could you help me to find the answer?
I'm a bit lost in this case :(

Thank you very much for your support!

**Comment by stoically** [comment]
One permanent container per domain is basically [what FPI does](https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/), you could use [this Add-on](https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/) to temporarily disable FPI when you need to escape FPI (e.g. for SSO).

Managing permanent containers isn't in the scope of TC, so it probably doesn't fit this use-case.

**Comment by SeriousM** [comment]
I wasn't aware of FPI. TC isn't serving my usecase though... 

Thank you very much!
