### ISSUE TITLE
restoring closed Tabs: Possible?

### ISSUE THREAD

**Issue by Golddouble** [stoically/temporary-containers#386]
- Temporary Containers Version: 1.8
- Firefox Version: 73.0.1

### Actual behavior
I open three Tabs using the addon "Temporary Contaniers" in three different "Temporary Contaniers" in three different Tabs. Then I close one Tab after the other. When all Tabs are closed, I make a right click and choose "restore the latest closed Tab" three times. -> But this way, the just closed Tabs can't be restored.

### Expected behavior
I would like to have the possibility to restore closed Tabs, when this are "temporary container Tabs".

### Notes
When I use the addon "First party isolation" instead of "Temporary Containers addon", then this works as wished.
When I use the Addon "Multi Account Containers" without the addon "Temporary Containers", and open three Tabs in three different Containers, it also works as wished.

Is there a way to get the possibility of restore closed tabs also when using the addon "Temporary Containers"?

Thank you.

**Comment by crssi** [comment]
I had similar experience with the configuration I have used.
It might be a bug/feature, but I was able to resolve with different configuration.

Do you use any rule with a wildcard only?
Or any rule for your search page?

Cheers

**Comment by stoically** [comment]
Restoring tabs (Undo close tab) is possible as long as the TC itself wasn't deleted yet. By default this happens are 15minutes (general preference > "Delete no longer needed Temporary Containers"). I'll look into making that time more customizable in the future, including delaying it until Firefox restart (#363).

FPI and MAC both create and use permanent containers that are never deleted, and hence undo close tab always works with them.

**Comment by Golddouble** [comment]
Thank you. I now have changed the setting "delete Container" from "after the the last tab in it closes" to "default (15min)".
Now it works as wished.

**Comment by stoically** [comment]
Glad it works for you. Added custom removal delays to #363. Closing this as it seems resolved.
