### ISSUE TITLE
Help needed with a reddit container with embedded https://v.redd.it links

### ISSUE THREAD

**Issue by d5ve** [stoically/temporary-containers#388]
I'm using Temporary Containers v1.8 and FF Multi Account Containers v6.2.3 on FF v73.0.1 on linux.

I'm using fresh installs of both TC and MAC with no config changes from the default (apart from setting up a "reddit" container)

What are the suggested steps to go through to have all my reddit browsing working in a "reddit" container?

I have created a "reddit" container and asked MAC to always open reddit.com in there. This does work.

However, if I click a reddit link which is to v.redd.it, like this random link from /all https://v.redd.it/de2z3ft0l2n41 it's redirected to https://www.reddit.com/r/aww/comments/fjot9d/im_a_teacher_and_i_got_the_news_this_morning_that/ inside the "reddit" container as expected, but the video itself won't play. Clicking on the play button just leads to a spinning blue circle and the video never starts playing.

Because the https://v.redd.it link is a redirect, I'm never offered the change to say "always open in the reddit container"

**Comment by stoically** [comment]
That's something you'd have to configure with MAC. Since `v.redd.it` redirects to `www.reddit.com`, it should ask you to open in that container, as long as that specified domain is assigned. Might want to double-check whether `www.reddit.com` is assigned to "Always open in" with MAC, and if it is then that's probably a bug and you might want to open an issue over on their issue tracker.

**Comment by notDavid** [comment]
@stoically As another workaround... would it be possible to make your extension compatible with [Reddit Container](https://addons.mozilla.org/en-US/firefox/addon/contain-reddit/?src=search) ?

**Comment by stoically** [comment]
@notDavid Sure, opened #395 to track that

**Comment by stoically** [comment]
Closing as this seems to be resolved.
