### ISSUE TITLE
[Suggestion] Open any link from a temp container in the same container

### ISSUE THREAD

**Issue by Tyf0x** [stoically/temporary-containers#390]
Hi, developer here and loving this extension for testing multiple accounts.

I haven't been able to figure out if the following behavior is possible to enforce:
* I am using multi-account container
* I have a domain set to always open in the "Work" container: say "https://localhost"
* I open a new temp container and navigate to localhost (no issue there, I wanted to log-in using a different account)
* I then middle-mouse click on a link in this temp tab which opens a new tab. Here is the problem: the new tab will open in the default container configured for the domain instead of staying in the temp container.

My question is: is there a way to configure this extensions to behave like "Once in a temp container, always open links in this container"? This would mean overwriting the multi-account container settings.

Cheers!

**Comment by crssi** [comment]
It is not TC who has control in which container will the page open in your case.
It is a MAC that interferes, since you have configured it to do so.

**Comment by Tyf0x** [comment]
I understand that MAC was the one with this behaviour, but was hoping it was possible to override it (using temp containers being more specific than pre-defined containers).

If this is not technically possible to implement, please let me know and I'll close this suggestion.

Thanks :)

**Comment by stoically** [comment]
This is related to #170. Without APIs on MACs end TC unfortunately can't modify its settings. MAC would also need some sophisticated feature like "don't use the always-open-in preference in the following containers", which doesn't exist.

**Comment by Tyf0x** [comment]
Thanks for the answer, this makes complete sense. Will close for now :)
