### ISSUE TITLE
[Question] Temporary Container in MAC

### ISSUE THREAD

**Issue by kamizoli** [stoically/temporary-containers#406]
I have a question. Sometimes I am opening several bookmarks leading to the same website and would like the new tabs to open in the same container, so login stays the same.
I then assign in MAC an exsisting temorary container, to always open the website in. It is not a use case where I would need a permanent conatiner in MAC.
My question now is, does a so assigned container stays a temporary container. Will Temporary container delete the browsing data for that container when I close the last tab? 
Also does a temporary container which I rename in MAC stays a temporary container and the data will be deleted?
I also use FPI so uMatrix or CAD can?t delete the cookies as I understand.

If Temporary Containers does not delete the browsing data in the above use case it would be a good addition to your addon.
Or if one would have the option to delete even the container data of a permanent container, after the last tabs has closed.

Thank you for your great work!

**Comment by stoically** [comment]
If you want to keep a temporary container you'd have to convert it to a permanent one using the popup (can be activated in the general preferences), by opening "actions" and clicking "convert to permanent". Keeping temporary containers around and making them quasi-permanent is not in the scope of TC.

> I also use FPI so uMatrix or CAD can?t delete the cookies as I understand.

I'm not sure, but I think I've read that both added support for FPI cookies. Not sure about storage and such though.

Hope that helps

> Thank you for your great work!

Thanks!

**Comment by stoically** [comment]
Closing as this seems to be resolved.
