### ISSUE TITLE
External domain not "MAC"-"Always open in" sometimes opened in MAC

### ISSUE THREAD

**Issue by OhSoGood** [stoically/temporary-containers#422]
Being in a MAC tab, I click on the icon on my personal address bar of a website which is not marked a "always open in" that MAC. Despite I have the MAC setting set to "Isolate navigations in permanent containers whose target domains isn't MAC-'Always open in' assigned to that container", the very-same website (whatever it is) often opens in a temp container but not always, i.e. it sometimes opens in the MAC tab.

**Comment by OhSoGood** [comment]
@stoically : thank you. I'll have access to that PC next weekend and I'll grab some log. The main difficulty will be to be able to reproduce the cases.

**Comment by stoically** [comment]
Can't debug this without a log or STR, so closing for now. Please let me know if you have more info.
