### ISSUE TITLE
[Possible Issue] Persistant cookie not being deleted when TC closed

### ISSUE THREAD

**Issue by throwinguppickles** [stoically/temporary-containers#424]
Let me start by saying thank you for the great Add-On. I wish I had looked at Firefox containers years ago.

- Temporary Containers Version: 1.8
- Firefox Version: 77.0

### Actual behavior

I found an issue when I visit https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html that seems to involve a persistant cookie. I noticed that when cdc.gov is visited in a Temporary Container many cookies are reported in Preferences > Privacy & Security > Manage Data but after closing that temporary container, going back to Preferences and pressing F5, to refresh, 1 cookie is still being displayed in Manage Data.

### Expected behavior

All cookies to be deleted when the Temporary Container is closed.

### Steps to reproduce

1. Open a new Temporary Container
2. Visit https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html
3. Close the Temporary Container
4. Navigate to Preferences > Privacy & Security > Manage Data
5. See 1 cookie reported for cdc.gov

### Notes

The only way I found to visit the site and not have 1 cookie left is to block 1st party scripting in uMatirx, then no cookies are reported in Manage Data.

To rule out any conflicts with any of the other Add-Ons I created a new Firefox profile and left all of the Preferences and about:config settings set to default and the only Add-On I installed was Temporary Containers. After closing the temporary container I saw 1 cdc.gov cookie being reported in Manage Data.

I attached a file with my Temporary Container settings.

So far this is the only site I've seen this happen with. Is this expected behavior or is cdc.gov breaking containment somehow?

[temporary_containers_preferences_2020-6-13_1.24.1.txt](https://github.com/stoically/temporary-containers/files/4773834/temporary_containers_preferences_2020-6-13_1.24.1.txt)

**Comment by stoically** [comment]
Thanks for the kind words and the thorough report. Unfortunately this is a known issue, please see: #405

**Comment by throwinguppickles** [comment]
You're welcome and they are well deserved. I'm sorry about creating what is essentially a duplicate issue and thanks for the link to the prior issue. It's good to know that this isn't really a privacy concern and hopefully Mozilla will get it patched sooner rather than later.

I'll go ahead and close this issue since all we can do is wait for Mozilla.

Thanks again and keep up the good work. :)
