### ISSUE TITLE
[Suggestion] Show container number in tooltip on the container icon when number is hidden

### ISSUE THREAD

**Issue by lazyletucce** [stoically/temporary-containers#425]
Hello, that would be pretty useful to have a tooltip with the container number when you hover the container icon in the address bar and have set Container Number setting to 'Hide number', thanks!

i know i could have set it to show number but it bloat the address bar and reduce the available space so an tooltip on icon with the number on hover would be really nice

**Comment by stoically** [comment]
Hey, unfortunately that tooltip isn't something that can be changed, as far as I know. Also currently counting is completely disabled when configured to "Hide number". An alternative might be to enable counting regardless and show the number in the popup. Is there a specific reason that you sometimes want to see the number?

**Comment by lazyletucce** [comment]
yes sometimes i want to check if a tab is isolated or not from another

**Comment by stoically** [comment]
Right, the proper solution I think would be something like #228, in a simple form it could just show the last isolation in the popup somewhere. But showing the number somewhere anyway could be a quick interim solution.

**Comment by lazyletucce** [comment]
i found a way to display it in the tooltip and not in the address bar using userchrome.css with
`#userContext-label { display: none !important; }`*

**Comment by stoically** [comment]
Interesting, thanks for sharing. I've opened https://github.com/stoically/temporary-containers/issues/427 to track the number in the popup thing.

**Comment by stoically** [comment]
Closing as this can't be solved directly by TC. Added a "has workaround" label.
