### ISSUE TITLE
[Feature Suggestion] Ignore tabs moved to an existing container by context menu in automatic mode

### ISSUE THREAD

**Issue by Termuellinator** [stoically/temporary-containers#428]
Hi, i love this addon, but have a small suggestion that would make life a bit easier :)

When in Automatic Mode and want to move a temporary tab (or any tab for that matter) to a permanent one by rightclick -> "open in container" it gets reverted to a new temporary container immediately.
So if you want to do that (for example to add this domain to MACs "always open in") you have to suspend isolation first.

I don't know if it is possible to discern tabs opened by clicking a link from ones opened by "rmb -> open in container", but if that's possible, it would be great to have the option to automatically suspend automatic mode for these tabs :+1:

**Comment by stoically** [comment]
Hey, thanks again.

That sounds like you activated Isolation > Multi-Account Containers. Unfortunately there's no workaround yet. See also #170

**Comment by Termuellinator** [comment]
Thanks for the quick answer! I had that enabled, yes. I thought that was what i wanted, but thanks you your link (didn't find that when searching, sorry) i noticed that to achieve isolation from permanent containers for external links i can also use the global setting "Navigation/Different from Tab and Domain & Subdomain".

I guess i understood the Isolation -> Multi Account Containers wrong - what is the intended usecase for this compared to the global navigation setting?

**Comment by stoically** [comment]
Happy it works for you.

Maybe the [wiki page](https://github.com/stoically/temporary-containers/wiki/Multi-Account-Containers-Isolation) does help clarify the intended use case? If it doesn't, please let me know.

**Comment by stoically** [comment]
Btw, there's also a advanced > keyboard shortcut in the preferences to globally toggle isolation which might be helpful in this case (I'm using it a lot :D).

**Comment by Termuellinator** [comment]
i haven't looked at the shortcuts since i decided to use automatic mode, but good to know anyway ^^
And i really misunderstood MAC isolation then, i didn't catch it having a own wiki-page but only read the one about keeping logins ^^
