### ISSUE TITLE
Load local files (i.e. file://) in automatic mode

### ISSUE THREAD

**Issue by theojepsen** [stoically/temporary-containers#430]
I have automatic mode enabled. When I load a page from the command line, e.g.,

    firefox http://example.com

it opens in a new temporary container, as expected. However, if the URL is a local file, e.g.

    firefox doc/index.html

it does not open in a temporary container. Is there a way to force local files (i.e. with the file:// URL) to open in a temporary container, instead of the default container?

**Comment by stoically** [comment]
It's an Firefox API security limitation which prevents opening [tabs with file:// URLs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create). So AFAIK this unfortunately can't be done.

**Comment by theojepsen** [comment]
I was afraid it was an API issue. Oh well. Thank you!
