### ISSUE TITLE
Automatic mode incompatibility with new "restrict" feature of Containers

### ISSUE THREAD

**Issue by YoAm** [stoically/temporary-containers#439]
When restricting a container to specific sites, and opening a link from within that container, the new tab is placed in no container.

**Comment by stoically** [comment]
Have to look into how MAC implemented it, but I think that can't and probably shouldn't be covered by automatic mode. A workaround that should work is using isolation.

**Comment by stoically** [comment]
Though, the automatic mode description reads "Tab tries to load a website in no container", so maybe it should be covered after all :D

Related: https://github.com/stoically/temporary-containers/issues/432#issuecomment-650782494

**Comment by crssi** [comment]
I am using per domain isolation rule as last of rules to catch cases which would land to non-isolated containers:
Domain: `*`
Always open in: `Enabled`

Maybe you can try that?
Cheers
