### ISSUE TITLE
Debug log instructions on wiki are out of date or incorrect

### ISSUE THREAD

**Issue by roothorick** [stoically/temporary-containers#441]
`tmp.log.DEBUG=true` returns an error:

```
Uncaught ReferenceError: tmp is not defined
    <anonymous> debugger eval code:1
```

- Temporary Containers Version: 1.8
- Firefox Version: 78.0.2

**Comment by stoically** [comment]
Still works for me. How are you opening the add-on background console exactly?

**Comment by roothorick** [comment]
Exactly as described on the wiki.

But I can't reproduce it now... I'll reopen if it happens again and I can find some sort of pattern.
