### ISSUE TITLE
[Suggestion] Option to make Containers not reopen sites when in certain Container

### ISSUE THREAD

**Issue by Randomfly1** [stoically/temporary-containers#445]
- Temporary Containers Version: 7.0.2
- Firefox Version: 78.0.2

Hello, 
I want to use a website with two different accounts but I also want the convenience 
of having the website automatically reopen in my default account container (account no. 1). 
When I want to use my 2nd account and open the site, it automatically redirects me to container 1.
I then have to manually go to the settings and delete whatever sites I want to use in my 2nd account container, so that I won't be redirected.
My solution to this problem would be adding an option to list sites in the 2nd container, that shouldn't be redirected to the 1st container when opened in the 2nd container. 

That way you could still just type in your site and it would open in container 1. But when you want to use the site with your other account, you can just click the reopen in container option.

**Comment by stoically** [comment]
Given the suggestion and the Add-on version you probably opened this issue in the wrong repository. You probably meant to open it in https://github.com/mozilla/multi-account-containers - though, I think a similar issue already exists there, might want to search for it.

**Comment by Randomfly1** [comment]
Oh yes, I'm sorry.
Thanks for telling me!
