### ISSUE TITLE
Addon break close button behavior on wikipedia.org

### ISSUE THREAD

**Issue by krystian3w** [stoically/temporary-containers#446]
### Steps to reproduce

- open [https://en.wikipedia.org/wiki/Wikipedia](https://en.wikipedia.org/wiki/Wikipedia);

- scroll to 1 of 2 photos  "`Jimmy Wales and Larry Sanger`" in [**History** section](https://en.wikipedia.org/wiki/Wikipedia#History).

- open these photo by click;

- close gallery with mouse by click in right close "✖️" button;

<dl><dd>

---

The site suddenly returns to the beginning. Turning off the add-on helps instantly and there is no scrolling to the beginning of the page.

Also html anchors don't help, something overwrites the positions in this case.

</dd></dl>

### Environment

- Temporary Containers Version: `1.9b2`
- Firefox Version: `79` 
- System: Windows 10 pro 20H1 (may 2020 / 2004)

### Actual behavior

<dl><dd>

When you click on the closing button with the mouse **the page suddenly "scroll" to the top**.

A workaround can be the use of the physical <kbd>ESC</kbd> key or the combination <kbd>TAB</kbd> + <kbd>Space bar</kbd>.

</dd></dl>

### Expected behavior

<dl><dd>

An add-on should not interfere with the gallery code when you click on the gallery close "✖️"  button.

There shouldn't be any jumping of the website to the top.

</dd></dl>

### Notes

<dl><dd>

The problem appeared somewhere with Firefox 70+ (in 68/69 it still worked OK).

It's possible that it's a bug in Firefox code requiring additional notification on the `bugzilla` or finding it in the exist thicket of tickets.

In addition, even using the oldest version of Addon `v0.91` seems to confirm this.

</dd></dl>

**Comment by stoically** [comment]
Huh, now that's a really interesting bug. And it seems to actually be triggered by TC. I wonder how this is even possible. I guess it must have something to do with the [content script](https://github.com/stoically/temporary-containers/blob/main/src/contentscript.ts), though, I don't see how that could trigger such behavior, since it doesn't call `preventDefault()` or similar.

**Comment by krystian3w** [comment]
Maybe no longer glitched in Firefox 94.0.1 or Fixed inside addon 1.9.0 stable and newer.
