### ISSUE TITLE
The "Target domain: Different from Tab domain" option doesn't work

### ISSUE THREAD

**Issue by gab12** [stoically/temporary-containers#447]
- Temporary Containers Version: 1.8
- Firefox Version: 78.0.2

### Actual behavior
> requierement : the option "Target domain: Different from Tab domain"
> Actual a link with the same domain but not subdomain is opened  in a new container and new tab.

### Expected behavior
> The link should be open in the same tab in container if the domain is the same.

### Steps to reproduce
 - In temporary Container, Option/Isolation/ Global/Navigation. I selected  "Target Domain : Different from Tab domain" (and not sub domain).
- I go to a website (example https://www.aliexpress.com)
- I click a link in the same domain, but not the same subdomain  (example "login":  https://login.aliexpress.com)

### Notes
- I attached my config file : 
[temporary_containers_preferences_2020-7-24_10.53.13.zip](https://github.com/stoically/temporary-containers/files/4971039/temporary_containers_preferences_2020-7-24_10.53.13.zip)
- in a Private Window / Firefox  remembers history
- to get around the problem, I must add the rule " Exclude Target Domains /Exclusion Pattern  : *.aliexpress.*" in the domain "*.aliexpress.*". In the case for gmx.*in the config file.

Thank you

**Comment by crssi** [comment]
That is as expected... in your case you should use option `Target Domain : Different from Tab Domain & Subdomains`

**Comment by gab12** [comment]
Oups. You are right. Sorry :)
My english is not very good, I misunderstood this option. Thank you

**Comment by crssi** [comment]
Don't be sorry... and welcome. 😄
