### ISSUE TITLE
Switch to upstream firefox-webext-browser

### ISSUE THREAD

**Issue by stoically** [stoically/temporary-containers#448]
https://github.com/jsmnbom/definitelytyped-firefox-webext-browser/issues/31 got fixed, so we can go back upstream once https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46342 gets merged

**Comment by jsmnbom** [comment]
> I just published [`@types/firefox-webext-browser@78.0.1` to npm](https://www.npmjs.com/package/@types/firefox-webext-browser).

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46342#issuecomment-665329613

Just a heads up :)
