### ISSUE TITLE
Exclude links opened by a webextension from isolation

### ISSUE THREAD

**Issue by guser-sudo** [stoically/temporary-containers#456]
Hi!
I use automatic mode and global isolation in general but want to exclude all links opened by a specific webextension.
The extension works by opening one of its included local files in no container and then uses window.location to set the actual target url. That causes the url to be isolated in a new tab of course. The new tab can be prevented by a domain isolation rule for the local file. But then automatic mode still kicks in and opens the url in a TC in the same tab.
How can I stop that?

PS: When I right-click a link and choose to open it in a specific or no container then I expect that to happen and not to be overruled by re-isolation without any explanation or warning. Users probably just consider TC to be buggy.

**Comment by stoically** [comment]
Not sure, but I think adding `/^moz-extension://../` (regexp) as per domain isolation domain pattern and `*` as excluded target domain for that rule should work

> PS: When I right-click a link and choose to open it in a specific or no container then I expect that to happen and not to be overruled by re-isolation without any explanation or warning. Users probably just consider TC to be buggy.

This should only happen when selecting "No Container", for which it's expected because a) it's Automatic Mode's job to prevent No Container tabs and b) there's a history of problems supporting that as a feature, hence why it was removed. If you experience it for permanent containers then that's either a bug or maybe Multi-Account Containers Isolation or something

**Comment by guser-sudo** [comment]
Thanks, but that's what I'm already doing. The problematic part is that automatic mode still opens the url in a TC, even when domain isolation is sucessfully deactivated for that extension. And I can't use 'Ignoring requests to' because I don't know the target domain, only the tab domain (the extension).

**Comment by stoically** [comment]
I see, well, in that case I don't think it's possible to achieve that currently with TC. It'd probably be covered by #397 at some point

**Comment by guser-sudo** [comment]
Just a few thoughts: Do we want/need extensions to be isolated? Is it even sensible/allowed to do so? Should they be excluded from isolation by default? I can hardly imagine someone considered an extension to be isolated when writing it.

**Comment by stoically** [comment]
For Isolation the possibility to exclude WebExtensions does exist, personally I think that's good enough. Automatic Mode should prevent tabs to open in No Container, personally I think it should stay that way by default for all tabs, regardless what opened them - though it'd be nice to be able to configure Automatic Mode on a per rule basis, which could be part of #397 and cover this use case.
