### ISSUE TITLE
Open Link in new Temporary Container tab does not work as expected for twitter pages

### ISSUE THREAD

**Issue by redneb** [stoically/temporary-containers#463]
- Temporary Containers Version: 1.9.1
- Firefox Version: 80.0.1
- OS: Linux x86_64

### Actual behavior
I have noticed that when I open a link to a twitter page with the `Open Link in new Temporary Container tab` option, then even though the page appears to open in a temporary container, if I close it and reopen it immediately with `Ctrl+Shift+T` it then runs in "No Container" mode. Also, if I close it, wait for the "Delete no longer needed Temporary Containers" period and then press `Ctrl+Shift+T`, it will reopen in "No Container" mode.

### Steps to reproduce
1. Run firefox in a new clean profile.
2. Install `Firefox Multi-Account Containers`.
3. Install `Temporary Containers`.
4. Go to https://en.wikipedia.org/wiki/Jack_Dorsey#External_links (you can do that from a "No Container" tab, it doesn't matter).
5. Right click on the link to Dorsey's twitter profile and select `Open Link in new Temporary Container tab`.
6. The twitter page tab now runs in a container called `tmp1`. Close that tab.
7. Press `Ctrl+Shift+T` to reopen the last closed tab.
8. Notice that the reopened tab runs in "No Container" mode.

**Comment by stoically** [comment]
Nice catch, it's not a TC issue tho. This also happens with permanent containers. Right click and select "Open Link in new Container Tab", closing and reopening opens in No Container. So that's a Firefox Bug which would need to get reported [upstream](https://bugzilla.mozilla.org/). It'd be nice if you post the link in case you file the bug.

**Comment by crssi** [comment]
Does this only happens with `Firefox Multi-Account Containers` installed?

**Comment by stoically** [comment]
The bug is not related to Add-ons

**Comment by crssi** [comment]
I see. With the config that I use, I cannot reproduce.
I also do not user MAC, that why I asked.

Cheers

**Comment by redneb** [comment]
I was able to reproduce this without `Temporary Containers` so this is indeed a firefox problem. I filed an [upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1666164) for it.

**Comment by stoically** [comment]
@redneb Thanks for reporting! The bug was closed as dup, related links: https://bugzilla.mozilla.org/show_bug.cgi?id=1665942 & https://github.com/mozilla/multi-account-containers/issues/1867

@crssi That's because Isolation catches it in your case

**Comment by redneb** [comment]
The underlying Firefox issue appears to have been fixed in the newly released Firefox 88.
