### ISSUE TITLE
[Wiki] Information about CAD is outdated

### ISSUE THREAD

**Issue by climbTheStairs** [stoically/temporary-containers#470]
In the ["Comparison"](https://github.com/stoically/temporary-containers/wiki/Comparison#cookies-autodelete) wiki page, it states that CAD does not clean indexedDB and cache. However, CAD [now supports](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.5.0) cleaning more types of site data.

**Comment by stoically** [comment]
Thanks for the hint, fixed
