### ISSUE TITLE
Reopening a tab is impossible

### ISSUE THREAD

**Issue by WhyNotHugo** [stoically/temporary-containers#479]
- Temporary Containers Version: 1.9.1
- Firefox Version: 83.0

### Steps to reproduce

0. Turn on automatic mode.

1. Open any webpage in a new tab.
2. Open another webpage in a second tab.
3. Close the first tab.
4. Press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>t</kbd> (which reopens the last closed tab)

### Actual behavior

A second copy of the second tab is opened.

### Expected behavior

The last closed tab should be reopened.

### Notes

Pressing <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>t</kbd> more times just keeps reopening the same tab over and over. The closed tab is forever lost.

**Comment by mimecry** [comment]
most likely because you've set "Delete no longer needed Temporary Containers" to "After the last tab in it closes"

**Comment by WhyNotHugo** [comment]
Apparently so. I know I changed quite a few settings and I no longer have the issue.

Sorry for the noise :sweat:
