### ISSUE TITLE
statistics: 0 cookies

### ISSUE THREAD

**Issue by basbebe** [stoically/temporary-containers#484]
I started trying out temporary containers a few days ago (and really ilke it so far).  
I switched from Multi-account-Containers + Cookies-Auto-Delete to Temporary Containers + Multi-Account-Containers + FPI

However, On the statistcs site it says that it deleted 0 cookies since then (and I would have expected to be more).

Did I have the wrong expectations or is there something not working?
In settings I deactivated Automatic Mode and Mddle-Click / CMD+Click.

<img width="612" alt="Bildschirmfoto 2021-01-18 um 14 58 30" src="https://user-images.githubusercontent.com/7083188/104924392-422a4e00-5995-11eb-8b16-9fdc3ceec952.png">

**Comment by stoically** [comment]
Might be related to FPI? Could you by chance test without FPI?

**Comment by basbebe** [comment]
this seems to have resolved itself in the meantime.
