### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by stoically** [stoically/temporary-containers#49]
Since Automatic Mode is disabled by default for now, it might be a good idea to integrate a landing page upon first installation to encourage users to enable Automatic Mode. `browser.cookies.getAll` can query by `storeId`, so the landing page could show the total count of all cookies in the default container.

---

To enable Automatic Mode by default a more thorough strategy would be needed since its really invasive and might confuse new users. There should be a way for them to get a choice to switch back to Automatic Mode disable it easily - but with an explanation and course of action to higher the chances of them using Automatic Mode. Instead of showing the user a landing page upon installation - which I would assume most silently ignore - it should show a dialog upon navigation to websites under special circumstances.

--

If the user navigates in a Temporary Container to a website where cookies in the `firefox-default` container are present, a Modal should be shown:

**Temporary Containers is in Automatic Mode and detected that cookies for this website exist in your default container. If you expect to be or stay logged in on this website, you need to take action:**
- I just want Temporary Containers as Private Tab replacement. Disable Automatic Mode and don't show this again
- I don't want to be or stay logged in here, don't show this again for this website
- Copy all cookies [including subdomains] to a new permanent container and redirect this website to the new permanent container in the future. Remember to adjust eventual Cookie Cleaning Add-ons to respect containers and/or whitelist the cookies after you clicked this button
- I know what I'm doing - don't show this again

--

If the user navigates in a Temporary Container to a website and cookies are set (no cookies for the website in the `firefox-default` container), a Modal should be shown:

**Temporary Containers is in Automatic Mode and detected that this website created cookies. If you expect to stay logged in on this website after closing the Temporary Container, you need to take action:**
- I just want Temporary Containers as Private Tab replacement. Disable Automatic Mode and don't show this again
- I don't want to stay logged in here, don't show this again for this website
- Copy all cookies [including subdomains] to a new permanent container and redirect this website to the new permanent container in the future. Remember to adjust eventual Cookie Cleaning Add-ons to respect containers and/or whitelist the cookies after you clicked this button
- I know what I'm doing - don't show this again

**Comment by jrie** [comment]
The option "I dont want to stay or be logged in here" - should function for the tab, not for the whole system itself.

So you might want to ask for that permission, to store data privately or not, in every case.

But the latter, you cannot guarantee, without knowing the particular cookie manager, what is allowed or ain't. And you have to ensure that the "other add-on" is keeping this guidelines, you promise in your dialog.And I guess, you can't keep up that.

There should be some slighty introduction, on a user using the add-on the first or second time - "like" "tip of the day" in other applications and inform the user.

But - what is very new to me, you want to introduce permanent containers, which would be great for me in terms of "Flag cookies" - but I guess, its hard to handle what should be added to a session (/container type) and what not.

**Comment by stoically** [comment]
> The option "I dont want to stay or be logged in here" - should function for the tab, not for the whole system itself.

"I dont want to stay or be logged in here, don't show this again for this website" in this case means more specifically "I dont want to stay or be logged in here while in Temporary Containers". So it would just affect not showing the dialog for that domain while in a Temporary Container. Other tabs are usually in their own Container, if you're in Automatic Mode.

> But the latter, you cannot guarantee, without knowing the particular cookie manager, what is allowed or ain't.

The cookie managers I know of for Firefox don't clean Container cookies by default. You pro-actively have to configure that. So if you're already know what containers are and configured your cookiemanager to handle container cookies, I'd assume you a) know what to do to ensure that the cookies copied over to the new permanent container stay intact after copying b) advanced anyway and click "I know what I'm doing"

> There should be some slighty introduction, on a user using the add-on the first or second time - "like" "tip of the day" in other applications and inform the user.

The introduction is currently on the addons.mozilla.org - but I guess you're right and it could at least show that on Installation too, for those that are willing to read.

> but I guess, its hard to handle what should be added to a session (/container type) and what not.

Multi-Account Containers and Temporary Containers both use the underlying Container feature from Firefox. So if I say "permanent container", I really just mean a container that doesn't get removed. So in terms of Flag cookies, the containers look the same - no additional work needed

**Comment by stoically** [comment]
Dropping plans to implement Landing Page (too annoying) or Onboarding with Automatic Mode per default (too hard) for now. Maybe I'll come back to it one day.
