### ISSUE TITLE
Per-Container privacy settings (like resistFingerprinting)

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [stoically/temporary-containers#51]
Firefox nowa Fingerprint protection, it it possible to enable it for a temporary container? (with fingerprint not activated globally?)

**Comment by stoically** [comment]
Hi, unfortunately privacy settings in Firefox are global. Related Issue: https://github.com/mozilla/multi-account-containers/issues/318 that you could vote for.

It might be possible to change the [privacy settings](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy) on the fly when using a Temporary Container and then back again when using permanent or default containers - but that would also affect all open tabs at this point. So if tabs in Temporary Containers try to fingerprint in intervals, they might at one point get the not resisted results when switch back to non Temporary Containers. So I don't think that's a good idea.

On a side-note: Even though the configuration is called `privacy.resistFingerprinting` - you should keep in mind that everything that makes you look more unique in comparison to others, also makes your fingerprint more unique. That includes Adblockers, resistFingerprinting, Canvas Blockers - anything really that most people don't do. It would be another story if those things were enabled by default, but they're not.

**Comment by ZatsuneNoMokou** [comment]
👍 added :)
I could say that Nothing replace native stuff ^^ (I don't use Adblock plus, I use uMatrix + uBlock Origin by the way).

**Comment by stoically** [comment]
It might be an interesting idea to get in touch with [Canvas Blocker](https://github.com/kkapsner/CanvasBlocker) and ask if it might be possible to support Temporary Containers - in the sense that every new Temporary Container gets a new persistent white. On top of that Temporary Containers could try to fake User-Agents and other values to match that of the Tor Browser. That would give Temporary Containers a significant different fingerprint than permanent or no-container tabs.

**Comment by stoically** [comment]
Closing this in favor of the Issue over at MAC, should this get platform-support I'm happy to reopen.
