### ISSUE TITLE
Context menu preferences inverses

### ISSUE THREAD

**Issue by jbnkx** [stoically/temporary-containers#512]
- Temporary Containers Version: 1.9.2
- Firefox Version: 90.0

### Actual behavior
In preferences > advanced > general > context menu : unchecking doesn't disable the context menu
Rechecking inverses the behavior -> behavior and display are in contradiction.

### Expected behavior
Context menu should show when preference is checked
Context menu should NOT show when preference is unchecked

### Steps to reproduce
1. Fresh install, go to preferences > advanced > general > context menu
2. Uncheck "show temporary container entry in the right click on links context menu"
3. Right click on any link > still in menu
4. Recheck "show temporary container entry in the right click on links context menu"
5. Right click on any link > doesn't show in the menu anymore

**Comment by stoically** [comment]
Nice catch, that's a weird one. That used to work, I'm really curious how that broke.

**Comment by stoically** [comment]
While trying to debug this it turned out that it actually works as expected, but Firefox seems to lag behind with regards to updating the setting internally. Eventually the correct context menu will be shown. So this would need to be reported upstream on Firefox's bugzilla.
