### ISSUE TITLE
[Feature request] Expose text links for new container in context menu

### ISSUE THREAD

**Issue by vulpes9** [stoically/temporary-containers#529]
- Temporary Containers Version:     1.9.2
- Firefox Version: 91.0.1 ESR

### Actual behavior

![grafik](https://user-images.githubusercontent.com/75497157/131480944-39223f39-c007-4b16-bf71-e72ed04f7f96.png)

### Expected behavior

![grafik](https://user-images.githubusercontent.com/75497157/131481018-3a039943-3580-4a4b-98c4-7640fd865f99.png)

### Steps to reproduce

1. right click unformatted selected text links
2. there is only the normal "open link by firefox"
3. you can only manually copy links to a new container

### Notes

This is a "nice to have feature". If you somehow can expose the "open link in new temporary container tab" for also manual selections of links, this would be fun. It is something to do if you feel like adding extra functionality. I don't know how firefox does this internally, but I guess they regex check if a string is a potential URL. How else would I they know? If it has http(s) at the beginning, that alone is a good indicator.

![grafik](https://user-images.githubusercontent.com/75497157/131481557-261b12e2-d122-404d-8b9b-f29dc3c857a4.png)

Cheers, and thanks for years of extra privacy.

**Comment by stoically** [comment]
Would be a nice to have feature indeed, probably duplicate of https://github.com/stoically/temporary-containers/issues/423

Also impressive stats you got there :sweat_smile:

**Comment by vulpes9** [comment]
Thank you and yes! I close this, but interest in https://github.com/stoically/temporary-containers/issues/423 being resolved (someday) is still high. Else copy paste and CTRL+T must do the trick. Your addon + ublock + umatrix is the best possible privacy shield on the normal surface web!
