### ISSUE TITLE
New temporary container for serarch context menu.

### ISSUE THREAD

**Issue by 1Nick1Name** [stoically/temporary-containers#534]
Is there a way to open the context search, in a new temporary container, instead of reusing the current?

Context:
When you are on a website you can mark some text and use the context menu to open a new search with your current search engine using the marked text as the search term. When I use that feature a new tab is opened using the container of the page where I issued the search from. 

I'd rather have it open in a new Container. 

Is this possible? If so, how do I configure that?

**Comment by crssi** [comment]
I am using DDG as default search provider and I have set this behavior the followng way:
![image](https://user-images.githubusercontent.com/17024151/132987752-6d0b80b8-a1ab-4aa0-be15-069b3f9fd674.png)

**Comment by 1Nick1Name** [comment]
Yes, thanks a bunch. Exactly what I was looking for.
