### ISSUE TITLE
Temporary container tabs closed by quitting the browser aren't cleaned

### ISSUE THREAD

**Issue by YellowWords** [stoically/temporary-containers#539]
- Temporary Containers Version: 1.9.2
- Firefox Version: 93.0

### Actual behavior
Temporary container tabs closed by quitting the browser aren't cleaned.

### Expected behavior
Temporary container tabs closed by quitting the browser should be cleaned up on quit.

### Steps to reproduce

1. In Firefox preferences:
a. Disable `Cookies and Site Data > Delete Cookies and site data when Firefox is closed`
b. Disable `Restore previous session`
2. In Addon settings, set `Delete no longer needed Temporary Containers` to `After the last tab in it closes` (just to make it faster to demonstrate, it isn't cleaned regardless what this setting is) 
3. Open any website that sets a cookie in a temporary container.
4. Quit the browser without closing the tab.
5. Reopen browser
6. Go to Firefox preferences: `Cookies and Site Data > Manage Data` - Cookie from the temporary container is still there

### Notes
I happened to look at my browser data recently and was very negatively surprised to see data from > 8 months ago in there, even though temporary containers should clean it quickly. After some trial and error I eventually discovered that the expected cleanup of temporary containers doesn't happen if you quit the browser instead of closing the tab.

You can work around this issue by setting `Cookies and Site Data > Delete Cookies and site data when Firefox is closed` in preferences. However this is a bit annoying when using permanent containers for example following [this guide](https://medium.com/@stoically/enhance-your-privacy-in-firefox-with-temporary-containers-33925cd6cd21). I use this for some web pages to have a persistent login, but this led me to disable this setting since it clears out also permanent containers.

This may be an issue with my expectations - I thought that the temporary container would be cleaned regardless of how it's closed, but it's actually only cleaned on tab close, not if the browser quits. I don't know how hard it is to do what I expected here - That the temp containers are cleaned up on quit. Another option might be to set `Delete Cookies and site data when Firefox is closed` from the addon - This might be friendlier to the user because otherwise you can get a lot of leaking in the cleanup over time. It's also kind of subtle and hard to spot because it does clean when you close the tab like you would expect.

**Comment by stoically** [comment]
Maybe you're affected by #371 since normally it does remove all containers. To make sure, try with a fresh profile and just TC installed.

**Comment by YellowWords** [comment]
Hello, thanks for taking the time!
I don't use Firefox sync. I did try to make a new profile with just temporary containers installed, but the issue still happens in the same way in that profile. Additionally, I notice localstorage isn't cleaned even if you close the tab instead of the browser.
I'm [attaching](https://pastebin.com/2jLHD2g5) my preferences file, is there anything else I can try?

**Comment by stoically** [comment]
Providing a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) would be helpful. However, please note that it should be enough to enable the sync feature in the Multi-Account Containers extension to trigger the bug described in #371, Firefox doesn't need to be logged-in to Firefox Sync.

**Comment by Gitoffthelawn** [comment]
> Providing a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) would be helpful. However, please note that it should be enough to enable the sync feature in the Multi-Account Containers extension to trigger the bug described in #371, Firefox doesn't need to be logged-in to Firefox Sync.

Is there a way to 100% completely disable Firefox Sync?  I've tried a few settings over the years, but browser data still winds up in Firefox's sync storage within the local profile.
