### ISSUE TITLE
Sites with unassigned default container do not have the option pre-selected (anymore)

### ISSUE THREAD

**Issue by drupov** [stoically/temporary-containers#548]
With the latest update now when I open a site, that is assigned to a container, but not configured with "Remember my decision for this site" the main option is not pre-selected.

Previously I could easily hit enter, if I wanted to open the site right away in that container.

Now as it is not pre-selected, this is more cumbersome, as I need to hit Tab several times in order to reach that option.

(In the below screenshot the "Open in w Container"-button was pre-selected)

![image](https://user-images.githubusercontent.com/1836325/143565413-21c77d30-1d98-4aac-8c44-7756e641c926.png)

**Comment by stoically** [comment]
That's a report for https://github.com/mozilla/multi-account-containers/issues/

**Comment by drupov** [comment]
My bad, sorry and thanks!

There is a issue over there already, if someone stumbles upon that one here: https://github.com/mozilla/multi-account-containers/issues/2217
