### ISSUE TITLE
Container Isolation

### ISSUE THREAD

**Issue by stoically** [stoically/temporary-containers#56]
- [x] Preference for "Container Isolation" Global and per Website: Every Tab opened from a container - even when opened programmatically - should open a new Temporary Container
- [x] Preference for "Multi-Account Containers Isolation per Container": When opening a domain in its assigned container, only requests to domains that are assigned to the container are allowed to load. Every other request automatically opens a new Temporary Container.

Like "Always per Website" will Isolation not work if the website is assigned with Multi-Account Containers. Official support from MAC could help.

Depends on: #29 
Related: https://github.com/mozilla/multi-account-containers/issues/655 https://github.com/mozilla/multi-account-containers/issues/419 https://github.com/mozilla/multi-account-containers/issues/847 https://github.com/mozilla/multi-account-containers/issues/1016

**Comment by stoically** [comment]
Pulled the feature with version 0.68 - there are bugs in combination with Multi-Account Containers I hadn't considered.

**Comment by stoically** [comment]
Published version 0.70 with the feature - doesn't handle MAC Confirm pages at all, because its too flaky at this point. Maybe we get official support from MAC to handle that.

**Comment by r-a-y** [comment]
Just tested and I'm loving this feature, particularly the "Isolation > Multi-Account Containers" option!

This extension just keeps getting better and better!  Thanks stoically!
