### ISSUE TITLE
Thousands of temp containers left inside Multi-Account Containers 

### ISSUE THREAD

**Issue by AdKiller** [stoically/temporary-containers#571]
I noticed I have thousands of tmp containers inside Multi-Account Containers. How do I get rid of them all at once?

I do not use Firefox Sync.

Things I tried:

"Delete no longer needed Temporary Containers: after the last tab in it closes" this was set for a long time. I changed it. 
Change "Container Number" to "Reuse available numbers" and "Keep counting until browser restart"

- Temporary Containers Version: 1.9.2
- Firefox Version: 97.0.1

**Comment by stoically** [comment]
Not using Firefox Sync isn't relevant. Relevant is whether you activated the sync feature in MAC. See https://github.com/stoically/temporary-containers/issues/371#issuecomment-1050519080

**Comment by AdKiller** [comment]
Under Firefox Multi-Account Containers, Firefox Account Sync was not enabled.

**Comment by stoically** [comment]
Closing in favor of https://github.com/stoically/temporary-containers/issues/371
