### ISSUE TITLE
Disabling Alt+Shift+T breaks the extension button

### ISSUE THREAD

**Issue by anewuser** [stoically/temporary-containers#65]
- Temporary Containers Version: 0.63
- Firefox Version: 58.0.2
- Windows
- Using "Deletes History Temporary Container" by default

### Actual behavior
Disabling `Advanced` →  `General` →  `Alt+ Shift + T` makes the extension button stop working.

Please check if you can reproduce this. If you can't, I'll post the full list of settings and generate a debugging log.

**Comment by stoically** [comment]
Can confirm, this got actually introduced with the keyboard shortcut settings themselves. Thanks for the report.

Out of curiosity - did you just tweaked your preferences or did <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> conflict with something in your case?

**Comment by anewuser** [comment]
I just don't use it. There has been no other conflict.

**Comment by stoically** [comment]
Just published version 0.64 with the fix. And thanks for the additional information, glad there's no other conflict.
