### ISSUE TITLE
Automatically create "Deletes History Temporary Containers" does not work for specified Websites

### ISSUE THREAD

**Issue by bstecklum** [stoically/temporary-containers#69]
- Temporary Containers Version: 0.63
- Firefox Version: 58.0.1
- Operating System + Version: Ubuntu 17.10
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version: 

### Actual behavior
Automatically create "Deletes History Temporary Containers" instead of normal Temporary Containers is activated
Spefied Websites open in normal Temporary Container

### Expected behavior
I would expect that the choice to create  "Deletes History Temporary Containers" automatically is applied to the per Website setting too.

### Steps to reproduce

1. ..
2. ..
3. ..

### Notes
..

**Comment by stoically** [comment]
Can confirm, that should be the case. I'll look into it, thanks for the report.

**Comment by bstecklum** [comment]
Sorry, I do not get a different result after updating the add-on. It seems from the source code  that there should be a new menu item in "Alawys per  website" but that does not show up.

**Comment by stoically** [comment]
You're right, the change wasn't published. You can use the new advanced preference now with version 0.65. Let me know if something doesn't work as expected.

**Comment by bstecklum** [comment]
Something is odd now, I cannot save website patterns. Pressing the save button
just takes me to the general menu item.

**Comment by stoically** [comment]
That's bad. Thanks for letting me know so fast. I've disabled version 0.65. Could you open the DevTools on the preferences/options page by pressing Ctrl+Shift+I and see if there are any errors? Maybe also reloading (F5) and pressing save and see if errors pop up? That would be really helpful because I can't reproduce, it works for me. :(

**Comment by stoically** [comment]
Also, are your other preferences / website patterns (if any) still intact?

**Comment by stoically** [comment]
In case you can't see any errors, could you then please try [0.66beta1](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/versions/beta) and see if it shows an error? I've added additional debugging. Sorry for the hassle.

**Comment by bstecklum** [comment]
There  was something wrong with my FF (e.g. noscript stalled) so I restarted.
The error is gone now and there are no messages from 0.66beta1 on the web console.

With both

Automatically create "Deletes History Temporary Containers" instead of normal
Temporary Containers

and

Open New "Deletes History Temporary Containers" for Website patterns configured
in "Always per Website" instead of normal Temporary Containers

activated it works now as expected. One could think of if the "Always by
website" setting in Advanced/Delete History may override that of "Automatically
create "Deletes History Temporary Containers""

Thanks!

**Comment by stoically** [comment]
> There  was something wrong with my FF (e.g. noscript stalled) so I restarted.

Ah, phew. That might explain it. Thanks for checking.

> One could think of if the "Always by website" setting in Advanced/Delete History may override that of "Automatically create "Deletes History Temporary Containers""

In fact, just configuring the advanced "Always per website" Deletes History preference works without activating "Automatically create Deletes History Containers". So in a way it does overwrite it.

At some point I'm gonna add some more documentation about that. Thanks for the feedback.

Published version 0.66 now. Let me know if something else doesn't work as expected.

**Comment by bstecklum** [comment]
On 04.03.2018 20:41, stoically wrote:
>
>     There was something wrong with my FF (e.g. noscript stalled) so I restarted.
>
> Ah, phew. That might explain it. Thanks for checking.
>
>     One could think of if the "Always by website" setting in Advanced/Delete
>     History may override that of "Automatically create "Deletes History
>     Temporary Containers""
>
> In fact, just configuring the advanced "Always per website" Deletes History
> preference works without activating "Automatically create Deletes History
> Containers". So in a way it does overwrite it.
>

That does not seem to be the case. I had to activate both to get it work.

**Comment by stoically** [comment]
Oh. Yeah, I've actually included that, ha, not sure why. Changed it accordingly. Thanks for noticing.

Added also a tooltip to "Automatically create Deletes History Containers" that reads

> This affects Automatic Mode, Toolbar Icon and the right-click context menu entry

Both will be included in the next version.
