### ISSUE TITLE
Ignoring requests to addons.mozilla.org

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/temporary-containers#81]
I noticed in the release notes for 0.68:

- *Ignoring requests to addons.mozilla.org completely now since requests can't get canceled anyway*

I wonder if this should be an option, because the user can enable normal interactions with addons.mozilla.org, by setting `privacy.resistFingerprinting.block_mozAddonManager` to `true`.

**Comment by stoically** [comment]
Didn't know that setting is a thing. I'll add it as advanced preference with a hint to the setting. Thanks for letting me know.

**Comment by Gitoffthelawn** [comment]
You're welcome. :-)

**Comment by stoically** [comment]
Just published version 0.72 with advanced preferences to deactivate ignoring requests to AMO and Pocket #52. Let me know if something doesn't work as expected.
