### ISSUE TITLE
Option to remove tab underline

### ISSUE THREAD

**Issue by grenzor** [stoically/temporary-containers#83]
Is it possible to add the option to not add the colored tab underline? I find that the indication of using containers in the address bar is enough for me

**Comment by stoically** [comment]
Hi, you can use CSS in your userChrome.js to achieve that. [Here's a short guide](https://github.com/stoically/temporary-containers/wiki/Container-Colors) and [here's related issue](https://github.com/stoically/temporary-containers/issues/61). Hope that helps, let me know if not.

**Comment by grenzor** [comment]
Thanks, that is helpful. But I've read userChrome.css has a possibility of being removed in the future, so maybe it's better to have this option within the addon?

**Comment by stoically** [comment]
Glad it helped. Unfortunately there's no way to change the color to something else with the API yet. If it gets supported, I'll happily implement it too.
