### ISSUE TITLE
Custom time for Delete no longer needed Temporary Containers

### ISSUE THREAD

**Issue by grenzor** [stoically/temporary-containers#85]
Currently, users only have to the option between deleting containers immediately or 15 minutes after last tab close. It would nice to be able for users to define how long to keep the containers after last tab close.

**Comment by stoically** [comment]
I'm curious, what's your use-case for a custom time? I didn't implement custom time or "until the browser starts" because the container removal code is a bit messy and would need some refactoring in order to take care of orphaned containers that couldn't get removed when they're meant to get removed (the Firefox API does its own thing sometimes).

**Comment by grenzor** [comment]
I'd personally like to change the time for deletion to something shorter like 15 seconds or 1 minute. This gives me enough time to undo a tab if really needed yet won't keep inactive containers open longer than needed for my use (imo 15 mins just seems too long for me even if it might be fine in terms of security/privacy).

**Comment by stoically** [comment]
Well, coincidentally you already have 15seconds time with the "after the last tab closes" preference

https://github.com/stoically/temporary-containers/blob/3e41bcab2b1177a037c8b46c914aad63454e7de3/src/background/container.js#L310

So in case that fits your needs I'd be in favor of not implementing a custom time at this point.

**Comment by grenzor** [comment]
Ah I see. Is it possible for you to add extra dropdown options similar to the delete 15 minutes after last tab but for 2 minutes and 5 minutes (if it doesn't take too much work to implement it)? That would give a few more options for users so that custom time won't really be needed.

**Comment by stoically** [comment]
Just published version 0.72 with 2minutes and 5minutes as alternative removal times. I didn't add 1minute since I feel it's too close to what happens with the "after the last tab in it closes" option anyway. Hope it fits your needs. Let me know if something doesn't work as expected.

**Comment by grenzor** [comment]
Thanks, these timings are ok for me.
