### ISSUE TITLE
Endless loop opening new tabs together with Containerise addon

### ISSUE THREAD

**Issue by falolaf** [stoically/temporary-containers#88]
- Temporary Containers Version: 
0.71

- Firefox Version: 
58.0.2

- Operating System + Version: 
Windows 7

- Non-default Options/Preferences in Temporary Containers: 
Automatic mode

- Other installed Add-ons + Version: 
Containerise 2.1.0
Firefox Multi-Account Containers 6.0.0

### Actual behavior
When I in Containerise have set a domain to open in "No Container" and also set "Automatic mode" in Temporary containers addon Firefox will open an "infinite" number of new tabs if trying to open the domain which is forced by Containerise to open in No Container. (I have obviously not tested infinity, I stopped at 700+.)

### Expected behavior
Not sure how to actually handle this case.

### Steps to reproduce
1. In Containerise: Assgin a domain to open in No Container
2. In Temporary Containers: Enable Automatic mode
3. Ctrl+T to open a new temporary container
5. Type in domain assigned in no. 1 above. Click enter
6. Watch FF endlessly open new tabs

### Notes
..

Sorry, no time to do below for now...

**Comment by stoically** [comment]
Hi, thanks for taking the time to report the Issue. I'm already working on [compatibility with Containerise](https://github.com/kintesh/containerise/issues/17). You can follow progress in #15 

However, it might be worth to implement a safety measure to prevent Add-on incompatbilities to endlessly spawn new tabs. I'll look into that too.

**Comment by stoically** [comment]
By the way, you might want to report this to Containerise too, so they can maybe consider adding a safety measure too, since this is not solely a Temporary Containers issue.
