### ISSUE TITLE
Convert Temporary to Permanent Container

### ISSUE THREAD

**Issue by rgamici** [stoically/temporary-containers#95]
Creating new permanent containers (usually with firefox or multi-account add-on) is awful.
You need to create a new one, and then open the website you want.
If you already opened I website, and then decided to create a custom permanent container for that, you need to start from the beginning.
The temporary containers does not have this problem as it already creates a new container, but it does not make them permanent for frequent use.

What if this addon do not delete the temporary containers that had their name (or icon) changed?
It would make it very easy to create permanent containers for specific websites after you opened it, and decided that it would be better if it had a permanent container.

**Comment by stoically** [comment]
Interesting idea. This might be a good candidate for the address bar popup #32, which could expose an explicit "convert to permanent container" button. I'm personally not in favor of making it an implicit behavior by just editing the container.

**Comment by Perflyst** [comment]
I have seen that it is already built into version 0.79beta4. You can turn temporary containers into permanent ones and delete history containers into normal temporary or permanent ones. However, there is no function to turn a normal temporary into a delete history, just like a permanent one into a temporary or a delete history container.

Maybe you can add these features?

**Comment by stoically** [comment]
> turn a normal temporary into a delete history

Adding buttons to Open the Tabs current URL in a new Temporary Container or Deletes-History Temporary Container sounds like a good idea. I'll look into adding those. "Converting" would require cleaning the underlying cookies & storage (in the default container) for just the current URL, which is AFAIK not possible.

> just like a permanent one into a temporary or a delete history container.

I'm not sure about adding the possibility to convert permanent containers to temporary ones. I feel like adding and using permanent containers is an explicit decision and accidentally deleting them might be a really bad UX. Do you see an actual use-case?

**Comment by Perflyst** [comment]
The only use I can think of is that the tab was accidentally opened in a permanent one. But you're right, how often will that happen...

**Comment by stoically** [comment]
I guess you mean accidentally opening an URL in a permanent container and with that polluting its storage. This probably happens often - a reason why the MAC Isolation feature was added. While converting the whole permanent container into a temporary one in this case seems like a radical decision, I can see why one would want to do that anyway. I'll look into adding it too.

**Comment by stoically** [comment]
> turn a normal temporary into a delete history

What I said earlier about "Converting would require cleaning the underlying cookies & storage" was with Tabs in the "Default Container" in mind, not in regular temporary containers. The only problem I see with actually "Converting" a normal temporary into a deletes history temporary container is that a user could assume that it will delete the whole tabs (or containers) history, which would not be the case, since history isn't tracked for normal temporary containers. So I think just adding the "Open the Tabs current URL in a new (Deletes History) Temporary Container" buttons is the right thing to do here anway.

**Comment by stoically** [comment]
Just published version 0.80 with the following available "Actions" in the Icon Popup (available by clicking the Menu-Icon in the Popup):

- [x] Convert Temporary to Permanent Container 
- [x] Convert Permanent to Temporary Container 
- [x] Open current Tab URL in new Temporary Container
- [x] Open current Tab URL in new "Deletes History Temporary Container" (if history permission was given)
- [x] Open a new "Deletes History Temporary Containers" tab (if history permission was given)
- [x] Convert "Deletes History Temporary Containers" to regular Temporary Containers to prevent deleting of history

Let me know if something doesn't work as expected.

**Comment by Unessential** [comment]
I know this is a 2 year old issue, but Just to be clear, As an alternative to using the toolbar icon, the conversions can be done by renaming the containers to not include the prefix to make them permanent,  or to rename to prefix+number to make permanent containers temporary right?
