### ISSUE TITLE
loadBookmarksInBackground not working with Temporary Containers

### ISSUE THREAD

**Issue by MadClown** [stoically/temporary-containers#97]
- Temporary Containers Version: 0.73
- Firefox Version: 59
- Operating System + Version: Windows 10 1709
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version: Multi-Account Containers 6.0.0

### Actual behavior
I have loadBookmarksInBackground set to true, but middle clicking bookmarks always opens in the foreground through temporary containers. MAC use to also have this behavior, but since 6.0.0, it now opens bookmarked sites assigned to it in the background.

### Expected behavior
Middle clicking with the mouse wheel opens bookmarks in temporary containers in the background if loadBookmarksInBackground is set to true.

### Steps to reproduce

1. Set loadBookmarksInBackground to true.
2. Open any bookmark not assigned to MAC with middle click.

**Comment by stoically** [comment]
Hi, thanks for the report. Can confirm, this should be the case.

**Comment by stoically** [comment]
Just published version 0.77 with the fix. Let me know if something isn't working as expected.
